#ifndef __REGS_MSS_COMMON_DEF_H__
#define __REGS_MSS_COMMON_DEF_H__

#ifdef __ASSEMBLER__
#define _64bit(x) x
#else /* __ASSEMBLER__ */
#ifdef __tile__
#define _64bit(x) x ## UL
#else /* __tile__ */
#define _64bit(x) x ## ULL
#endif /* __tile__ */
#endif /* __ASSEMBLER */



#ifndef __DOXYGEN__

/*
 * Device Info.
 * This register provides general information about the device attached to
 * this port and channel.
 */
#define MSS_COMMON_DEV_INFO 0x0000
#define MSS_COMMON_DEV_INFO__LENGTH 0x0001

#define MSS_COMMON_DEV_INFO__TYPE_SHIFT 0
#define MSS_COMMON_DEV_INFO__TYPE_WIDTH 12
#define MSS_COMMON_DEV_INFO__TYPE_RESET_VAL 0
#define MSS_COMMON_DEV_INFO__TYPE_RMASK 0xfff
#define MSS_COMMON_DEV_INFO__TYPE_MASK  0xfff
#define MSS_COMMON_DEV_INFO__TYPE_FIELD 0,11
#define MSS_COMMON_DEV_INFO__TYPE_VAL_PCIE 0x1
#define MSS_COMMON_DEV_INFO__TYPE_VAL_TRIO 0x14
#define MSS_COMMON_DEV_INFO__TYPE_VAL_CRYPTO 0x16
#define MSS_COMMON_DEV_INFO__TYPE_VAL_RSHIM 0x21
#define MSS_COMMON_DEV_INFO__TYPE_VAL_GGA_COMP 0x28
#define MSS_COMMON_DEV_INFO__TYPE_VAL_GGA_CRYPT 0x29
#define MSS_COMMON_DEV_INFO__TYPE_VAL_GGA_REGEX 0x2a
#define MSS_COMMON_DEV_INFO__TYPE_VAL_MMC 0x2b
#define MSS_COMMON_DEV_INFO__TYPE_VAL_MSS 0x46
#define MSS_COMMON_DEV_INFO__TYPE_VAL_TILE 0x82
#define MSS_COMMON_DEV_INFO__TYPE_VAL_SMMU 0x85
#define MSS_COMMON_DEV_INFO__TYPE_VAL_GIC 0x86

#define MSS_COMMON_DEV_INFO__DEVICE_REV_SHIFT 16
#define MSS_COMMON_DEV_INFO__DEVICE_REV_WIDTH 8
#define MSS_COMMON_DEV_INFO__DEVICE_REV_RMASK 0xff
#define MSS_COMMON_DEV_INFO__DEVICE_REV_MASK  0xff0000
#define MSS_COMMON_DEV_INFO__DEVICE_REV_FIELD 16,23

#define MSS_COMMON_DEV_INFO__REGISTER_REV_SHIFT 24
#define MSS_COMMON_DEV_INFO__REGISTER_REV_WIDTH 4
#define MSS_COMMON_DEV_INFO__REGISTER_REV_RESET_VAL 0
#define MSS_COMMON_DEV_INFO__REGISTER_REV_RMASK 0xf
#define MSS_COMMON_DEV_INFO__REGISTER_REV_MASK  0xf000000
#define MSS_COMMON_DEV_INFO__REGISTER_REV_FIELD 24,27

#define MSS_COMMON_DEV_INFO__INSTANCE_SHIFT 32
#define MSS_COMMON_DEV_INFO__INSTANCE_WIDTH 4
#define MSS_COMMON_DEV_INFO__INSTANCE_RMASK 0xf
#define MSS_COMMON_DEV_INFO__INSTANCE_MASK  _64bit(0xf00000000)
#define MSS_COMMON_DEV_INFO__INSTANCE_FIELD 32,35


/*
 * Device Control.
 * This register provides general device control.
 */
#define MSS_COMMON_DEV_CTL 0x0008
#define MSS_COMMON_DEV_CTL__LENGTH 0x0001

#define MSS_COMMON_DEV_CTL__NDN_ROUTE_ORDER_SHIFT 0
#define MSS_COMMON_DEV_CTL__NDN_ROUTE_ORDER_WIDTH 1
#define MSS_COMMON_DEV_CTL__NDN_ROUTE_ORDER_RESET_VAL 0
#define MSS_COMMON_DEV_CTL__NDN_ROUTE_ORDER_RMASK 0x1
#define MSS_COMMON_DEV_CTL__NDN_ROUTE_ORDER_MASK  0x1
#define MSS_COMMON_DEV_CTL__NDN_ROUTE_ORDER_FIELD 0,0

#define MSS_COMMON_DEV_CTL__CDN_ROUTE_ORDER_SHIFT 1
#define MSS_COMMON_DEV_CTL__CDN_ROUTE_ORDER_WIDTH 1
#define MSS_COMMON_DEV_CTL__CDN_ROUTE_ORDER_RESET_VAL 1
#define MSS_COMMON_DEV_CTL__CDN_ROUTE_ORDER_RMASK 0x1
#define MSS_COMMON_DEV_CTL__CDN_ROUTE_ORDER_MASK  0x2
#define MSS_COMMON_DEV_CTL__CDN_ROUTE_ORDER_FIELD 1,1

#define MSS_COMMON_DEV_CTL__DDN_ROUTE_ORDER_SHIFT 2
#define MSS_COMMON_DEV_CTL__DDN_ROUTE_ORDER_WIDTH 1
#define MSS_COMMON_DEV_CTL__DDN_ROUTE_ORDER_RESET_VAL 1
#define MSS_COMMON_DEV_CTL__DDN_ROUTE_ORDER_RMASK 0x1
#define MSS_COMMON_DEV_CTL__DDN_ROUTE_ORDER_MASK  0x4
#define MSS_COMMON_DEV_CTL__DDN_ROUTE_ORDER_FIELD 2,2

#define MSS_COMMON_DEV_CTL__DMA_RD_CA_ENA_SHIFT 3
#define MSS_COMMON_DEV_CTL__DMA_RD_CA_ENA_WIDTH 1
#define MSS_COMMON_DEV_CTL__DMA_RD_CA_ENA_RESET_VAL 1
#define MSS_COMMON_DEV_CTL__DMA_RD_CA_ENA_RMASK 0x1
#define MSS_COMMON_DEV_CTL__DMA_RD_CA_ENA_MASK  0x8
#define MSS_COMMON_DEV_CTL__DMA_RD_CA_ENA_FIELD 3,3

#define MSS_COMMON_DEV_CTL__L3_PROFILE_OVD_SHIFT 4
#define MSS_COMMON_DEV_CTL__L3_PROFILE_OVD_WIDTH 1
#define MSS_COMMON_DEV_CTL__L3_PROFILE_OVD_RESET_VAL 0
#define MSS_COMMON_DEV_CTL__L3_PROFILE_OVD_RMASK 0x1
#define MSS_COMMON_DEV_CTL__L3_PROFILE_OVD_MASK  0x10
#define MSS_COMMON_DEV_CTL__L3_PROFILE_OVD_FIELD 4,4

#define MSS_COMMON_DEV_CTL__L3_PROFILE_VAL_SHIFT 5
#define MSS_COMMON_DEV_CTL__L3_PROFILE_VAL_WIDTH 4
#define MSS_COMMON_DEV_CTL__L3_PROFILE_VAL_RESET_VAL 0
#define MSS_COMMON_DEV_CTL__L3_PROFILE_VAL_RMASK 0xf
#define MSS_COMMON_DEV_CTL__L3_PROFILE_VAL_MASK  0x1e0
#define MSS_COMMON_DEV_CTL__L3_PROFILE_VAL_FIELD 5,8

#define MSS_COMMON_DEV_CTL__WR_SLVERR_MAP_SHIFT 9
#define MSS_COMMON_DEV_CTL__WR_SLVERR_MAP_WIDTH 2
#define MSS_COMMON_DEV_CTL__WR_SLVERR_MAP_RESET_VAL 2
#define MSS_COMMON_DEV_CTL__WR_SLVERR_MAP_RMASK 0x3
#define MSS_COMMON_DEV_CTL__WR_SLVERR_MAP_MASK  0x600
#define MSS_COMMON_DEV_CTL__WR_SLVERR_MAP_FIELD 9,10
#define MSS_COMMON_DEV_CTL__WR_SLVERR_MAP_VAL_OKAY 0x0
#define MSS_COMMON_DEV_CTL__WR_SLVERR_MAP_VAL_DATAERROR 0x2
#define MSS_COMMON_DEV_CTL__WR_SLVERR_MAP_VAL_NONDATAERROR 0x3

#define MSS_COMMON_DEV_CTL__WR_DECERR_MAP_SHIFT 11
#define MSS_COMMON_DEV_CTL__WR_DECERR_MAP_WIDTH 2
#define MSS_COMMON_DEV_CTL__WR_DECERR_MAP_RESET_VAL 3
#define MSS_COMMON_DEV_CTL__WR_DECERR_MAP_RMASK 0x3
#define MSS_COMMON_DEV_CTL__WR_DECERR_MAP_MASK  0x1800
#define MSS_COMMON_DEV_CTL__WR_DECERR_MAP_FIELD 11,12
#define MSS_COMMON_DEV_CTL__WR_DECERR_MAP_VAL_OKAY 0x0
#define MSS_COMMON_DEV_CTL__WR_DECERR_MAP_VAL_DATAERROR 0x2
#define MSS_COMMON_DEV_CTL__WR_DECERR_MAP_VAL_NONDATAERROR 0x3

#define MSS_COMMON_DEV_CTL__RD_SLVERR_MAP_SHIFT 13
#define MSS_COMMON_DEV_CTL__RD_SLVERR_MAP_WIDTH 2
#define MSS_COMMON_DEV_CTL__RD_SLVERR_MAP_RESET_VAL 2
#define MSS_COMMON_DEV_CTL__RD_SLVERR_MAP_RMASK 0x3
#define MSS_COMMON_DEV_CTL__RD_SLVERR_MAP_MASK  0x6000
#define MSS_COMMON_DEV_CTL__RD_SLVERR_MAP_FIELD 13,14
#define MSS_COMMON_DEV_CTL__RD_SLVERR_MAP_VAL_OKAY 0x0
#define MSS_COMMON_DEV_CTL__RD_SLVERR_MAP_VAL_DATAERROR 0x2
#define MSS_COMMON_DEV_CTL__RD_SLVERR_MAP_VAL_NONDATAERROR 0x3

#define MSS_COMMON_DEV_CTL__RD_DECERR_MAP_SHIFT 15
#define MSS_COMMON_DEV_CTL__RD_DECERR_MAP_WIDTH 2
#define MSS_COMMON_DEV_CTL__RD_DECERR_MAP_RESET_VAL 3
#define MSS_COMMON_DEV_CTL__RD_DECERR_MAP_RMASK 0x3
#define MSS_COMMON_DEV_CTL__RD_DECERR_MAP_MASK  0x18000
#define MSS_COMMON_DEV_CTL__RD_DECERR_MAP_FIELD 15,16
#define MSS_COMMON_DEV_CTL__RD_DECERR_MAP_VAL_OKAY 0x0
#define MSS_COMMON_DEV_CTL__RD_DECERR_MAP_VAL_DATAERROR 0x2
#define MSS_COMMON_DEV_CTL__RD_DECERR_MAP_VAL_NONDATAERROR 0x3

#define MSS_COMMON_DEV_CTL__CDN_REQ_BUF_ENA_SHIFT 17
#define MSS_COMMON_DEV_CTL__CDN_REQ_BUF_ENA_WIDTH 1
#define MSS_COMMON_DEV_CTL__CDN_REQ_BUF_ENA_RESET_VAL 1
#define MSS_COMMON_DEV_CTL__CDN_REQ_BUF_ENA_RMASK 0x1
#define MSS_COMMON_DEV_CTL__CDN_REQ_BUF_ENA_MASK  0x20000
#define MSS_COMMON_DEV_CTL__CDN_REQ_BUF_ENA_FIELD 17,17

#define MSS_COMMON_DEV_CTL__DMA_WRQ_HWM_SHIFT 20
#define MSS_COMMON_DEV_CTL__DMA_WRQ_HWM_WIDTH 8
#define MSS_COMMON_DEV_CTL__DMA_WRQ_HWM_RESET_VAL 255
#define MSS_COMMON_DEV_CTL__DMA_WRQ_HWM_RMASK 0xff
#define MSS_COMMON_DEV_CTL__DMA_WRQ_HWM_MASK  0xff00000
#define MSS_COMMON_DEV_CTL__DMA_WRQ_HWM_FIELD 20,27

#define MSS_COMMON_DEV_CTL__GTHR_DELAY_ADJ_SHIFT 28
#define MSS_COMMON_DEV_CTL__GTHR_DELAY_ADJ_WIDTH 4
#define MSS_COMMON_DEV_CTL__GTHR_DELAY_ADJ_RESET_VAL 0
#define MSS_COMMON_DEV_CTL__GTHR_DELAY_ADJ_RMASK 0xf
#define MSS_COMMON_DEV_CTL__GTHR_DELAY_ADJ_MASK  0xf0000000
#define MSS_COMMON_DEV_CTL__GTHR_DELAY_ADJ_FIELD 28,31


/*
 * Common Spare Register.
 * Common Spare Register. Mellanox tradition: leave one spare register as a
 * backup if there is something wrong of some registers
 */
#define MSS_COMMON_COMMON_SPARE 0x0010
#define MSS_COMMON_COMMON_SPARE__LENGTH 0x0001

#define MSS_COMMON_COMMON_SPARE__VAL_SHIFT 0
#define MSS_COMMON_COMMON_SPARE__VAL_WIDTH 64
#define MSS_COMMON_COMMON_SPARE__VAL_RESET_VAL 18446744073709551615
#define MSS_COMMON_COMMON_SPARE__VAL_RMASK _64bit(0xffffffffffffffff)
#define MSS_COMMON_COMMON_SPARE__VAL_MASK  _64bit(0xffffffffffffffff)
#define MSS_COMMON_COMMON_SPARE__VAL_FIELD 0,63


/* Scratchpad. */
#define MSS_COMMON_SCRATCHPAD 0x0020
#define MSS_COMMON_SCRATCHPAD__LENGTH 0x0001

#define MSS_COMMON_SCRATCHPAD__SCRATCHPAD_SHIFT 0
#define MSS_COMMON_SCRATCHPAD__SCRATCHPAD_WIDTH 64
#define MSS_COMMON_SCRATCHPAD__SCRATCHPAD_RESET_VAL 0
#define MSS_COMMON_SCRATCHPAD__SCRATCHPAD_RMASK _64bit(0xffffffffffffffff)
#define MSS_COMMON_SCRATCHPAD__SCRATCHPAD_MASK  _64bit(0xffffffffffffffff)
#define MSS_COMMON_SCRATCHPAD__SCRATCHPAD_FIELD 0,63


/*
 * Semaphore0.
 * Semaphore, this register is intentionally unused in the viper project
 */
#define MSS_COMMON_SEMAPHORE0 0x0028
#define MSS_COMMON_SEMAPHORE0__LENGTH 0x0001

#define MSS_COMMON_SEMAPHORE0__VAL_SHIFT 0
#define MSS_COMMON_SEMAPHORE0__VAL_WIDTH 1
#define MSS_COMMON_SEMAPHORE0__VAL_RESET_VAL 0
#define MSS_COMMON_SEMAPHORE0__VAL_RMASK 0x1
#define MSS_COMMON_SEMAPHORE0__VAL_MASK  0x1
#define MSS_COMMON_SEMAPHORE0__VAL_FIELD 0,0


/*
 * DMA Status.
 * DMA status information for debug. Unused for devices that do not have DMA.
 * This register does not exist in the PKA or Tile or MSS.
 */
#define MSS_COMMON_DMA_STATUS 0x0030
#define MSS_COMMON_DMA_STATUS__LENGTH 0x0001

#define MSS_COMMON_DMA_STATUS__RDQ_INFL_COUNT_SHIFT 0
#define MSS_COMMON_DMA_STATUS__RDQ_INFL_COUNT_WIDTH 9
#define MSS_COMMON_DMA_STATUS__RDQ_INFL_COUNT_RESET_VAL 0
#define MSS_COMMON_DMA_STATUS__RDQ_INFL_COUNT_RMASK 0x1ff
#define MSS_COMMON_DMA_STATUS__RDQ_INFL_COUNT_MASK  0x1ff
#define MSS_COMMON_DMA_STATUS__RDQ_INFL_COUNT_FIELD 0,8

#define MSS_COMMON_DMA_STATUS__WRQ_INFL_COUNT_SHIFT 9
#define MSS_COMMON_DMA_STATUS__WRQ_INFL_COUNT_WIDTH 9
#define MSS_COMMON_DMA_STATUS__WRQ_INFL_COUNT_RESET_VAL 0
#define MSS_COMMON_DMA_STATUS__WRQ_INFL_COUNT_RMASK 0x1ff
#define MSS_COMMON_DMA_STATUS__WRQ_INFL_COUNT_MASK  0x3fe00
#define MSS_COMMON_DMA_STATUS__WRQ_INFL_COUNT_FIELD 9,17

#define MSS_COMMON_DMA_STATUS__WRQ_DIAG_VEC_SHIFT 25
#define MSS_COMMON_DMA_STATUS__WRQ_DIAG_VEC_WIDTH 39
#define MSS_COMMON_DMA_STATUS__WRQ_DIAG_VEC_RESET_VAL 0
#define MSS_COMMON_DMA_STATUS__WRQ_DIAG_VEC_RMASK _64bit(0x7fffffffff)
#define MSS_COMMON_DMA_STATUS__WRQ_DIAG_VEC_MASK  _64bit(0xfffffffffe000000)
#define MSS_COMMON_DMA_STATUS__WRQ_DIAG_VEC_FIELD 25,63


/* Clock Count. */
#define MSS_COMMON_CLOCK_COUNT 0x0038
#define MSS_COMMON_CLOCK_COUNT__LENGTH 0x0001

#define MSS_COMMON_CLOCK_COUNT__RUN_SHIFT 0
#define MSS_COMMON_CLOCK_COUNT__RUN_WIDTH 1
#define MSS_COMMON_CLOCK_COUNT__RUN_RESET_VAL 0
#define MSS_COMMON_CLOCK_COUNT__RUN_RMASK 0x1
#define MSS_COMMON_CLOCK_COUNT__RUN_MASK  0x1
#define MSS_COMMON_CLOCK_COUNT__RUN_FIELD 0,0

#define MSS_COMMON_CLOCK_COUNT__COUNT_SHIFT 1
#define MSS_COMMON_CLOCK_COUNT__COUNT_WIDTH 15
#define MSS_COMMON_CLOCK_COUNT__COUNT_RMASK 0x7fff
#define MSS_COMMON_CLOCK_COUNT__COUNT_MASK  0xfffe
#define MSS_COMMON_CLOCK_COUNT__COUNT_FIELD 1,15


/*
 * Interrupt Setup.
 * Configuration for device interrupts.
 */
#define MSS_COMMON_INT_SETUP 0x0040
#define MSS_COMMON_INT_SETUP__LENGTH 0x0001

#define MSS_COMMON_INT_SETUP__GBL_ENA_SHIFT 0
#define MSS_COMMON_INT_SETUP__GBL_ENA_WIDTH 1
#define MSS_COMMON_INT_SETUP__GBL_ENA_RESET_VAL 0
#define MSS_COMMON_INT_SETUP__GBL_ENA_RMASK 0x1
#define MSS_COMMON_INT_SETUP__GBL_ENA_MASK  0x1
#define MSS_COMMON_INT_SETUP__GBL_ENA_FIELD 0,0

#define MSS_COMMON_INT_SETUP__BASE_INT_NUM_SHIFT 48
#define MSS_COMMON_INT_SETUP__BASE_INT_NUM_WIDTH 16
#define MSS_COMMON_INT_SETUP__BASE_INT_NUM_RMASK 0xffff
#define MSS_COMMON_INT_SETUP__BASE_INT_NUM_MASK  _64bit(0xffff000000000000)
#define MSS_COMMON_INT_SETUP__BASE_INT_NUM_FIELD 48,63


/*
 * Credit Control.
 * Provides access to the request-credit counters that control end-to-end
 * flow control between the device and other nodes in the system.
 */
#define MSS_COMMON_CRED_CTL 0x0050
#define MSS_COMMON_CRED_CTL__LENGTH 0x0001

#define MSS_COMMON_CRED_CTL__UPDATE_SHIFT 0
#define MSS_COMMON_CRED_CTL__UPDATE_WIDTH 1
#define MSS_COMMON_CRED_CTL__UPDATE_RESET_VAL 0
#define MSS_COMMON_CRED_CTL__UPDATE_RMASK 0x1
#define MSS_COMMON_CRED_CTL__UPDATE_MASK  0x1
#define MSS_COMMON_CRED_CTL__UPDATE_FIELD 0,0

#define MSS_COMMON_CRED_CTL__NODEID_SEL_SHIFT 1
#define MSS_COMMON_CRED_CTL__NODEID_SEL_WIDTH 11
#define MSS_COMMON_CRED_CTL__NODEID_SEL_RESET_VAL 0
#define MSS_COMMON_CRED_CTL__NODEID_SEL_RMASK 0x7ff
#define MSS_COMMON_CRED_CTL__NODEID_SEL_MASK  0xffe
#define MSS_COMMON_CRED_CTL__NODEID_SEL_FIELD 1,11

#define MSS_COMMON_CRED_CTL__TGT_SEL_SHIFT 12
#define MSS_COMMON_CRED_CTL__TGT_SEL_WIDTH 2
#define MSS_COMMON_CRED_CTL__TGT_SEL_RESET_VAL 0
#define MSS_COMMON_CRED_CTL__TGT_SEL_RMASK 0x3
#define MSS_COMMON_CRED_CTL__TGT_SEL_MASK  0x3000
#define MSS_COMMON_CRED_CTL__TGT_SEL_FIELD 12,13
#define MSS_COMMON_CRED_CTL__TGT_SEL_VAL_TX_REQ 0x0
#define MSS_COMMON_CRED_CTL__TGT_SEL_VAL_RETRYQ 0x1
#define MSS_COMMON_CRED_CTL__TGT_SEL_VAL_RING 0x2

#define MSS_COMMON_CRED_CTL__CLIENT_SEL_SHIFT 14
#define MSS_COMMON_CRED_CTL__CLIENT_SEL_WIDTH 2
#define MSS_COMMON_CRED_CTL__CLIENT_SEL_RESET_VAL 0
#define MSS_COMMON_CRED_CTL__CLIENT_SEL_RMASK 0x3
#define MSS_COMMON_CRED_CTL__CLIENT_SEL_MASK  0xc000
#define MSS_COMMON_CRED_CTL__CLIENT_SEL_FIELD 14,15

#define MSS_COMMON_CRED_CTL__VAL_SHIFT 16
#define MSS_COMMON_CRED_CTL__VAL_WIDTH 16
#define MSS_COMMON_CRED_CTL__VAL_RESET_VAL 0
#define MSS_COMMON_CRED_CTL__VAL_RMASK 0xffff
#define MSS_COMMON_CRED_CTL__VAL_MASK  0xffff0000
#define MSS_COMMON_CRED_CTL__VAL_FIELD 16,31


/*
 * SAM Control.
 * Provides access to SAM initialization.
 */
#define MSS_COMMON_SAM_CTL 0x0058
#define MSS_COMMON_SAM_CTL__LENGTH 0x0001

#define MSS_COMMON_SAM_CTL__UPDATE_SHIFT 0
#define MSS_COMMON_SAM_CTL__UPDATE_WIDTH 1
#define MSS_COMMON_SAM_CTL__UPDATE_RESET_VAL 0
#define MSS_COMMON_SAM_CTL__UPDATE_RMASK 0x1
#define MSS_COMMON_SAM_CTL__UPDATE_MASK  0x1
#define MSS_COMMON_SAM_CTL__UPDATE_FIELD 0,0

#define MSS_COMMON_SAM_CTL__IDX_SHIFT 1
#define MSS_COMMON_SAM_CTL__IDX_WIDTH 12
#define MSS_COMMON_SAM_CTL__IDX_RESET_VAL 0
#define MSS_COMMON_SAM_CTL__IDX_RMASK 0xfff
#define MSS_COMMON_SAM_CTL__IDX_MASK  0x1ffe
#define MSS_COMMON_SAM_CTL__IDX_FIELD 1,12
#define MSS_COMMON_SAM_CTL__IDX_VAL_HNF_SIZE 0x7f7
#define MSS_COMMON_SAM_CTL__IDX_VAL_LDR_SIZE 0x20

#define MSS_COMMON_SAM_CTL__TBL_SEL_SHIFT 13
#define MSS_COMMON_SAM_CTL__TBL_SEL_WIDTH 3
#define MSS_COMMON_SAM_CTL__TBL_SEL_RESET_VAL 0
#define MSS_COMMON_SAM_CTL__TBL_SEL_RMASK 0x7
#define MSS_COMMON_SAM_CTL__TBL_SEL_MASK  0xe000
#define MSS_COMMON_SAM_CTL__TBL_SEL_FIELD 13,15
#define MSS_COMMON_SAM_CTL__TBL_SEL_VAL_LDR 0x0
#define MSS_COMMON_SAM_CTL__TBL_SEL_VAL_HNF 0x1
#define MSS_COMMON_SAM_CTL__TBL_SEL_VAL_PCI_NPF 0x2
#define MSS_COMMON_SAM_CTL__TBL_SEL_VAL_PCI_PF 0x3
#define MSS_COMMON_SAM_CTL__TBL_SEL_VAL_PCI_CFG 0x4

#define MSS_COMMON_SAM_CTL__CLIENT_SEL_SHIFT 16
#define MSS_COMMON_SAM_CTL__CLIENT_SEL_WIDTH 1
#define MSS_COMMON_SAM_CTL__CLIENT_SEL_RESET_VAL 0
#define MSS_COMMON_SAM_CTL__CLIENT_SEL_RMASK 0x1
#define MSS_COMMON_SAM_CTL__CLIENT_SEL_MASK  0x10000
#define MSS_COMMON_SAM_CTL__CLIENT_SEL_FIELD 16,16

#define MSS_COMMON_SAM_CTL__READ_SHIFT 17
#define MSS_COMMON_SAM_CTL__READ_WIDTH 1
#define MSS_COMMON_SAM_CTL__READ_RESET_VAL 0
#define MSS_COMMON_SAM_CTL__READ_RMASK 0x1
#define MSS_COMMON_SAM_CTL__READ_MASK  0x20000
#define MSS_COMMON_SAM_CTL__READ_FIELD 17,17

#define MSS_COMMON_SAM_CTL__VAL_SHIFT 18
#define MSS_COMMON_SAM_CTL__VAL_WIDTH 34
#define MSS_COMMON_SAM_CTL__VAL_RESET_VAL 0
#define MSS_COMMON_SAM_CTL__VAL_RMASK _64bit(0x3ffffffff)
#define MSS_COMMON_SAM_CTL__VAL_MASK  _64bit(0xffffffffc0000)
#define MSS_COMMON_SAM_CTL__VAL_FIELD 18,51


/*
 * Device Security Level.
 * Allows Secure and/or NonSecure accesses. When not allowed reads will
 * return a value of 0 and writes
 *   will be dropped. Accesses to this register are not controlled by these
 * bits; only Secure accesses are allowed.
 *
 * The NUM_SEC_DOMAIN PUBLIC on a unit's sm_dev instantiation describes the
 * number of address spaces within the unit that are separately protected.
 * Each domain has a corresponding set of ALLOW_S/ALLOW_NS bits.
 * The most common case is for the entire address space of the unit to be
 * treated the same. In this case NUM_SEC_DOMAIN is set to 1, Domain0's
 * ALLOW_S/ALLOW_NS bits are valid, and all other Domains' ALLOW_S/ALLOW_NS
 * are reserved/unused by hardware.
 * If NUM_SEC_DOMAIN is set to 2, Domain0 and Domain1 are valid and
 * Domains2-5 are reserved/unused by hardware.
 */
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL 0x0018
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__LENGTH 0x0001

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN0_SHIFT 0
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN0_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN0_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN0_MASK  0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN0_FIELD 0,0

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN0_SHIFT 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN0_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN0_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN0_MASK  0x2
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN0_FIELD 1,1

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN1_SHIFT 2
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN1_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN1_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN1_MASK  0x4
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN1_FIELD 2,2

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN1_SHIFT 3
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN1_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN1_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN1_MASK  0x8
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN1_FIELD 3,3

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN2_SHIFT 4
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN2_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN2_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN2_MASK  0x10
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN2_FIELD 4,4

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN2_SHIFT 5
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN2_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN2_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN2_MASK  0x20
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN2_FIELD 5,5

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN3_SHIFT 6
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN3_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN3_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN3_MASK  0x40
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN3_FIELD 6,6

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN3_SHIFT 7
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN3_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN3_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN3_MASK  0x80
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN3_FIELD 7,7

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN4_SHIFT 8
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN4_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN4_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN4_MASK  0x100
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN4_FIELD 8,8

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN4_SHIFT 9
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN4_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN4_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN4_MASK  0x200
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN4_FIELD 9,9

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN5_SHIFT 10
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN5_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN5_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN5_MASK  0x400
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_S_DOMAIN5_FIELD 10,10

#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN5_SHIFT 11
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN5_WIDTH 1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN5_RMASK 0x1
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN5_MASK  0x800
#define MSS_COMMON_COMMON_DEVICE_SECURITY_LEVEL__ALLOW_NS_DOMAIN5_FIELD 11,11


/*
 * DMA Read Pacer.
 * Control the behavior of dma read pacer
 */
#define MSS_COMMON_DMA_READ_PACE 0x0060
#define MSS_COMMON_DMA_READ_PACE__LENGTH 0x0001

#define MSS_COMMON_DMA_READ_PACE__EN_SHIFT 0
#define MSS_COMMON_DMA_READ_PACE__EN_WIDTH 1
#define MSS_COMMON_DMA_READ_PACE__EN_RESET_VAL 0
#define MSS_COMMON_DMA_READ_PACE__EN_RMASK 0x1
#define MSS_COMMON_DMA_READ_PACE__EN_MASK  0x1
#define MSS_COMMON_DMA_READ_PACE__EN_FIELD 0,0

#define MSS_COMMON_DMA_READ_PACE__PER_READ_PENALTY_SHIFT 1
#define MSS_COMMON_DMA_READ_PACE__PER_READ_PENALTY_WIDTH 3
#define MSS_COMMON_DMA_READ_PACE__PER_READ_PENALTY_RESET_VAL 0
#define MSS_COMMON_DMA_READ_PACE__PER_READ_PENALTY_RMASK 0x7
#define MSS_COMMON_DMA_READ_PACE__PER_READ_PENALTY_MASK  0xe
#define MSS_COMMON_DMA_READ_PACE__PER_READ_PENALTY_FIELD 1,3

#define MSS_COMMON_DMA_READ_PACE__MAX_COUNT_SHIFT 4
#define MSS_COMMON_DMA_READ_PACE__MAX_COUNT_WIDTH 9
#define MSS_COMMON_DMA_READ_PACE__MAX_COUNT_RESET_VAL 32
#define MSS_COMMON_DMA_READ_PACE__MAX_COUNT_RMASK 0x1ff
#define MSS_COMMON_DMA_READ_PACE__MAX_COUNT_MASK  0x1ff0
#define MSS_COMMON_DMA_READ_PACE__MAX_COUNT_FIELD 4,12

#define MSS_COMMON_DMA_READ_PACE__PENALTY_FRACTION_SHIFT 13
#define MSS_COMMON_DMA_READ_PACE__PENALTY_FRACTION_WIDTH 8
#define MSS_COMMON_DMA_READ_PACE__PENALTY_FRACTION_RESET_VAL 0
#define MSS_COMMON_DMA_READ_PACE__PENALTY_FRACTION_RMASK 0xff
#define MSS_COMMON_DMA_READ_PACE__PENALTY_FRACTION_MASK  0x1fe000
#define MSS_COMMON_DMA_READ_PACE__PENALTY_FRACTION_FIELD 13,20


/*
 * DMA Write Latency.
 * Provides random sample and record of DMA AXI4 write latency
 */
#define MSS_COMMON_DMA_WR_LAT 0x0070
#define MSS_COMMON_DMA_WR_LAT__LENGTH 0x0001

#define MSS_COMMON_DMA_WR_LAT__MIN_LAT_SHIFT 0
#define MSS_COMMON_DMA_WR_LAT__MIN_LAT_WIDTH 15
#define MSS_COMMON_DMA_WR_LAT__MIN_LAT_RESET_VAL 0
#define MSS_COMMON_DMA_WR_LAT__MIN_LAT_RMASK 0x7fff
#define MSS_COMMON_DMA_WR_LAT__MIN_LAT_MASK  0x7fff
#define MSS_COMMON_DMA_WR_LAT__MIN_LAT_FIELD 0,14

#define MSS_COMMON_DMA_WR_LAT__MAX_LAT_SHIFT 16
#define MSS_COMMON_DMA_WR_LAT__MAX_LAT_WIDTH 15
#define MSS_COMMON_DMA_WR_LAT__MAX_LAT_RESET_VAL 0
#define MSS_COMMON_DMA_WR_LAT__MAX_LAT_RMASK 0x7fff
#define MSS_COMMON_DMA_WR_LAT__MAX_LAT_MASK  0x7fff0000
#define MSS_COMMON_DMA_WR_LAT__MAX_LAT_FIELD 16,30

#define MSS_COMMON_DMA_WR_LAT__CURR_LAT_SHIFT 32
#define MSS_COMMON_DMA_WR_LAT__CURR_LAT_WIDTH 15
#define MSS_COMMON_DMA_WR_LAT__CURR_LAT_RESET_VAL 0
#define MSS_COMMON_DMA_WR_LAT__CURR_LAT_RMASK 0x7fff
#define MSS_COMMON_DMA_WR_LAT__CURR_LAT_MASK  _64bit(0x7fff00000000)
#define MSS_COMMON_DMA_WR_LAT__CURR_LAT_FIELD 32,46

#define MSS_COMMON_DMA_WR_LAT__CLEAR_SHIFT 48
#define MSS_COMMON_DMA_WR_LAT__CLEAR_WIDTH 1
#define MSS_COMMON_DMA_WR_LAT__CLEAR_RESET_VAL 0
#define MSS_COMMON_DMA_WR_LAT__CLEAR_RMASK 0x1
#define MSS_COMMON_DMA_WR_LAT__CLEAR_MASK  _64bit(0x1000000000000)
#define MSS_COMMON_DMA_WR_LAT__CLEAR_FIELD 48,48

#define MSS_COMMON_DMA_WR_LAT__MAX_STND_REQS_SHIFT 49
#define MSS_COMMON_DMA_WR_LAT__MAX_STND_REQS_WIDTH 12
#define MSS_COMMON_DMA_WR_LAT__MAX_STND_REQS_RESET_VAL 0
#define MSS_COMMON_DMA_WR_LAT__MAX_STND_REQS_RMASK 0xfff
#define MSS_COMMON_DMA_WR_LAT__MAX_STND_REQS_MASK  _64bit(0x1ffe000000000000)
#define MSS_COMMON_DMA_WR_LAT__MAX_STND_REQS_FIELD 49,60


/*
 * DMA Read Latency.
 * Provides random sample and record of DMA AXI4 read latency
 */
#define MSS_COMMON_DMA_RD_LAT 0x0078
#define MSS_COMMON_DMA_RD_LAT__LENGTH 0x0001

#define MSS_COMMON_DMA_RD_LAT__MIN_LAT_SHIFT 0
#define MSS_COMMON_DMA_RD_LAT__MIN_LAT_WIDTH 15
#define MSS_COMMON_DMA_RD_LAT__MIN_LAT_RESET_VAL 0
#define MSS_COMMON_DMA_RD_LAT__MIN_LAT_RMASK 0x7fff
#define MSS_COMMON_DMA_RD_LAT__MIN_LAT_MASK  0x7fff
#define MSS_COMMON_DMA_RD_LAT__MIN_LAT_FIELD 0,14

#define MSS_COMMON_DMA_RD_LAT__MAX_LAT_SHIFT 16
#define MSS_COMMON_DMA_RD_LAT__MAX_LAT_WIDTH 15
#define MSS_COMMON_DMA_RD_LAT__MAX_LAT_RESET_VAL 0
#define MSS_COMMON_DMA_RD_LAT__MAX_LAT_RMASK 0x7fff
#define MSS_COMMON_DMA_RD_LAT__MAX_LAT_MASK  0x7fff0000
#define MSS_COMMON_DMA_RD_LAT__MAX_LAT_FIELD 16,30

#define MSS_COMMON_DMA_RD_LAT__CURR_LAT_SHIFT 32
#define MSS_COMMON_DMA_RD_LAT__CURR_LAT_WIDTH 15
#define MSS_COMMON_DMA_RD_LAT__CURR_LAT_RESET_VAL 0
#define MSS_COMMON_DMA_RD_LAT__CURR_LAT_RMASK 0x7fff
#define MSS_COMMON_DMA_RD_LAT__CURR_LAT_MASK  _64bit(0x7fff00000000)
#define MSS_COMMON_DMA_RD_LAT__CURR_LAT_FIELD 32,46

#define MSS_COMMON_DMA_RD_LAT__CLEAR_SHIFT 48
#define MSS_COMMON_DMA_RD_LAT__CLEAR_WIDTH 1
#define MSS_COMMON_DMA_RD_LAT__CLEAR_RESET_VAL 0
#define MSS_COMMON_DMA_RD_LAT__CLEAR_RMASK 0x1
#define MSS_COMMON_DMA_RD_LAT__CLEAR_MASK  _64bit(0x1000000000000)
#define MSS_COMMON_DMA_RD_LAT__CLEAR_FIELD 48,48

#define MSS_COMMON_DMA_RD_LAT__MAX_STND_REQS_SHIFT 49
#define MSS_COMMON_DMA_RD_LAT__MAX_STND_REQS_WIDTH 12
#define MSS_COMMON_DMA_RD_LAT__MAX_STND_REQS_RESET_VAL 0
#define MSS_COMMON_DMA_RD_LAT__MAX_STND_REQS_RMASK 0xfff
#define MSS_COMMON_DMA_RD_LAT__MAX_STND_REQS_MASK  _64bit(0x1ffe000000000000)
#define MSS_COMMON_DMA_RD_LAT__MAX_STND_REQS_FIELD 49,60


/*
 * Bandwidth_Control.
 * Limit the bandwidth between the node and the mesh. There are four
 * bandwidth control registers, which respectively control WRITE-CDN,
 * WRITE-DDN, READ-CDN and READ-DDN channel
 */
#define MSS_COMMON_BND_CTL__FIRST_WORD 0x0080
#define MSS_COMMON_BND_CTL__LAST_WORD 0x0098
#define MSS_COMMON_BND_CTL__LENGTH 0x0020
#define MSS_COMMON_BND_CTL__STRIDE 0x0008

#define MSS_COMMON_BND_CTL__EN_SHIFT 0
#define MSS_COMMON_BND_CTL__EN_WIDTH 1
#define MSS_COMMON_BND_CTL__EN_RESET_VAL 0
#define MSS_COMMON_BND_CTL__EN_RMASK 0x1
#define MSS_COMMON_BND_CTL__EN_MASK  0x1
#define MSS_COMMON_BND_CTL__EN_FIELD 0,0

#define MSS_COMMON_BND_CTL__MAX_COUNT_SHIFT 1
#define MSS_COMMON_BND_CTL__MAX_COUNT_WIDTH 9
#define MSS_COMMON_BND_CTL__MAX_COUNT_RESET_VAL 32
#define MSS_COMMON_BND_CTL__MAX_COUNT_RMASK 0x1ff
#define MSS_COMMON_BND_CTL__MAX_COUNT_MASK  0x3fe
#define MSS_COMMON_BND_CTL__MAX_COUNT_FIELD 1,9

#define MSS_COMMON_BND_CTL__TOKEN_NUM_SHIFT 20
#define MSS_COMMON_BND_CTL__TOKEN_NUM_WIDTH 10
#define MSS_COMMON_BND_CTL__TOKEN_NUM_RESET_VAL 1023
#define MSS_COMMON_BND_CTL__TOKEN_NUM_RMASK 0x3ff
#define MSS_COMMON_BND_CTL__TOKEN_NUM_MASK  0x3ff00000
#define MSS_COMMON_BND_CTL__TOKEN_NUM_FIELD 20,29

#define MSS_COMMON_BND_CTL__PENALTY_NUM_SHIFT 30
#define MSS_COMMON_BND_CTL__PENALTY_NUM_WIDTH 3
#define MSS_COMMON_BND_CTL__PENALTY_NUM_RESET_VAL 0
#define MSS_COMMON_BND_CTL__PENALTY_NUM_RMASK 0x7
#define MSS_COMMON_BND_CTL__PENALTY_NUM_MASK  _64bit(0x1c0000000)
#define MSS_COMMON_BND_CTL__PENALTY_NUM_FIELD 30,32

#define MSS_COMMON_BND_CTL__PENALTY_FRACTION_SHIFT 33
#define MSS_COMMON_BND_CTL__PENALTY_FRACTION_WIDTH 8
#define MSS_COMMON_BND_CTL__PENALTY_FRACTION_RESET_VAL 0
#define MSS_COMMON_BND_CTL__PENALTY_FRACTION_RMASK 0xff
#define MSS_COMMON_BND_CTL__PENALTY_FRACTION_MASK  _64bit(0x1fe00000000)
#define MSS_COMMON_BND_CTL__PENALTY_FRACTION_FIELD 33,40


/*
 * Bandwidth_Control.
 * Limit the bandwidth between the node and the mesh. There are four
 * bandwidth control registers, which respectively control WRITE-CDN,
 * WRITE-DDN, READ-CDN and READ-DDN channel
 */
#define MSS_COMMON_BND_CTL_1__FIRST_WORD 0x0088
#define MSS_COMMON_BND_CTL_1__LAST_WORD 0x00a0
#define MSS_COMMON_BND_CTL_1__LENGTH 0x0020
#define MSS_COMMON_BND_CTL_1__STRIDE 0x0008

#define MSS_COMMON_BND_CTL_1__EN_SHIFT 0
#define MSS_COMMON_BND_CTL_1__EN_WIDTH 1
#define MSS_COMMON_BND_CTL_1__EN_RESET_VAL 0
#define MSS_COMMON_BND_CTL_1__EN_RMASK 0x1
#define MSS_COMMON_BND_CTL_1__EN_MASK  0x1
#define MSS_COMMON_BND_CTL_1__EN_FIELD 0,0

#define MSS_COMMON_BND_CTL_1__MAX_COUNT_SHIFT 1
#define MSS_COMMON_BND_CTL_1__MAX_COUNT_WIDTH 9
#define MSS_COMMON_BND_CTL_1__MAX_COUNT_RESET_VAL 32
#define MSS_COMMON_BND_CTL_1__MAX_COUNT_RMASK 0x1ff
#define MSS_COMMON_BND_CTL_1__MAX_COUNT_MASK  0x3fe
#define MSS_COMMON_BND_CTL_1__MAX_COUNT_FIELD 1,9

#define MSS_COMMON_BND_CTL_1__TOKEN_NUM_SHIFT 20
#define MSS_COMMON_BND_CTL_1__TOKEN_NUM_WIDTH 10
#define MSS_COMMON_BND_CTL_1__TOKEN_NUM_RESET_VAL 1023
#define MSS_COMMON_BND_CTL_1__TOKEN_NUM_RMASK 0x3ff
#define MSS_COMMON_BND_CTL_1__TOKEN_NUM_MASK  0x3ff00000
#define MSS_COMMON_BND_CTL_1__TOKEN_NUM_FIELD 20,29

#define MSS_COMMON_BND_CTL_1__PENALTY_NUM_SHIFT 30
#define MSS_COMMON_BND_CTL_1__PENALTY_NUM_WIDTH 3
#define MSS_COMMON_BND_CTL_1__PENALTY_NUM_RESET_VAL 0
#define MSS_COMMON_BND_CTL_1__PENALTY_NUM_RMASK 0x7
#define MSS_COMMON_BND_CTL_1__PENALTY_NUM_MASK  _64bit(0x1c0000000)
#define MSS_COMMON_BND_CTL_1__PENALTY_NUM_FIELD 30,32

#define MSS_COMMON_BND_CTL_1__PENALTY_FRACTION_SHIFT 33
#define MSS_COMMON_BND_CTL_1__PENALTY_FRACTION_WIDTH 8
#define MSS_COMMON_BND_CTL_1__PENALTY_FRACTION_RESET_VAL 0
#define MSS_COMMON_BND_CTL_1__PENALTY_FRACTION_RMASK 0xff
#define MSS_COMMON_BND_CTL_1__PENALTY_FRACTION_MASK  _64bit(0x1fe00000000)
#define MSS_COMMON_BND_CTL_1__PENALTY_FRACTION_FIELD 33,40


/*
 * Bandwidth_Control.
 * Limit the bandwidth between the node and the mesh. There are four
 * bandwidth control registers, which respectively control WRITE-CDN,
 * WRITE-DDN, READ-CDN and READ-DDN channel
 */
#define MSS_COMMON_BND_CTL_2__FIRST_WORD 0x0090
#define MSS_COMMON_BND_CTL_2__LAST_WORD 0x00a8
#define MSS_COMMON_BND_CTL_2__LENGTH 0x0020
#define MSS_COMMON_BND_CTL_2__STRIDE 0x0008

#define MSS_COMMON_BND_CTL_2__EN_SHIFT 0
#define MSS_COMMON_BND_CTL_2__EN_WIDTH 1
#define MSS_COMMON_BND_CTL_2__EN_RESET_VAL 0
#define MSS_COMMON_BND_CTL_2__EN_RMASK 0x1
#define MSS_COMMON_BND_CTL_2__EN_MASK  0x1
#define MSS_COMMON_BND_CTL_2__EN_FIELD 0,0

#define MSS_COMMON_BND_CTL_2__MAX_COUNT_SHIFT 1
#define MSS_COMMON_BND_CTL_2__MAX_COUNT_WIDTH 9
#define MSS_COMMON_BND_CTL_2__MAX_COUNT_RESET_VAL 32
#define MSS_COMMON_BND_CTL_2__MAX_COUNT_RMASK 0x1ff
#define MSS_COMMON_BND_CTL_2__MAX_COUNT_MASK  0x3fe
#define MSS_COMMON_BND_CTL_2__MAX_COUNT_FIELD 1,9

#define MSS_COMMON_BND_CTL_2__TOKEN_NUM_SHIFT 20
#define MSS_COMMON_BND_CTL_2__TOKEN_NUM_WIDTH 10
#define MSS_COMMON_BND_CTL_2__TOKEN_NUM_RESET_VAL 1023
#define MSS_COMMON_BND_CTL_2__TOKEN_NUM_RMASK 0x3ff
#define MSS_COMMON_BND_CTL_2__TOKEN_NUM_MASK  0x3ff00000
#define MSS_COMMON_BND_CTL_2__TOKEN_NUM_FIELD 20,29

#define MSS_COMMON_BND_CTL_2__PENALTY_NUM_SHIFT 30
#define MSS_COMMON_BND_CTL_2__PENALTY_NUM_WIDTH 3
#define MSS_COMMON_BND_CTL_2__PENALTY_NUM_RESET_VAL 0
#define MSS_COMMON_BND_CTL_2__PENALTY_NUM_RMASK 0x7
#define MSS_COMMON_BND_CTL_2__PENALTY_NUM_MASK  _64bit(0x1c0000000)
#define MSS_COMMON_BND_CTL_2__PENALTY_NUM_FIELD 30,32

#define MSS_COMMON_BND_CTL_2__PENALTY_FRACTION_SHIFT 33
#define MSS_COMMON_BND_CTL_2__PENALTY_FRACTION_WIDTH 8
#define MSS_COMMON_BND_CTL_2__PENALTY_FRACTION_RESET_VAL 0
#define MSS_COMMON_BND_CTL_2__PENALTY_FRACTION_RMASK 0xff
#define MSS_COMMON_BND_CTL_2__PENALTY_FRACTION_MASK  _64bit(0x1fe00000000)
#define MSS_COMMON_BND_CTL_2__PENALTY_FRACTION_FIELD 33,40


/*
 * Bandwidth_Control.
 * Limit the bandwidth between the node and the mesh. There are four
 * bandwidth control registers, which respectively control WRITE-CDN,
 * WRITE-DDN, READ-CDN and READ-DDN channel
 */
#define MSS_COMMON_BND_CTL_3__FIRST_WORD 0x0098
#define MSS_COMMON_BND_CTL_3__LAST_WORD 0x00b0
#define MSS_COMMON_BND_CTL_3__LENGTH 0x0020
#define MSS_COMMON_BND_CTL_3__STRIDE 0x0008

#define MSS_COMMON_BND_CTL_3__EN_SHIFT 0
#define MSS_COMMON_BND_CTL_3__EN_WIDTH 1
#define MSS_COMMON_BND_CTL_3__EN_RESET_VAL 0
#define MSS_COMMON_BND_CTL_3__EN_RMASK 0x1
#define MSS_COMMON_BND_CTL_3__EN_MASK  0x1
#define MSS_COMMON_BND_CTL_3__EN_FIELD 0,0

#define MSS_COMMON_BND_CTL_3__MAX_COUNT_SHIFT 1
#define MSS_COMMON_BND_CTL_3__MAX_COUNT_WIDTH 9
#define MSS_COMMON_BND_CTL_3__MAX_COUNT_RESET_VAL 32
#define MSS_COMMON_BND_CTL_3__MAX_COUNT_RMASK 0x1ff
#define MSS_COMMON_BND_CTL_3__MAX_COUNT_MASK  0x3fe
#define MSS_COMMON_BND_CTL_3__MAX_COUNT_FIELD 1,9

#define MSS_COMMON_BND_CTL_3__TOKEN_NUM_SHIFT 20
#define MSS_COMMON_BND_CTL_3__TOKEN_NUM_WIDTH 10
#define MSS_COMMON_BND_CTL_3__TOKEN_NUM_RESET_VAL 1023
#define MSS_COMMON_BND_CTL_3__TOKEN_NUM_RMASK 0x3ff
#define MSS_COMMON_BND_CTL_3__TOKEN_NUM_MASK  0x3ff00000
#define MSS_COMMON_BND_CTL_3__TOKEN_NUM_FIELD 20,29

#define MSS_COMMON_BND_CTL_3__PENALTY_NUM_SHIFT 30
#define MSS_COMMON_BND_CTL_3__PENALTY_NUM_WIDTH 3
#define MSS_COMMON_BND_CTL_3__PENALTY_NUM_RESET_VAL 0
#define MSS_COMMON_BND_CTL_3__PENALTY_NUM_RMASK 0x7
#define MSS_COMMON_BND_CTL_3__PENALTY_NUM_MASK  _64bit(0x1c0000000)
#define MSS_COMMON_BND_CTL_3__PENALTY_NUM_FIELD 30,32

#define MSS_COMMON_BND_CTL_3__PENALTY_FRACTION_SHIFT 33
#define MSS_COMMON_BND_CTL_3__PENALTY_FRACTION_WIDTH 8
#define MSS_COMMON_BND_CTL_3__PENALTY_FRACTION_RESET_VAL 0
#define MSS_COMMON_BND_CTL_3__PENALTY_FRACTION_RMASK 0xff
#define MSS_COMMON_BND_CTL_3__PENALTY_FRACTION_MASK  _64bit(0x1fe00000000)
#define MSS_COMMON_BND_CTL_3__PENALTY_FRACTION_FIELD 33,40


/*
 * BandWidth Throttle Control.
 * Control Bandwidth throttle algorithm behavior.There are four bandwidth
 * throttle control registers, which respectively control WRITE-CDN,
 * WRITE-DDN, READ-CDN and READ-DDN channel
 */
#define MSS_COMMON_BND_THRT_CTL__FIRST_WORD 0x00a0
#define MSS_COMMON_BND_THRT_CTL__LAST_WORD 0x00b8
#define MSS_COMMON_BND_THRT_CTL__LENGTH 0x0020
#define MSS_COMMON_BND_THRT_CTL__STRIDE 0x0008

#define MSS_COMMON_BND_THRT_CTL__EN_SHIFT 0
#define MSS_COMMON_BND_THRT_CTL__EN_WIDTH 1
#define MSS_COMMON_BND_THRT_CTL__EN_RESET_VAL 0
#define MSS_COMMON_BND_THRT_CTL__EN_RMASK 0x1
#define MSS_COMMON_BND_THRT_CTL__EN_MASK  0x1
#define MSS_COMMON_BND_THRT_CTL__EN_FIELD 0,0

#define MSS_COMMON_BND_THRT_CTL__CONG_THRES_SHIFT 1
#define MSS_COMMON_BND_THRT_CTL__CONG_THRES_WIDTH 15
#define MSS_COMMON_BND_THRT_CTL__CONG_THRES_RESET_VAL 256
#define MSS_COMMON_BND_THRT_CTL__CONG_THRES_RMASK 0x7fff
#define MSS_COMMON_BND_THRT_CTL__CONG_THRES_MASK  0xfffe
#define MSS_COMMON_BND_THRT_CTL__CONG_THRES_FIELD 1,15

#define MSS_COMMON_BND_THRT_CTL__MAX_SHIFT 16
#define MSS_COMMON_BND_THRT_CTL__MAX_WIDTH 10
#define MSS_COMMON_BND_THRT_CTL__MAX_RESET_VAL 1023
#define MSS_COMMON_BND_THRT_CTL__MAX_RMASK 0x3ff
#define MSS_COMMON_BND_THRT_CTL__MAX_MASK  0x3ff0000
#define MSS_COMMON_BND_THRT_CTL__MAX_FIELD 16,25

#define MSS_COMMON_BND_THRT_CTL__MIN_SHIFT 26
#define MSS_COMMON_BND_THRT_CTL__MIN_WIDTH 10
#define MSS_COMMON_BND_THRT_CTL__MIN_RESET_VAL 1
#define MSS_COMMON_BND_THRT_CTL__MIN_RMASK 0x3ff
#define MSS_COMMON_BND_THRT_CTL__MIN_MASK  _64bit(0xffc000000)
#define MSS_COMMON_BND_THRT_CTL__MIN_FIELD 26,35

#define MSS_COMMON_BND_THRT_CTL__DEC_PER_SHIFT 36
#define MSS_COMMON_BND_THRT_CTL__DEC_PER_WIDTH 5
#define MSS_COMMON_BND_THRT_CTL__DEC_PER_RESET_VAL 4
#define MSS_COMMON_BND_THRT_CTL__DEC_PER_RMASK 0x1f
#define MSS_COMMON_BND_THRT_CTL__DEC_PER_MASK  _64bit(0x1f000000000)
#define MSS_COMMON_BND_THRT_CTL__DEC_PER_FIELD 36,40

#define MSS_COMMON_BND_THRT_CTL__INC_PER_SHIFT 41
#define MSS_COMMON_BND_THRT_CTL__INC_PER_WIDTH 5
#define MSS_COMMON_BND_THRT_CTL__INC_PER_RESET_VAL 5
#define MSS_COMMON_BND_THRT_CTL__INC_PER_RMASK 0x1f
#define MSS_COMMON_BND_THRT_CTL__INC_PER_MASK  _64bit(0x3e0000000000)
#define MSS_COMMON_BND_THRT_CTL__INC_PER_FIELD 41,45

#define MSS_COMMON_BND_THRT_CTL__WIN_LEN_SHIFT 46
#define MSS_COMMON_BND_THRT_CTL__WIN_LEN_WIDTH 18
#define MSS_COMMON_BND_THRT_CTL__WIN_LEN_RESET_VAL 1000
#define MSS_COMMON_BND_THRT_CTL__WIN_LEN_RMASK 0x3ffff
#define MSS_COMMON_BND_THRT_CTL__WIN_LEN_MASK  _64bit(0xffffc00000000000)
#define MSS_COMMON_BND_THRT_CTL__WIN_LEN_FIELD 46,63


/*
 * BandWidth Throttle Control.
 * Control Bandwidth throttle algorithm behavior.There are four bandwidth
 * throttle control registers, which respectively control WRITE-CDN,
 * WRITE-DDN, READ-CDN and READ-DDN channel
 */
#define MSS_COMMON_BND_THRT_CTL_1__FIRST_WORD 0x00a8
#define MSS_COMMON_BND_THRT_CTL_1__LAST_WORD 0x00c0
#define MSS_COMMON_BND_THRT_CTL_1__LENGTH 0x0020
#define MSS_COMMON_BND_THRT_CTL_1__STRIDE 0x0008

#define MSS_COMMON_BND_THRT_CTL_1__EN_SHIFT 0
#define MSS_COMMON_BND_THRT_CTL_1__EN_WIDTH 1
#define MSS_COMMON_BND_THRT_CTL_1__EN_RESET_VAL 0
#define MSS_COMMON_BND_THRT_CTL_1__EN_RMASK 0x1
#define MSS_COMMON_BND_THRT_CTL_1__EN_MASK  0x1
#define MSS_COMMON_BND_THRT_CTL_1__EN_FIELD 0,0

#define MSS_COMMON_BND_THRT_CTL_1__CONG_THRES_SHIFT 1
#define MSS_COMMON_BND_THRT_CTL_1__CONG_THRES_WIDTH 15
#define MSS_COMMON_BND_THRT_CTL_1__CONG_THRES_RESET_VAL 256
#define MSS_COMMON_BND_THRT_CTL_1__CONG_THRES_RMASK 0x7fff
#define MSS_COMMON_BND_THRT_CTL_1__CONG_THRES_MASK  0xfffe
#define MSS_COMMON_BND_THRT_CTL_1__CONG_THRES_FIELD 1,15

#define MSS_COMMON_BND_THRT_CTL_1__MAX_SHIFT 16
#define MSS_COMMON_BND_THRT_CTL_1__MAX_WIDTH 10
#define MSS_COMMON_BND_THRT_CTL_1__MAX_RESET_VAL 1023
#define MSS_COMMON_BND_THRT_CTL_1__MAX_RMASK 0x3ff
#define MSS_COMMON_BND_THRT_CTL_1__MAX_MASK  0x3ff0000
#define MSS_COMMON_BND_THRT_CTL_1__MAX_FIELD 16,25

#define MSS_COMMON_BND_THRT_CTL_1__MIN_SHIFT 26
#define MSS_COMMON_BND_THRT_CTL_1__MIN_WIDTH 10
#define MSS_COMMON_BND_THRT_CTL_1__MIN_RESET_VAL 1
#define MSS_COMMON_BND_THRT_CTL_1__MIN_RMASK 0x3ff
#define MSS_COMMON_BND_THRT_CTL_1__MIN_MASK  _64bit(0xffc000000)
#define MSS_COMMON_BND_THRT_CTL_1__MIN_FIELD 26,35

#define MSS_COMMON_BND_THRT_CTL_1__DEC_PER_SHIFT 36
#define MSS_COMMON_BND_THRT_CTL_1__DEC_PER_WIDTH 5
#define MSS_COMMON_BND_THRT_CTL_1__DEC_PER_RESET_VAL 4
#define MSS_COMMON_BND_THRT_CTL_1__DEC_PER_RMASK 0x1f
#define MSS_COMMON_BND_THRT_CTL_1__DEC_PER_MASK  _64bit(0x1f000000000)
#define MSS_COMMON_BND_THRT_CTL_1__DEC_PER_FIELD 36,40

#define MSS_COMMON_BND_THRT_CTL_1__INC_PER_SHIFT 41
#define MSS_COMMON_BND_THRT_CTL_1__INC_PER_WIDTH 5
#define MSS_COMMON_BND_THRT_CTL_1__INC_PER_RESET_VAL 5
#define MSS_COMMON_BND_THRT_CTL_1__INC_PER_RMASK 0x1f
#define MSS_COMMON_BND_THRT_CTL_1__INC_PER_MASK  _64bit(0x3e0000000000)
#define MSS_COMMON_BND_THRT_CTL_1__INC_PER_FIELD 41,45

#define MSS_COMMON_BND_THRT_CTL_1__WIN_LEN_SHIFT 46
#define MSS_COMMON_BND_THRT_CTL_1__WIN_LEN_WIDTH 18
#define MSS_COMMON_BND_THRT_CTL_1__WIN_LEN_RESET_VAL 1000
#define MSS_COMMON_BND_THRT_CTL_1__WIN_LEN_RMASK 0x3ffff
#define MSS_COMMON_BND_THRT_CTL_1__WIN_LEN_MASK  _64bit(0xffffc00000000000)
#define MSS_COMMON_BND_THRT_CTL_1__WIN_LEN_FIELD 46,63


/*
 * BandWidth Throttle Control.
 * Control Bandwidth throttle algorithm behavior.There are four bandwidth
 * throttle control registers, which respectively control WRITE-CDN,
 * WRITE-DDN, READ-CDN and READ-DDN channel
 */
#define MSS_COMMON_BND_THRT_CTL_2__FIRST_WORD 0x00b0
#define MSS_COMMON_BND_THRT_CTL_2__LAST_WORD 0x00c8
#define MSS_COMMON_BND_THRT_CTL_2__LENGTH 0x0020
#define MSS_COMMON_BND_THRT_CTL_2__STRIDE 0x0008

#define MSS_COMMON_BND_THRT_CTL_2__EN_SHIFT 0
#define MSS_COMMON_BND_THRT_CTL_2__EN_WIDTH 1
#define MSS_COMMON_BND_THRT_CTL_2__EN_RESET_VAL 0
#define MSS_COMMON_BND_THRT_CTL_2__EN_RMASK 0x1
#define MSS_COMMON_BND_THRT_CTL_2__EN_MASK  0x1
#define MSS_COMMON_BND_THRT_CTL_2__EN_FIELD 0,0

#define MSS_COMMON_BND_THRT_CTL_2__CONG_THRES_SHIFT 1
#define MSS_COMMON_BND_THRT_CTL_2__CONG_THRES_WIDTH 15
#define MSS_COMMON_BND_THRT_CTL_2__CONG_THRES_RESET_VAL 256
#define MSS_COMMON_BND_THRT_CTL_2__CONG_THRES_RMASK 0x7fff
#define MSS_COMMON_BND_THRT_CTL_2__CONG_THRES_MASK  0xfffe
#define MSS_COMMON_BND_THRT_CTL_2__CONG_THRES_FIELD 1,15

#define MSS_COMMON_BND_THRT_CTL_2__MAX_SHIFT 16
#define MSS_COMMON_BND_THRT_CTL_2__MAX_WIDTH 10
#define MSS_COMMON_BND_THRT_CTL_2__MAX_RESET_VAL 1023
#define MSS_COMMON_BND_THRT_CTL_2__MAX_RMASK 0x3ff
#define MSS_COMMON_BND_THRT_CTL_2__MAX_MASK  0x3ff0000
#define MSS_COMMON_BND_THRT_CTL_2__MAX_FIELD 16,25

#define MSS_COMMON_BND_THRT_CTL_2__MIN_SHIFT 26
#define MSS_COMMON_BND_THRT_CTL_2__MIN_WIDTH 10
#define MSS_COMMON_BND_THRT_CTL_2__MIN_RESET_VAL 1
#define MSS_COMMON_BND_THRT_CTL_2__MIN_RMASK 0x3ff
#define MSS_COMMON_BND_THRT_CTL_2__MIN_MASK  _64bit(0xffc000000)
#define MSS_COMMON_BND_THRT_CTL_2__MIN_FIELD 26,35

#define MSS_COMMON_BND_THRT_CTL_2__DEC_PER_SHIFT 36
#define MSS_COMMON_BND_THRT_CTL_2__DEC_PER_WIDTH 5
#define MSS_COMMON_BND_THRT_CTL_2__DEC_PER_RESET_VAL 4
#define MSS_COMMON_BND_THRT_CTL_2__DEC_PER_RMASK 0x1f
#define MSS_COMMON_BND_THRT_CTL_2__DEC_PER_MASK  _64bit(0x1f000000000)
#define MSS_COMMON_BND_THRT_CTL_2__DEC_PER_FIELD 36,40

#define MSS_COMMON_BND_THRT_CTL_2__INC_PER_SHIFT 41
#define MSS_COMMON_BND_THRT_CTL_2__INC_PER_WIDTH 5
#define MSS_COMMON_BND_THRT_CTL_2__INC_PER_RESET_VAL 5
#define MSS_COMMON_BND_THRT_CTL_2__INC_PER_RMASK 0x1f
#define MSS_COMMON_BND_THRT_CTL_2__INC_PER_MASK  _64bit(0x3e0000000000)
#define MSS_COMMON_BND_THRT_CTL_2__INC_PER_FIELD 41,45

#define MSS_COMMON_BND_THRT_CTL_2__WIN_LEN_SHIFT 46
#define MSS_COMMON_BND_THRT_CTL_2__WIN_LEN_WIDTH 18
#define MSS_COMMON_BND_THRT_CTL_2__WIN_LEN_RESET_VAL 1000
#define MSS_COMMON_BND_THRT_CTL_2__WIN_LEN_RMASK 0x3ffff
#define MSS_COMMON_BND_THRT_CTL_2__WIN_LEN_MASK  _64bit(0xffffc00000000000)
#define MSS_COMMON_BND_THRT_CTL_2__WIN_LEN_FIELD 46,63


/*
 * BandWidth Throttle Control.
 * Control Bandwidth throttle algorithm behavior.There are four bandwidth
 * throttle control registers, which respectively control WRITE-CDN,
 * WRITE-DDN, READ-CDN and READ-DDN channel
 */
#define MSS_COMMON_BND_THRT_CTL_3__FIRST_WORD 0x00b8
#define MSS_COMMON_BND_THRT_CTL_3__LAST_WORD 0x00d0
#define MSS_COMMON_BND_THRT_CTL_3__LENGTH 0x0020
#define MSS_COMMON_BND_THRT_CTL_3__STRIDE 0x0008

#define MSS_COMMON_BND_THRT_CTL_3__EN_SHIFT 0
#define MSS_COMMON_BND_THRT_CTL_3__EN_WIDTH 1
#define MSS_COMMON_BND_THRT_CTL_3__EN_RESET_VAL 0
#define MSS_COMMON_BND_THRT_CTL_3__EN_RMASK 0x1
#define MSS_COMMON_BND_THRT_CTL_3__EN_MASK  0x1
#define MSS_COMMON_BND_THRT_CTL_3__EN_FIELD 0,0

#define MSS_COMMON_BND_THRT_CTL_3__CONG_THRES_SHIFT 1
#define MSS_COMMON_BND_THRT_CTL_3__CONG_THRES_WIDTH 15
#define MSS_COMMON_BND_THRT_CTL_3__CONG_THRES_RESET_VAL 256
#define MSS_COMMON_BND_THRT_CTL_3__CONG_THRES_RMASK 0x7fff
#define MSS_COMMON_BND_THRT_CTL_3__CONG_THRES_MASK  0xfffe
#define MSS_COMMON_BND_THRT_CTL_3__CONG_THRES_FIELD 1,15

#define MSS_COMMON_BND_THRT_CTL_3__MAX_SHIFT 16
#define MSS_COMMON_BND_THRT_CTL_3__MAX_WIDTH 10
#define MSS_COMMON_BND_THRT_CTL_3__MAX_RESET_VAL 1023
#define MSS_COMMON_BND_THRT_CTL_3__MAX_RMASK 0x3ff
#define MSS_COMMON_BND_THRT_CTL_3__MAX_MASK  0x3ff0000
#define MSS_COMMON_BND_THRT_CTL_3__MAX_FIELD 16,25

#define MSS_COMMON_BND_THRT_CTL_3__MIN_SHIFT 26
#define MSS_COMMON_BND_THRT_CTL_3__MIN_WIDTH 10
#define MSS_COMMON_BND_THRT_CTL_3__MIN_RESET_VAL 1
#define MSS_COMMON_BND_THRT_CTL_3__MIN_RMASK 0x3ff
#define MSS_COMMON_BND_THRT_CTL_3__MIN_MASK  _64bit(0xffc000000)
#define MSS_COMMON_BND_THRT_CTL_3__MIN_FIELD 26,35

#define MSS_COMMON_BND_THRT_CTL_3__DEC_PER_SHIFT 36
#define MSS_COMMON_BND_THRT_CTL_3__DEC_PER_WIDTH 5
#define MSS_COMMON_BND_THRT_CTL_3__DEC_PER_RESET_VAL 4
#define MSS_COMMON_BND_THRT_CTL_3__DEC_PER_RMASK 0x1f
#define MSS_COMMON_BND_THRT_CTL_3__DEC_PER_MASK  _64bit(0x1f000000000)
#define MSS_COMMON_BND_THRT_CTL_3__DEC_PER_FIELD 36,40

#define MSS_COMMON_BND_THRT_CTL_3__INC_PER_SHIFT 41
#define MSS_COMMON_BND_THRT_CTL_3__INC_PER_WIDTH 5
#define MSS_COMMON_BND_THRT_CTL_3__INC_PER_RESET_VAL 5
#define MSS_COMMON_BND_THRT_CTL_3__INC_PER_RMASK 0x1f
#define MSS_COMMON_BND_THRT_CTL_3__INC_PER_MASK  _64bit(0x3e0000000000)
#define MSS_COMMON_BND_THRT_CTL_3__INC_PER_FIELD 41,45

#define MSS_COMMON_BND_THRT_CTL_3__WIN_LEN_SHIFT 46
#define MSS_COMMON_BND_THRT_CTL_3__WIN_LEN_WIDTH 18
#define MSS_COMMON_BND_THRT_CTL_3__WIN_LEN_RESET_VAL 1000
#define MSS_COMMON_BND_THRT_CTL_3__WIN_LEN_RMASK 0x3ffff
#define MSS_COMMON_BND_THRT_CTL_3__WIN_LEN_MASK  _64bit(0xffffc00000000000)
#define MSS_COMMON_BND_THRT_CTL_3__WIN_LEN_FIELD 46,63


/*
 * Generic performance module configuration register.
 * Set up the configuration of generic performance module
 */
#define MSS_COMMON_GEN_PERFMON_CONFIG__FIRST_WORD 0x00c0
#define MSS_COMMON_GEN_PERFMON_CONFIG__LAST_WORD 0x00d8
#define MSS_COMMON_GEN_PERFMON_CONFIG__LENGTH 0x0020
#define MSS_COMMON_GEN_PERFMON_CONFIG__STRIDE 0x0008

#define MSS_COMMON_GEN_PERFMON_CONFIG__WR_RD_B_SHIFT 0
#define MSS_COMMON_GEN_PERFMON_CONFIG__WR_RD_B_WIDTH 1
#define MSS_COMMON_GEN_PERFMON_CONFIG__WR_RD_B_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG__WR_RD_B_RMASK 0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG__WR_RD_B_MASK  0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG__WR_RD_B_FIELD 0,0

#define MSS_COMMON_GEN_PERFMON_CONFIG__STROBE_SHIFT 1
#define MSS_COMMON_GEN_PERFMON_CONFIG__STROBE_WIDTH 1
#define MSS_COMMON_GEN_PERFMON_CONFIG__STROBE_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG__STROBE_RMASK 0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG__STROBE_MASK  0x2
#define MSS_COMMON_GEN_PERFMON_CONFIG__STROBE_FIELD 1,1

#define MSS_COMMON_GEN_PERFMON_CONFIG__ADDR_SHIFT 2
#define MSS_COMMON_GEN_PERFMON_CONFIG__ADDR_WIDTH 3
#define MSS_COMMON_GEN_PERFMON_CONFIG__ADDR_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG__ADDR_RMASK 0x7
#define MSS_COMMON_GEN_PERFMON_CONFIG__ADDR_MASK  0x1c
#define MSS_COMMON_GEN_PERFMON_CONFIG__ADDR_FIELD 2,4

#define MSS_COMMON_GEN_PERFMON_CONFIG__WDATA_SHIFT 5
#define MSS_COMMON_GEN_PERFMON_CONFIG__WDATA_WIDTH 56
#define MSS_COMMON_GEN_PERFMON_CONFIG__WDATA_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG__WDATA_RMASK _64bit(0xffffffffffffff)
#define MSS_COMMON_GEN_PERFMON_CONFIG__WDATA_MASK  _64bit(0x1fffffffffffffe0)
#define MSS_COMMON_GEN_PERFMON_CONFIG__WDATA_FIELD 5,60


/*
 * Generic performance module configuration register.
 * Set up the configuration of generic performance module
 */
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__FIRST_WORD 0x00c8
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__LAST_WORD 0x00e0
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__LENGTH 0x0020
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__STRIDE 0x0008

#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WR_RD_B_SHIFT 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WR_RD_B_WIDTH 1
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WR_RD_B_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WR_RD_B_RMASK 0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WR_RD_B_MASK  0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WR_RD_B_FIELD 0,0

#define MSS_COMMON_GEN_PERFMON_CONFIG_1__STROBE_SHIFT 1
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__STROBE_WIDTH 1
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__STROBE_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__STROBE_RMASK 0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__STROBE_MASK  0x2
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__STROBE_FIELD 1,1

#define MSS_COMMON_GEN_PERFMON_CONFIG_1__ADDR_SHIFT 2
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__ADDR_WIDTH 3
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__ADDR_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__ADDR_RMASK 0x7
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__ADDR_MASK  0x1c
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__ADDR_FIELD 2,4

#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WDATA_SHIFT 5
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WDATA_WIDTH 56
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WDATA_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WDATA_RMASK _64bit(0xffffffffffffff)
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WDATA_MASK  _64bit(0x1fffffffffffffe0)
#define MSS_COMMON_GEN_PERFMON_CONFIG_1__WDATA_FIELD 5,60


/*
 * Generic performance module configuration register.
 * Set up the configuration of generic performance module
 */
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__FIRST_WORD 0x00d0
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__LAST_WORD 0x00e8
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__LENGTH 0x0020
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__STRIDE 0x0008

#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WR_RD_B_SHIFT 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WR_RD_B_WIDTH 1
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WR_RD_B_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WR_RD_B_RMASK 0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WR_RD_B_MASK  0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WR_RD_B_FIELD 0,0

#define MSS_COMMON_GEN_PERFMON_CONFIG_2__STROBE_SHIFT 1
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__STROBE_WIDTH 1
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__STROBE_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__STROBE_RMASK 0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__STROBE_MASK  0x2
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__STROBE_FIELD 1,1

#define MSS_COMMON_GEN_PERFMON_CONFIG_2__ADDR_SHIFT 2
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__ADDR_WIDTH 3
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__ADDR_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__ADDR_RMASK 0x7
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__ADDR_MASK  0x1c
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__ADDR_FIELD 2,4

#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WDATA_SHIFT 5
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WDATA_WIDTH 56
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WDATA_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WDATA_RMASK _64bit(0xffffffffffffff)
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WDATA_MASK  _64bit(0x1fffffffffffffe0)
#define MSS_COMMON_GEN_PERFMON_CONFIG_2__WDATA_FIELD 5,60


/*
 * Generic performance module configuration register.
 * Set up the configuration of generic performance module
 */
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__FIRST_WORD 0x00d8
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__LAST_WORD 0x00f0
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__LENGTH 0x0020
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__STRIDE 0x0008

#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WR_RD_B_SHIFT 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WR_RD_B_WIDTH 1
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WR_RD_B_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WR_RD_B_RMASK 0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WR_RD_B_MASK  0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WR_RD_B_FIELD 0,0

#define MSS_COMMON_GEN_PERFMON_CONFIG_3__STROBE_SHIFT 1
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__STROBE_WIDTH 1
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__STROBE_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__STROBE_RMASK 0x1
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__STROBE_MASK  0x2
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__STROBE_FIELD 1,1

#define MSS_COMMON_GEN_PERFMON_CONFIG_3__ADDR_SHIFT 2
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__ADDR_WIDTH 3
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__ADDR_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__ADDR_RMASK 0x7
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__ADDR_MASK  0x1c
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__ADDR_FIELD 2,4

#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WDATA_SHIFT 5
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WDATA_WIDTH 56
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WDATA_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WDATA_RMASK _64bit(0xffffffffffffff)
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WDATA_MASK  _64bit(0x1fffffffffffffe0)
#define MSS_COMMON_GEN_PERFMON_CONFIG_3__WDATA_FIELD 5,60


/*
 * Generic performance value register.
 * The register is used to provide interface where software can read the
 * value of generic performance counter
 */
#define MSS_COMMON_GEN_PERFMVAL__FIRST_WORD 0x00e0
#define MSS_COMMON_GEN_PERFMVAL__LAST_WORD 0x00f8
#define MSS_COMMON_GEN_PERFMVAL__LENGTH 0x0020
#define MSS_COMMON_GEN_PERFMVAL__STRIDE 0x0008

#define MSS_COMMON_GEN_PERFMVAL__VAL_SHIFT 0
#define MSS_COMMON_GEN_PERFMVAL__VAL_WIDTH 64
#define MSS_COMMON_GEN_PERFMVAL__VAL_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMVAL__VAL_RMASK _64bit(0xffffffffffffffff)
#define MSS_COMMON_GEN_PERFMVAL__VAL_MASK  _64bit(0xffffffffffffffff)
#define MSS_COMMON_GEN_PERFMVAL__VAL_FIELD 0,63


/*
 * Generic performance value register.
 * The register is used to provide interface where software can read the
 * value of generic performance counter
 */
#define MSS_COMMON_GEN_PERFMVAL_1__FIRST_WORD 0x00e8
#define MSS_COMMON_GEN_PERFMVAL_1__LAST_WORD 0x0100
#define MSS_COMMON_GEN_PERFMVAL_1__LENGTH 0x0020
#define MSS_COMMON_GEN_PERFMVAL_1__STRIDE 0x0008

#define MSS_COMMON_GEN_PERFMVAL_1__VAL_SHIFT 0
#define MSS_COMMON_GEN_PERFMVAL_1__VAL_WIDTH 64
#define MSS_COMMON_GEN_PERFMVAL_1__VAL_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMVAL_1__VAL_RMASK _64bit(0xffffffffffffffff)
#define MSS_COMMON_GEN_PERFMVAL_1__VAL_MASK  _64bit(0xffffffffffffffff)
#define MSS_COMMON_GEN_PERFMVAL_1__VAL_FIELD 0,63


/*
 * Generic performance value register.
 * The register is used to provide interface where software can read the
 * value of generic performance counter
 */
#define MSS_COMMON_GEN_PERFMVAL_2__FIRST_WORD 0x00f0
#define MSS_COMMON_GEN_PERFMVAL_2__LAST_WORD 0x0108
#define MSS_COMMON_GEN_PERFMVAL_2__LENGTH 0x0020
#define MSS_COMMON_GEN_PERFMVAL_2__STRIDE 0x0008

#define MSS_COMMON_GEN_PERFMVAL_2__VAL_SHIFT 0
#define MSS_COMMON_GEN_PERFMVAL_2__VAL_WIDTH 64
#define MSS_COMMON_GEN_PERFMVAL_2__VAL_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMVAL_2__VAL_RMASK _64bit(0xffffffffffffffff)
#define MSS_COMMON_GEN_PERFMVAL_2__VAL_MASK  _64bit(0xffffffffffffffff)
#define MSS_COMMON_GEN_PERFMVAL_2__VAL_FIELD 0,63


/*
 * Generic performance value register.
 * The register is used to provide interface where software can read the
 * value of generic performance counter
 */
#define MSS_COMMON_GEN_PERFMVAL_3__FIRST_WORD 0x00f8
#define MSS_COMMON_GEN_PERFMVAL_3__LAST_WORD 0x0110
#define MSS_COMMON_GEN_PERFMVAL_3__LENGTH 0x0020
#define MSS_COMMON_GEN_PERFMVAL_3__STRIDE 0x0008

#define MSS_COMMON_GEN_PERFMVAL_3__VAL_SHIFT 0
#define MSS_COMMON_GEN_PERFMVAL_3__VAL_WIDTH 64
#define MSS_COMMON_GEN_PERFMVAL_3__VAL_RESET_VAL 0
#define MSS_COMMON_GEN_PERFMVAL_3__VAL_RMASK _64bit(0xffffffffffffffff)
#define MSS_COMMON_GEN_PERFMVAL_3__VAL_MASK  _64bit(0xffffffffffffffff)
#define MSS_COMMON_GEN_PERFMVAL_3__VAL_FIELD 0,63


/*
 * Performance Control Register.
 * The performance control register holds global and per accumulator control
 * fields defining the operation of the module on 0/1 data paths
 */
#define MSS_COMMON_PERFCTL 0x00c0
#define MSS_COMMON_PERFCTL__LENGTH 0x0001

#define MSS_COMMON_PERFCTL__FM1_SHIFT 0
#define MSS_COMMON_PERFCTL__FM1_WIDTH 3
#define MSS_COMMON_PERFCTL__FM1_RESET_VAL 0
#define MSS_COMMON_PERFCTL__FM1_RMASK 0x7
#define MSS_COMMON_PERFCTL__FM1_MASK  0x7
#define MSS_COMMON_PERFCTL__FM1_FIELD 0,2
#define MSS_COMMON_PERFCTL__FM1_VAL_Always 0x0
#define MSS_COMMON_PERFCTL__FM1_VAL_Never 0x1
#define MSS_COMMON_PERFCTL__FM1_VAL_EQ 0x2
#define MSS_COMMON_PERFCTL__FM1_VAL_NEQ 0x3
#define MSS_COMMON_PERFCTL__FM1_VAL_GEQS 0x4
#define MSS_COMMON_PERFCTL__FM1_VAL_LTS 0x5
#define MSS_COMMON_PERFCTL__FM1_VAL_GEQU 0x6
#define MSS_COMMON_PERFCTL__FM1_VAL_LTU 0x7

#define MSS_COMMON_PERFCTL__MS1_SHIFT 4
#define MSS_COMMON_PERFCTL__MS1_WIDTH 2
#define MSS_COMMON_PERFCTL__MS1_RESET_VAL 0
#define MSS_COMMON_PERFCTL__MS1_RMASK 0x3
#define MSS_COMMON_PERFCTL__MS1_MASK  0x30
#define MSS_COMMON_PERFCTL__MS1_FIELD 4,5
#define MSS_COMMON_PERFCTL__MS1_VAL_Independent 0x0
#define MSS_COMMON_PERFCTL__MS1_VAL_AND 0x1
#define MSS_COMMON_PERFCTL__MS1_VAL_OR 0x2
#define MSS_COMMON_PERFCTL__MS1_VAL_EXCL 0x3

#define MSS_COMMON_PERFCTL__ACCM1_SHIFT 8
#define MSS_COMMON_PERFCTL__ACCM1_WIDTH 3
#define MSS_COMMON_PERFCTL__ACCM1_RESET_VAL 0
#define MSS_COMMON_PERFCTL__ACCM1_RMASK 0x7
#define MSS_COMMON_PERFCTL__ACCM1_MASK  0x700
#define MSS_COMMON_PERFCTL__ACCM1_FIELD 8,10
#define MSS_COMMON_PERFCTL__ACCM1_VAL_INC_TM 0x0
#define MSS_COMMON_PERFCTL__ACCM1_VAL_INC_M 0x1
#define MSS_COMMON_PERFCTL__ACCM1_VAL_ADDS 0x2
#define MSS_COMMON_PERFCTL__ACCM1_VAL_ADDU 0x3
#define MSS_COMMON_PERFCTL__ACCM1_VAL_SAMP 0x4
#define MSS_COMMON_PERFCTL__ACCM1_VAL_MIN_DEC 0x5
#define MSS_COMMON_PERFCTL__ACCM1_VAL_MAX_DEC 0x6
#define MSS_COMMON_PERFCTL__ACCM1_VAL_FREE 0x7

#define MSS_COMMON_PERFCTL__AD1_SHIFT 11
#define MSS_COMMON_PERFCTL__AD1_WIDTH 1
#define MSS_COMMON_PERFCTL__AD1_RESET_VAL 0
#define MSS_COMMON_PERFCTL__AD1_RMASK 0x1
#define MSS_COMMON_PERFCTL__AD1_MASK  0x800
#define MSS_COMMON_PERFCTL__AD1_FIELD 11,11
#define MSS_COMMON_PERFCTL__AD1_VAL_DISABLE 0x0
#define MSS_COMMON_PERFCTL__AD1_VAL_ENABLE 0x1

#define MSS_COMMON_PERFCTL__ETRIG1_SHIFT 12
#define MSS_COMMON_PERFCTL__ETRIG1_WIDTH 2
#define MSS_COMMON_PERFCTL__ETRIG1_RESET_VAL 0
#define MSS_COMMON_PERFCTL__ETRIG1_RMASK 0x3
#define MSS_COMMON_PERFCTL__ETRIG1_MASK  0x3000
#define MSS_COMMON_PERFCTL__ETRIG1_FIELD 12,13
#define MSS_COMMON_PERFCTL__ETRIG1_VAL_L_LVL 0x0
#define MSS_COMMON_PERFCTL__ETRIG1_VAL_H_LVL 0x1
#define MSS_COMMON_PERFCTL__ETRIG1_VAL_NEG_EDG 0x2
#define MSS_COMMON_PERFCTL__ETRIG1_VAL_POS_EDG 0x3

#define MSS_COMMON_PERFCTL__EB1_SHIFT 14
#define MSS_COMMON_PERFCTL__EB1_WIDTH 1
#define MSS_COMMON_PERFCTL__EB1_RESET_VAL 0
#define MSS_COMMON_PERFCTL__EB1_RMASK 0x1
#define MSS_COMMON_PERFCTL__EB1_MASK  0x4000
#define MSS_COMMON_PERFCTL__EB1_FIELD 14,14
#define MSS_COMMON_PERFCTL__EB1_VAL_DISABLE 0x0
#define MSS_COMMON_PERFCTL__EB1_VAL_ENABLE 0x1

#define MSS_COMMON_PERFCTL__EN1_SHIFT 15
#define MSS_COMMON_PERFCTL__EN1_WIDTH 1
#define MSS_COMMON_PERFCTL__EN1_RESET_VAL 0
#define MSS_COMMON_PERFCTL__EN1_RMASK 0x1
#define MSS_COMMON_PERFCTL__EN1_MASK  0x8000
#define MSS_COMMON_PERFCTL__EN1_FIELD 15,15

#define MSS_COMMON_PERFCTL__FM0_SHIFT 16
#define MSS_COMMON_PERFCTL__FM0_WIDTH 3
#define MSS_COMMON_PERFCTL__FM0_RESET_VAL 0
#define MSS_COMMON_PERFCTL__FM0_RMASK 0x7
#define MSS_COMMON_PERFCTL__FM0_MASK  0x70000
#define MSS_COMMON_PERFCTL__FM0_FIELD 16,18
#define MSS_COMMON_PERFCTL__FM0_VAL_Always 0x0
#define MSS_COMMON_PERFCTL__FM0_VAL_Never 0x1
#define MSS_COMMON_PERFCTL__FM0_VAL_EQ 0x2
#define MSS_COMMON_PERFCTL__FM0_VAL_NEQ 0x3
#define MSS_COMMON_PERFCTL__FM0_VAL_GEQS 0x4
#define MSS_COMMON_PERFCTL__FM0_VAL_LTS 0x5
#define MSS_COMMON_PERFCTL__FM0_VAL_GEQU 0x6
#define MSS_COMMON_PERFCTL__FM0_VAL_LTU 0x7

#define MSS_COMMON_PERFCTL__MS0_SHIFT 20
#define MSS_COMMON_PERFCTL__MS0_WIDTH 2
#define MSS_COMMON_PERFCTL__MS0_RESET_VAL 0
#define MSS_COMMON_PERFCTL__MS0_RMASK 0x3
#define MSS_COMMON_PERFCTL__MS0_MASK  0x300000
#define MSS_COMMON_PERFCTL__MS0_FIELD 20,21
#define MSS_COMMON_PERFCTL__MS0_VAL_Independent 0x0
#define MSS_COMMON_PERFCTL__MS0_VAL_AND 0x1
#define MSS_COMMON_PERFCTL__MS0_VAL_OR 0x2
#define MSS_COMMON_PERFCTL__MS0_VAL_EXCL 0x3

#define MSS_COMMON_PERFCTL__ACCM0_SHIFT 24
#define MSS_COMMON_PERFCTL__ACCM0_WIDTH 3
#define MSS_COMMON_PERFCTL__ACCM0_RESET_VAL 0
#define MSS_COMMON_PERFCTL__ACCM0_RMASK 0x7
#define MSS_COMMON_PERFCTL__ACCM0_MASK  0x7000000
#define MSS_COMMON_PERFCTL__ACCM0_FIELD 24,26
#define MSS_COMMON_PERFCTL__ACCM0_VAL_INC_TM 0x0
#define MSS_COMMON_PERFCTL__ACCM0_VAL_INC_M 0x1
#define MSS_COMMON_PERFCTL__ACCM0_VAL_ADDS 0x2
#define MSS_COMMON_PERFCTL__ACCM0_VAL_ADDU 0x3
#define MSS_COMMON_PERFCTL__ACCM0_VAL_SAMP 0x4
#define MSS_COMMON_PERFCTL__ACCM0_VAL_MIN_DEC 0x5
#define MSS_COMMON_PERFCTL__ACCM0_VAL_MAX_DEC 0x6
#define MSS_COMMON_PERFCTL__ACCM0_VAL_FREE 0x7

#define MSS_COMMON_PERFCTL__AD0_SHIFT 27
#define MSS_COMMON_PERFCTL__AD0_WIDTH 1
#define MSS_COMMON_PERFCTL__AD0_RESET_VAL 0
#define MSS_COMMON_PERFCTL__AD0_RMASK 0x1
#define MSS_COMMON_PERFCTL__AD0_MASK  0x8000000
#define MSS_COMMON_PERFCTL__AD0_FIELD 27,27
#define MSS_COMMON_PERFCTL__AD0_VAL_DISABLE 0x0
#define MSS_COMMON_PERFCTL__AD0_VAL_ENABLE 0x1

#define MSS_COMMON_PERFCTL__ETRIG0_SHIFT 28
#define MSS_COMMON_PERFCTL__ETRIG0_WIDTH 2
#define MSS_COMMON_PERFCTL__ETRIG0_RESET_VAL 0
#define MSS_COMMON_PERFCTL__ETRIG0_RMASK 0x3
#define MSS_COMMON_PERFCTL__ETRIG0_MASK  0x30000000
#define MSS_COMMON_PERFCTL__ETRIG0_FIELD 28,29
#define MSS_COMMON_PERFCTL__ETRIG0_VAL_L_LVL 0x0
#define MSS_COMMON_PERFCTL__ETRIG0_VAL_H_LVL 0x1
#define MSS_COMMON_PERFCTL__ETRIG0_VAL_NEG_EDG 0x2
#define MSS_COMMON_PERFCTL__ETRIG0_VAL_POS_EDG 0x3

#define MSS_COMMON_PERFCTL__EB0_SHIFT 30
#define MSS_COMMON_PERFCTL__EB0_WIDTH 1
#define MSS_COMMON_PERFCTL__EB0_RESET_VAL 0
#define MSS_COMMON_PERFCTL__EB0_RMASK 0x1
#define MSS_COMMON_PERFCTL__EB0_MASK  0x40000000
#define MSS_COMMON_PERFCTL__EB0_FIELD 30,30
#define MSS_COMMON_PERFCTL__EB0_VAL_DISABLE 0x0
#define MSS_COMMON_PERFCTL__EB0_VAL_ENABLE 0x1

#define MSS_COMMON_PERFCTL__EN0_SHIFT 31
#define MSS_COMMON_PERFCTL__EN0_WIDTH 1
#define MSS_COMMON_PERFCTL__EN0_RESET_VAL 0
#define MSS_COMMON_PERFCTL__EN0_RMASK 0x1
#define MSS_COMMON_PERFCTL__EN0_MASK  0x80000000
#define MSS_COMMON_PERFCTL__EN0_FIELD 31,31


/*
 * Performance Event Selection Register.
 * The performance event selection register controls multiplexing logic at
 * the block level
 */
#define MSS_COMMON_PERFEVT 0x00c0
#define MSS_COMMON_PERFEVT__LENGTH 0x0001

#define MSS_COMMON_PERFEVT__PVALSEL_SHIFT 16
#define MSS_COMMON_PERFEVT__PVALSEL_WIDTH 4
#define MSS_COMMON_PERFEVT__PVALSEL_RESET_VAL 0
#define MSS_COMMON_PERFEVT__PVALSEL_RMASK 0xf
#define MSS_COMMON_PERFEVT__PVALSEL_MASK  0xf0000
#define MSS_COMMON_PERFEVT__PVALSEL_FIELD 16,19
#define MSS_COMMON_PERFEVT__PVALSEL_VAL_AW_LAT 0x0
#define MSS_COMMON_PERFEVT__PVALSEL_VAL_AR_LAT 0x1
#define MSS_COMMON_PERFEVT__PVALSEL_VAL_TXREQ_FLIT 0x2

#define MSS_COMMON_PERFEVT__MODSEL_SHIFT 20
#define MSS_COMMON_PERFEVT__MODSEL_WIDTH 4
#define MSS_COMMON_PERFEVT__MODSEL_RESET_VAL 0
#define MSS_COMMON_PERFEVT__MODSEL_RMASK 0xf
#define MSS_COMMON_PERFEVT__MODSEL_MASK  0xf00000
#define MSS_COMMON_PERFEVT__MODSEL_FIELD 20,23

#define MSS_COMMON_PERFEVT__EVTSEL_SHIFT 24
#define MSS_COMMON_PERFEVT__EVTSEL_WIDTH 8
#define MSS_COMMON_PERFEVT__EVTSEL_RESET_VAL 0
#define MSS_COMMON_PERFEVT__EVTSEL_RMASK 0xff
#define MSS_COMMON_PERFEVT__EVTSEL_MASK  0xff000000
#define MSS_COMMON_PERFEVT__EVTSEL_FIELD 24,31
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AW_REQ 0x0
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AW_BEATS 0x1
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AW_TRANS 0x2
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AW_RESP 0x3
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AW_STL 0x4
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AW_LAT 0x5
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AW_REQ_TBU 0x6
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AR_REQ 0x8
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AR_BEATS 0x9
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AR_TRANS 0xa
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AR_STL 0xb
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AR_LAT 0xc
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_AR_REQ_TBU 0xd
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TBU_MISS 0xe
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TX_DAT_AF 0xf
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RX_DAT_AF 0x10
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RETRYQ_CRED 0x11
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_REQ 0x12
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_REQ 0x13
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_REQ 0x14
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_N_OUT_OF_CRED 0x15
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_S_OUT_OF_CRED 0x16
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_E_OUT_OF_CRED 0x17
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_W_OUT_OF_CRED 0x18
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_C_OUT_OF_CRED 0x19
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_N_EGRESS 0x1a
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_S_EGRESS 0x1b
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_E_EGRESS 0x1c
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_W_EGRESS 0x1d
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_C_EGRESS 0x1e
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_N_INGRESS 0x1f
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_S_INGRESS 0x20
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_E_INGRESS 0x21
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_W_INGRESS 0x22
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_C_INGRESS 0x23
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_CDN_DIAG_CORE_SENT 0x24
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_N_OUT_OF_CRED 0x25
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_S_OUT_OF_CRED 0x26
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_E_OUT_OF_CRED 0x27
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_W_OUT_OF_CRED 0x28
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_C_OUT_OF_CRED 0x29
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_N_EGRESS 0x2a
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_S_EGRESS 0x2b
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_E_EGRESS 0x2c
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_W_EGRESS 0x2d
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_C_EGRESS 0x2e
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_N_INGRESS 0x2f
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_S_INGRESS 0x30
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_E_INGRESS 0x31
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_W_INGRESS 0x32
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_C_INGRESS 0x33
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DDN_DIAG_CORE_SENT 0x34
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_N_OUT_OF_CRED 0x35
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_S_OUT_OF_CRED 0x36
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_E_OUT_OF_CRED 0x37
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_W_OUT_OF_CRED 0x38
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_C_OUT_OF_CRED 0x39
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_N_EGRESS 0x3a
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_S_EGRESS 0x3b
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_E_EGRESS 0x3c
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_W_EGRESS 0x3d
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_C_EGRESS 0x3e
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_N_INGRESS 0x3f
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_S_INGRESS 0x40
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_E_INGRESS 0x41
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_W_INGRESS 0x42
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_C_INGRESS 0x43
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_NDN_DIAG_CORE_SENT 0x44
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_HNF_REQUESTS 0x45
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_HNF_REJECTS 0x46
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_ALL_BUSY 0x47
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_MAF_BUSY 0x48
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_MAF_REQUESTS 0x49
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RNF_REQUESTS 0x4a
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_REQUEST_TYPE 0x4b
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_MEMORY_READS 0x4c
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_MEMORY_WRITES 0x4d
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_VICTIM_WRITE 0x4e
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_POC_FULL 0x4f
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_POC_FAIL 0x50
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_POC_SUCCESS 0x51
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_POC_WRITES 0x52
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_POC_READS 0x53
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_FORWARD 0x54
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RXREQ_HNF 0x55
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RXRSP_HNF 0x56
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RXDAT_HNF 0x57
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXREQ_HNF 0x58
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXRSP_HNF 0x59
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXDAT_HNF 0x5a
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXSNP_HNF 0x5b
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_INDEX_MATCH 0x5c
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_A72_ACCESS 0x5d
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_IO_ACCESS 0x5e
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TSO_WRITE 0x5f
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TSO_CONFLICT 0x60
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_DIR_HIT 0x61
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_HNF_ACCEPTS 0x62
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_REQ_BUF_EMPTY 0x63
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_REQ_BUF_IDLE_MAF 0x64
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TSO_NOARB 0x65
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TSO_NOARB_CYCLES 0x66
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_MSS_NO_CREDIT 0x67
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXDAT_NO_LCRD 0x68
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXSNP_NO_LCRD 0x69
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXRSP_NO_LCRD 0x6a
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXREQ_NO_LCRD 0x6b
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TSO_CL_MATCH 0x6c
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_MEMORY_READS_BYPASS 0x6d
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TSO_NOARB_TIMEOUT 0x6e
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_ALLOCATE 0x6f
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_VICTIM 0x70
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_A72_WRITE 0x71
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_A72_Read 0x72
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_IO_WRITE 0x73
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_IO_Reads 0x74
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TSO_Reject 0x75
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXREQ_RN 0x80
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXRSP_RN 0x81
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXDAT_RN 0x82
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RXSNP_RN 0x83
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RXRSP_RN 0x84
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RXDAT_RN 0x85
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TPIO_DATA_BEAT 0xa0
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TDMA_DATA_BEAT 0xa1
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_MAP_DATA_BEAT 0xa2
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXMSG_DATA_BEAT 0xa3
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TPIO_DATA_PACKET 0xa4
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TDMA_DATA_PACKET 0xa5
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_MAP_DATA_PACKET 0xa6
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXMSG_DATA_PACKET 0xa7
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TDMA_RT_AF 0xa8
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TDMA_PBUF_MAC_AF 0xa9
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_MAP_WRQ_BUF_EMPTY 0xaa
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_MAP_CPL_BUF_EMPTY 0xab
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_MAP_RDQ0_BUF_EMPTY 0xac
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_MAP_RDQ1_BUF_EMPTY 0xad
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_MAP_RDQ2_BUF_EMPTY 0xae
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_MAP_RDQ3_BUF_EMPTY 0xaf
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_MAP_RDQ4_BUF_EMPTY 0xb0
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_MAP_RDQ5_BUF_EMPTY 0xb1
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_MAP_RDQ6_BUF_EMPTY 0xb2
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_MAP_RDQ7_BUF_EMPTY 0xb3
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_RING_TX_FLIT_CH0 0xb4
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_RING_TX_FLIT_CH1 0xb5
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_RING_TX_FLIT_CH2 0xb6
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_RING_TX_FLIT_CH3 0xb7
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_RING_TX_FLIT_CH4 0xb8
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_RING_RX_FLIT_CH0 0xb9
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_RING_RX_FLIT_CH1 0xba
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_RING_RX_FLIT_CH2 0xbb
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TRIO_RING_RX_FLIT_CH3 0xbc
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RXREQ_MSS 0xc0
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_RXDAT_MSS 0xc1
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXRSP_MSS 0xc2
#define MSS_COMMON_PERFEVT__EVTSEL_VAL_TXDAT_MSS 0xc3


/*
 * Performance Value Extraction Register.
 * The performance value extraction register extracts two 56-bit values out
 * of PVAL with bitwise offset and width control
 */
#define MSS_COMMON_PERFVALEXT 0x00c0
#define MSS_COMMON_PERFVALEXT__LENGTH 0x0001

#define MSS_COMMON_PERFVALEXT__VOFS1_SHIFT 0
#define MSS_COMMON_PERFVALEXT__VOFS1_WIDTH 7
#define MSS_COMMON_PERFVALEXT__VOFS1_RESET_VAL 0
#define MSS_COMMON_PERFVALEXT__VOFS1_RMASK 0x7f
#define MSS_COMMON_PERFVALEXT__VOFS1_MASK  0x7f
#define MSS_COMMON_PERFVALEXT__VOFS1_FIELD 0,6

#define MSS_COMMON_PERFVALEXT__VLEN1_SHIFT 8
#define MSS_COMMON_PERFVALEXT__VLEN1_WIDTH 6
#define MSS_COMMON_PERFVALEXT__VLEN1_RESET_VAL 0
#define MSS_COMMON_PERFVALEXT__VLEN1_RMASK 0x3f
#define MSS_COMMON_PERFVALEXT__VLEN1_MASK  0x3f00
#define MSS_COMMON_PERFVALEXT__VLEN1_FIELD 8,13

#define MSS_COMMON_PERFVALEXT__VOFS0_SHIFT 16
#define MSS_COMMON_PERFVALEXT__VOFS0_WIDTH 7
#define MSS_COMMON_PERFVALEXT__VOFS0_RESET_VAL 0
#define MSS_COMMON_PERFVALEXT__VOFS0_RMASK 0x7f
#define MSS_COMMON_PERFVALEXT__VOFS0_MASK  0x7f0000
#define MSS_COMMON_PERFVALEXT__VOFS0_FIELD 16,22

#define MSS_COMMON_PERFVALEXT__VLEN0_SHIFT 24
#define MSS_COMMON_PERFVALEXT__VLEN0_WIDTH 6
#define MSS_COMMON_PERFVALEXT__VLEN0_RESET_VAL 0
#define MSS_COMMON_PERFVALEXT__VLEN0_RMASK 0x3f
#define MSS_COMMON_PERFVALEXT__VLEN0_MASK  0x3f000000
#define MSS_COMMON_PERFVALEXT__VLEN0_FIELD 24,29


/*
 * Performance Accumulator 0 Register.
 * This register enable both reading and updating the 32-bit value
 * accumulated by accumulator 0.
 */
#define MSS_COMMON_PERFACC0 0x00c0
#define MSS_COMMON_PERFACC0__LENGTH 0x0001

#define MSS_COMMON_PERFACC0__ACC_SHIFT 0
#define MSS_COMMON_PERFACC0__ACC_WIDTH 56
#define MSS_COMMON_PERFACC0__ACC_RESET_VAL 0
#define MSS_COMMON_PERFACC0__ACC_RMASK _64bit(0xffffffffffffff)
#define MSS_COMMON_PERFACC0__ACC_MASK  _64bit(0xffffffffffffff)
#define MSS_COMMON_PERFACC0__ACC_FIELD 0,55


/*
 * Performance Accumulator 1 Register.
 * This register enable both reading and updating the 32-bit value
 * accumulated by accumulator 1.
 */
#define MSS_COMMON_PERFACC1 0x00c0
#define MSS_COMMON_PERFACC1__LENGTH 0x0001

#define MSS_COMMON_PERFACC1__ACC_SHIFT 0
#define MSS_COMMON_PERFACC1__ACC_WIDTH 56
#define MSS_COMMON_PERFACC1__ACC_RESET_VAL 0
#define MSS_COMMON_PERFACC1__ACC_RMASK _64bit(0xffffffffffffff)
#define MSS_COMMON_PERFACC1__ACC_MASK  _64bit(0xffffffffffffff)
#define MSS_COMMON_PERFACC1__ACC_FIELD 0,55


/*
 * Performance Match Value 0 Register.
 * This register provides up to 32-bit match to be compared with extracted
 * value 0 according to PERFCTL register configurations.
 */
#define MSS_COMMON_PERFMVAL0 0x00c0
#define MSS_COMMON_PERFMVAL0__LENGTH 0x0001

#define MSS_COMMON_PERFMVAL0__MVAL_SHIFT 0
#define MSS_COMMON_PERFMVAL0__MVAL_WIDTH 32
#define MSS_COMMON_PERFMVAL0__MVAL_RESET_VAL 0
#define MSS_COMMON_PERFMVAL0__MVAL_RMASK 0xffffffff
#define MSS_COMMON_PERFMVAL0__MVAL_MASK  0xffffffff
#define MSS_COMMON_PERFMVAL0__MVAL_FIELD 0,31


/*
 * Performance Match Value 1 Register.
 * This register provides up to 32-bit match to be compared with extracted
 * value 1 according to PERFCTL register configurations.
 */
#define MSS_COMMON_PERFMVAL1 0x00c0
#define MSS_COMMON_PERFMVAL1__LENGTH 0x0001

#define MSS_COMMON_PERFMVAL1__MVAL_SHIFT 0
#define MSS_COMMON_PERFMVAL1__MVAL_WIDTH 32
#define MSS_COMMON_PERFMVAL1__MVAL_RESET_VAL 0
#define MSS_COMMON_PERFMVAL1__MVAL_RMASK 0xffffffff
#define MSS_COMMON_PERFMVAL1__MVAL_MASK  0xffffffff
#define MSS_COMMON_PERFMVAL1__MVAL_FIELD 0,31

#endif /* !defined(__DOXYGEN__) */

#endif /* !defined(__REGS_MSS_COMMON_DEF_H__) */
