#ifndef __REGS_OOB_DEF_H__
#define __REGS_OOB_DEF_H__

#ifdef __ASSEMBLER__
#define _64bit(x) x
#else /* __ASSEMBLER__ */
#ifdef __tile__
#define _64bit(x) x ## UL
#else /* __tile__ */
#define _64bit(x) x ## ULL
#endif /* __tile__ */
#endif /* __ASSEMBLER */



#ifndef __DOXYGEN__

/* Scratchpad. */
#define OOB_SCRATCHPAD 0x0020
#define OOB_SCRATCHPAD__LENGTH 0x0001

#define OOB_SCRATCHPAD__SCRATCHPAD_SHIFT 0
#define OOB_SCRATCHPAD__SCRATCHPAD_WIDTH 64
#define OOB_SCRATCHPAD__SCRATCHPAD_RESET_VAL 0
#define OOB_SCRATCHPAD__SCRATCHPAD_RMASK _64bit(0xffffffffffffffff)
#define OOB_SCRATCHPAD__SCRATCHPAD_MASK  _64bit(0xffffffffffffffff)
#define OOB_SCRATCHPAD__SCRATCHPAD_FIELD 0,63


/*
 * TX work queue size log2.
 * log2 of the size of the work queue (number of entries), minimum value is
 * 2, maximum value is 8
 */
#define OOB_TX_WQ_SIZE_LOG2 0x0100
#define OOB_TX_WQ_SIZE_LOG2__LENGTH 0x0001

#define OOB_TX_WQ_SIZE_LOG2__TX_WQ_SIZE_LOG2_SHIFT 0
#define OOB_TX_WQ_SIZE_LOG2__TX_WQ_SIZE_LOG2_WIDTH 4
#define OOB_TX_WQ_SIZE_LOG2__TX_WQ_SIZE_LOG2_RESET_VAL 0
#define OOB_TX_WQ_SIZE_LOG2__TX_WQ_SIZE_LOG2_RMASK 0xf
#define OOB_TX_WQ_SIZE_LOG2__TX_WQ_SIZE_LOG2_MASK  0xf
#define OOB_TX_WQ_SIZE_LOG2__TX_WQ_SIZE_LOG2_FIELD 0,3


/*
 * TX work queue first address.
 * The first address of the work queue
 */
#define OOB_TX_WQ_FIRST_ADDRESS 0x0108
#define OOB_TX_WQ_FIRST_ADDRESS__LENGTH 0x0001

#define OOB_TX_WQ_FIRST_ADDRESS__TX_WQ_FIRST_ADDRESS_SHIFT 12
#define OOB_TX_WQ_FIRST_ADDRESS__TX_WQ_FIRST_ADDRESS_WIDTH 28
#define OOB_TX_WQ_FIRST_ADDRESS__TX_WQ_FIRST_ADDRESS_RESET_VAL 0
#define OOB_TX_WQ_FIRST_ADDRESS__TX_WQ_FIRST_ADDRESS_RMASK 0xfffffff
#define OOB_TX_WQ_FIRST_ADDRESS__TX_WQ_FIRST_ADDRESS_MASK  _64bit(0xfffffff000)
#define OOB_TX_WQ_FIRST_ADDRESS__TX_WQ_FIRST_ADDRESS_FIELD 12,39


/*
 * TX producer index.
 * SW updates this register when there are available wqes to read
 */
#define OOB_TX_PRODUCER_INDEX 0x0110
#define OOB_TX_PRODUCER_INDEX__LENGTH 0x0001

#define OOB_TX_PRODUCER_INDEX__TX_PRODUCER_INDEX_SHIFT 0
#define OOB_TX_PRODUCER_INDEX__TX_PRODUCER_INDEX_WIDTH 16
#define OOB_TX_PRODUCER_INDEX__TX_PRODUCER_INDEX_RESET_VAL 0
#define OOB_TX_PRODUCER_INDEX__TX_PRODUCER_INDEX_RMASK 0xffff
#define OOB_TX_PRODUCER_INDEX__TX_PRODUCER_INDEX_MASK  0xffff
#define OOB_TX_PRODUCER_INDEX__TX_PRODUCER_INDEX_FIELD 0,15


/*
 * TX consumer index.
 * HW updates this register when wqe was written to tx fifo
 */
#define OOB_TX_CONSUMER_INDEX 0x0118
#define OOB_TX_CONSUMER_INDEX__LENGTH 0x0001

#define OOB_TX_CONSUMER_INDEX__TX_CONSUMER_INDEX_SHIFT 0
#define OOB_TX_CONSUMER_INDEX__TX_CONSUMER_INDEX_WIDTH 16
#define OOB_TX_CONSUMER_INDEX__TX_CONSUMER_INDEX_RESET_VAL 0
#define OOB_TX_CONSUMER_INDEX__TX_CONSUMER_INDEX_RMASK 0xffff
#define OOB_TX_CONSUMER_INDEX__TX_CONSUMER_INDEX_MASK  0xffff
#define OOB_TX_CONSUMER_INDEX__TX_CONSUMER_INDEX_FIELD 0,15


/*
 * TX control Register.
 * This is the control register, with a couple common register types.
 */
#define OOB_TX_CONTROL 0x0120
#define OOB_TX_CONTROL__LENGTH 0x0001

#define OOB_TX_CONTROL__GRACEFULLY_STOP_REQ_SHIFT 0
#define OOB_TX_CONTROL__GRACEFULLY_STOP_REQ_WIDTH 1
#define OOB_TX_CONTROL__GRACEFULLY_STOP_REQ_RESET_VAL 0
#define OOB_TX_CONTROL__GRACEFULLY_STOP_REQ_RMASK 0x1
#define OOB_TX_CONTROL__GRACEFULLY_STOP_REQ_MASK  0x1
#define OOB_TX_CONTROL__GRACEFULLY_STOP_REQ_FIELD 0,0


/*
 * TX counters cycle number register.
 * The amount of cycles the counters will use to count
 */
#define OOB_TX_COUNTERS_CYCLES_NUMBER 0x0128
#define OOB_TX_COUNTERS_CYCLES_NUMBER__LENGTH 0x0001

#define OOB_TX_COUNTERS_CYCLES_NUMBER__TX_COUNTERS_CYCLES_NUMBER_SHIFT 0
#define OOB_TX_COUNTERS_CYCLES_NUMBER__TX_COUNTERS_CYCLES_NUMBER_WIDTH 32
#define OOB_TX_COUNTERS_CYCLES_NUMBER__TX_COUNTERS_CYCLES_NUMBER_RESET_VAL 0
#define OOB_TX_COUNTERS_CYCLES_NUMBER__TX_COUNTERS_CYCLES_NUMBER_RMASK 0xffffffff
#define OOB_TX_COUNTERS_CYCLES_NUMBER__TX_COUNTERS_CYCLES_NUMBER_MASK  0xffffffff
#define OOB_TX_COUNTERS_CYCLES_NUMBER__TX_COUNTERS_CYCLES_NUMBER_FIELD 0,31


/*
 * TX fifo out frames counter cycles number.
 * The number of frames exit from tx fifo in the configured cycles number
 */
#define OOB_TX_FIFO_OUT_FRAMES_COUNTER 0x0148
#define OOB_TX_FIFO_OUT_FRAMES_COUNTER__LENGTH 0x0001

#define OOB_TX_FIFO_OUT_FRAMES_COUNTER__TX_FIFO_OUT_FRAMES_COUNTER_SHIFT 0
#define OOB_TX_FIFO_OUT_FRAMES_COUNTER__TX_FIFO_OUT_FRAMES_COUNTER_WIDTH 32
#define OOB_TX_FIFO_OUT_FRAMES_COUNTER__TX_FIFO_OUT_FRAMES_COUNTER_RESET_VAL 0
#define OOB_TX_FIFO_OUT_FRAMES_COUNTER__TX_FIFO_OUT_FRAMES_COUNTER_RMASK 0xffffffff
#define OOB_TX_FIFO_OUT_FRAMES_COUNTER__TX_FIFO_OUT_FRAMES_COUNTER_MASK  0xffffffff
#define OOB_TX_FIFO_OUT_FRAMES_COUNTER__TX_FIFO_OUT_FRAMES_COUNTER_FIELD 0,31


/*
 * TX producer index equal to consumer index counter cycles number.
 * The number of cycles producer index equal to consumer index in the
 * configured cycles number
 */
#define OOB_TX_PRODUCER_EQUAL_CONSUMER_COUNTER 0x0150
#define OOB_TX_PRODUCER_EQUAL_CONSUMER_COUNTER__LENGTH 0x0001

#define OOB_TX_PRODUCER_EQUAL_CONSUMER_COUNTER__TX_PRODUCER_EQUAL_CONSUMER_COUNTER_SHIFT 0
#define OOB_TX_PRODUCER_EQUAL_CONSUMER_COUNTER__TX_PRODUCER_EQUAL_CONSUMER_COUNTER_WIDTH 32
#define OOB_TX_PRODUCER_EQUAL_CONSUMER_COUNTER__TX_PRODUCER_EQUAL_CONSUMER_COUNTER_RESET_VAL 0
#define OOB_TX_PRODUCER_EQUAL_CONSUMER_COUNTER__TX_PRODUCER_EQUAL_CONSUMER_COUNTER_RMASK 0xffffffff
#define OOB_TX_PRODUCER_EQUAL_CONSUMER_COUNTER__TX_PRODUCER_EQUAL_CONSUMER_COUNTER_MASK  0xffffffff
#define OOB_TX_PRODUCER_EQUAL_CONSUMER_COUNTER__TX_PRODUCER_EQUAL_CONSUMER_COUNTER_FIELD 0,31


/*
 * TX producer index higher by 4 or more than consumer index counter cycles
 * number.
 * The number of cycles producer index higher by 4 or more than consumer
 * index in the configured cycles number
 */
#define OOB_TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER 0x0158
#define OOB_TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER__LENGTH 0x0001

#define OOB_TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER__TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER_SHIFT 0
#define OOB_TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER__TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER_WIDTH 32
#define OOB_TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER__TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER_RESET_VAL 0
#define OOB_TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER__TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER_RMASK 0xffffffff
#define OOB_TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER__TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER_MASK  0xffffffff
#define OOB_TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER__TX_PRODUCER_HIGHER_BY_4_OR_MORE_THAN_CONSUMER_COUNTER_FIELD 0,31


/*
 * TX wq raddr not ready after valid counter cycles number.
 * The number of cycles tx wq raddr not ready after valid in the configured
 * cycles number
 */
#define OOB_TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER 0x0160
#define OOB_TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER__LENGTH 0x0001

#define OOB_TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER_SHIFT 0
#define OOB_TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER_WIDTH 32
#define OOB_TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER_RESET_VAL 0
#define OOB_TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER_RMASK 0xffffffff
#define OOB_TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER_MASK  0xffffffff
#define OOB_TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_WQ_RADDR_NOT_READY_AFTER_VALID_COUNTER_FIELD 0,31


/*
 * TX data raddr not ready after valid counter cycles number.
 * The number of cycles tx data raddr not ready after valid in the configured
 * cycles number
 */
#define OOB_TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER 0x0168
#define OOB_TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER__LENGTH 0x0001

#define OOB_TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER_SHIFT 0
#define OOB_TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER_WIDTH 32
#define OOB_TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER_RESET_VAL 0
#define OOB_TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER_RMASK 0xffffffff
#define OOB_TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER_MASK  0xffffffff
#define OOB_TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER__TX_DATA_RADDR_NOT_READY_AFTER_VALID_COUNTER_FIELD 0,31


/*
 * TX fifo in bytes counter.
 * The number of bytes enter to tx fifo in the configured cycles number
 */
#define OOB_TX_FIFO_IN_BYTES_COUNTER 0x0130
#define OOB_TX_FIFO_IN_BYTES_COUNTER__LENGTH 0x0001

#define OOB_TX_FIFO_IN_BYTES_COUNTER__TX_FIFO_IN_BYTES_COUNTER_SHIFT 0
#define OOB_TX_FIFO_IN_BYTES_COUNTER__TX_FIFO_IN_BYTES_COUNTER_WIDTH 32
#define OOB_TX_FIFO_IN_BYTES_COUNTER__TX_FIFO_IN_BYTES_COUNTER_RESET_VAL 0
#define OOB_TX_FIFO_IN_BYTES_COUNTER__TX_FIFO_IN_BYTES_COUNTER_RMASK 0xffffffff
#define OOB_TX_FIFO_IN_BYTES_COUNTER__TX_FIFO_IN_BYTES_COUNTER_MASK  0xffffffff
#define OOB_TX_FIFO_IN_BYTES_COUNTER__TX_FIFO_IN_BYTES_COUNTER_FIELD 0,31


/*
 * TX fifo in frames counter cycles number.
 * The number of frames enter to tx fifo in the configured cycles number
 */
#define OOB_TX_FIFO_IN_FRAMES_COUNTER 0x0138
#define OOB_TX_FIFO_IN_FRAMES_COUNTER__LENGTH 0x0001

#define OOB_TX_FIFO_IN_FRAMES_COUNTER__TX_FIFO_IN_FRAMES_COUNTER_SHIFT 0
#define OOB_TX_FIFO_IN_FRAMES_COUNTER__TX_FIFO_IN_FRAMES_COUNTER_WIDTH 32
#define OOB_TX_FIFO_IN_FRAMES_COUNTER__TX_FIFO_IN_FRAMES_COUNTER_RESET_VAL 0
#define OOB_TX_FIFO_IN_FRAMES_COUNTER__TX_FIFO_IN_FRAMES_COUNTER_RMASK 0xffffffff
#define OOB_TX_FIFO_IN_FRAMES_COUNTER__TX_FIFO_IN_FRAMES_COUNTER_MASK  0xffffffff
#define OOB_TX_FIFO_IN_FRAMES_COUNTER__TX_FIFO_IN_FRAMES_COUNTER_FIELD 0,31


/*
 * TX fifo out bytes counter.
 * The number of bytes exit from tx fifo in the configured cycles number
 */
#define OOB_TX_FIFO_OUT_BYTES_COUNTER 0x0140
#define OOB_TX_FIFO_OUT_BYTES_COUNTER__LENGTH 0x0001

#define OOB_TX_FIFO_OUT_BYTES_COUNTER__TX_FIFO_OUT_BYTES_COUNTER_SHIFT 0
#define OOB_TX_FIFO_OUT_BYTES_COUNTER__TX_FIFO_OUT_BYTES_COUNTER_WIDTH 32
#define OOB_TX_FIFO_OUT_BYTES_COUNTER__TX_FIFO_OUT_BYTES_COUNTER_RESET_VAL 0
#define OOB_TX_FIFO_OUT_BYTES_COUNTER__TX_FIFO_OUT_BYTES_COUNTER_RMASK 0xffffffff
#define OOB_TX_FIFO_OUT_BYTES_COUNTER__TX_FIFO_OUT_BYTES_COUNTER_MASK  0xffffffff
#define OOB_TX_FIFO_OUT_BYTES_COUNTER__TX_FIFO_OUT_BYTES_COUNTER_FIELD 0,31


/*
 * TX adapter not ready after valid counter cycles number.
 * The number of cycles tx adapter not ready after valid in the configured
 * cycles number
 */
#define OOB_TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER 0x0170
#define OOB_TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER__LENGTH 0x0001

#define OOB_TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER__TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER_SHIFT 0
#define OOB_TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER__TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER_WIDTH 32
#define OOB_TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER__TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER_RESET_VAL 0
#define OOB_TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER__TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER_RMASK 0xffffffff
#define OOB_TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER__TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER_MASK  0xffffffff
#define OOB_TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER__TX_ADAPTER_NOT_READY_AFTER_VALID_COUNTER_FIELD 0,31


/*
 * TX errors Register.
 * This is the errors register.
 */
#define OOB_TX_ERRORS 0x0178
#define OOB_TX_ERRORS__LENGTH 0x0001

#define OOB_TX_ERRORS__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_SHIFT 0
#define OOB_TX_ERRORS__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_WIDTH 1
#define OOB_TX_ERRORS__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_RESET_VAL 0
#define OOB_TX_ERRORS__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_RMASK 0x1
#define OOB_TX_ERRORS__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_MASK  0x1
#define OOB_TX_ERRORS__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_FIELD 0,0

#define OOB_TX_ERRORS__FRAME_SIZE_SMALL_SHIFT 1
#define OOB_TX_ERRORS__FRAME_SIZE_SMALL_WIDTH 1
#define OOB_TX_ERRORS__FRAME_SIZE_SMALL_RESET_VAL 0
#define OOB_TX_ERRORS__FRAME_SIZE_SMALL_RMASK 0x1
#define OOB_TX_ERRORS__FRAME_SIZE_SMALL_MASK  0x2
#define OOB_TX_ERRORS__FRAME_SIZE_SMALL_FIELD 1,1

#define OOB_TX_ERRORS__CHECKSUM_INPUTS_SHIFT 2
#define OOB_TX_ERRORS__CHECKSUM_INPUTS_WIDTH 1
#define OOB_TX_ERRORS__CHECKSUM_INPUTS_RESET_VAL 0
#define OOB_TX_ERRORS__CHECKSUM_INPUTS_RMASK 0x1
#define OOB_TX_ERRORS__CHECKSUM_INPUTS_MASK  0x4
#define OOB_TX_ERRORS__CHECKSUM_INPUTS_FIELD 2,2

#define OOB_TX_ERRORS__WQ_RESPONSE_SHIFT 3
#define OOB_TX_ERRORS__WQ_RESPONSE_WIDTH 2
#define OOB_TX_ERRORS__WQ_RESPONSE_RESET_VAL 0
#define OOB_TX_ERRORS__WQ_RESPONSE_RMASK 0x3
#define OOB_TX_ERRORS__WQ_RESPONSE_MASK  0x18
#define OOB_TX_ERRORS__WQ_RESPONSE_FIELD 3,4

#define OOB_TX_ERRORS__DATA_RESPONSE_SHIFT 5
#define OOB_TX_ERRORS__DATA_RESPONSE_WIDTH 2
#define OOB_TX_ERRORS__DATA_RESPONSE_RESET_VAL 0
#define OOB_TX_ERRORS__DATA_RESPONSE_RMASK 0x3
#define OOB_TX_ERRORS__DATA_RESPONSE_MASK  0x60
#define OOB_TX_ERRORS__DATA_RESPONSE_FIELD 5,6


/*
 * TX errors interrupts enable Register.
 * This is the errors interrupts enable register, decides which errors will
 * cause interrupt.
 */
#define OOB_TX_ERRORS_INT_ENABLE 0x0180
#define OOB_TX_ERRORS_INT_ENABLE__LENGTH 0x0001

#define OOB_TX_ERRORS_INT_ENABLE__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_SHIFT 0
#define OOB_TX_ERRORS_INT_ENABLE__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_WIDTH 1
#define OOB_TX_ERRORS_INT_ENABLE__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_RESET_VAL 1
#define OOB_TX_ERRORS_INT_ENABLE__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_RMASK 0x1
#define OOB_TX_ERRORS_INT_ENABLE__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_MASK  0x1
#define OOB_TX_ERRORS_INT_ENABLE__PI_MINUS_CI_LARGER_THAN_WQ_SIZE_FIELD 0,0

#define OOB_TX_ERRORS_INT_ENABLE__FRAME_SIZE_SMALL_SHIFT 1
#define OOB_TX_ERRORS_INT_ENABLE__FRAME_SIZE_SMALL_WIDTH 1
#define OOB_TX_ERRORS_INT_ENABLE__FRAME_SIZE_SMALL_RESET_VAL 1
#define OOB_TX_ERRORS_INT_ENABLE__FRAME_SIZE_SMALL_RMASK 0x1
#define OOB_TX_ERRORS_INT_ENABLE__FRAME_SIZE_SMALL_MASK  0x2
#define OOB_TX_ERRORS_INT_ENABLE__FRAME_SIZE_SMALL_FIELD 1,1

#define OOB_TX_ERRORS_INT_ENABLE__CHECKSUM_INPUTS_SHIFT 2
#define OOB_TX_ERRORS_INT_ENABLE__CHECKSUM_INPUTS_WIDTH 1
#define OOB_TX_ERRORS_INT_ENABLE__CHECKSUM_INPUTS_RESET_VAL 0
#define OOB_TX_ERRORS_INT_ENABLE__CHECKSUM_INPUTS_RMASK 0x1
#define OOB_TX_ERRORS_INT_ENABLE__CHECKSUM_INPUTS_MASK  0x4
#define OOB_TX_ERRORS_INT_ENABLE__CHECKSUM_INPUTS_FIELD 2,2

#define OOB_TX_ERRORS_INT_ENABLE__WQ_RESPONSE_SHIFT 3
#define OOB_TX_ERRORS_INT_ENABLE__WQ_RESPONSE_WIDTH 1
#define OOB_TX_ERRORS_INT_ENABLE__WQ_RESPONSE_RESET_VAL 1
#define OOB_TX_ERRORS_INT_ENABLE__WQ_RESPONSE_RMASK 0x1
#define OOB_TX_ERRORS_INT_ENABLE__WQ_RESPONSE_MASK  0x8
#define OOB_TX_ERRORS_INT_ENABLE__WQ_RESPONSE_FIELD 3,3

#define OOB_TX_ERRORS_INT_ENABLE__DATA_RESPONSE_SHIFT 4
#define OOB_TX_ERRORS_INT_ENABLE__DATA_RESPONSE_WIDTH 1
#define OOB_TX_ERRORS_INT_ENABLE__DATA_RESPONSE_RESET_VAL 1
#define OOB_TX_ERRORS_INT_ENABLE__DATA_RESPONSE_RMASK 0x1
#define OOB_TX_ERRORS_INT_ENABLE__DATA_RESPONSE_MASK  0x10
#define OOB_TX_ERRORS_INT_ENABLE__DATA_RESPONSE_FIELD 4,4


/*
 * TX status Register.
 * This is the status register.
 */
#define OOB_TX_STATUS 0x0188
#define OOB_TX_STATUS__LENGTH 0x0001

#define OOB_TX_STATUS__DISABLED_SHIFT 0
#define OOB_TX_STATUS__DISABLED_WIDTH 1
#define OOB_TX_STATUS__DISABLED_RESET_VAL 0
#define OOB_TX_STATUS__DISABLED_RMASK 0x1
#define OOB_TX_STATUS__DISABLED_MASK  0x1
#define OOB_TX_STATUS__DISABLED_FIELD 0,0

#define OOB_TX_STATUS__DATA_FIFO_FULL_SHIFT 1
#define OOB_TX_STATUS__DATA_FIFO_FULL_WIDTH 1
#define OOB_TX_STATUS__DATA_FIFO_FULL_RESET_VAL 0
#define OOB_TX_STATUS__DATA_FIFO_FULL_RMASK 0x1
#define OOB_TX_STATUS__DATA_FIFO_FULL_MASK  0x2
#define OOB_TX_STATUS__DATA_FIFO_FULL_FIELD 1,1

#define OOB_TX_STATUS__MAC_FLOW_CONTROL_SHIFT 2
#define OOB_TX_STATUS__MAC_FLOW_CONTROL_WIDTH 1
#define OOB_TX_STATUS__MAC_FLOW_CONTROL_RESET_VAL 0
#define OOB_TX_STATUS__MAC_FLOW_CONTROL_RMASK 0x1
#define OOB_TX_STATUS__MAC_FLOW_CONTROL_MASK  0x4
#define OOB_TX_STATUS__MAC_FLOW_CONTROL_FIELD 2,2

#define OOB_TX_STATUS__COUNTERS_FINISHED_SHIFT 3
#define OOB_TX_STATUS__COUNTERS_FINISHED_WIDTH 1
#define OOB_TX_STATUS__COUNTERS_FINISHED_RESET_VAL 0
#define OOB_TX_STATUS__COUNTERS_FINISHED_RMASK 0x1
#define OOB_TX_STATUS__COUNTERS_FINISHED_MASK  0x8
#define OOB_TX_STATUS__COUNTERS_FINISHED_FIELD 3,3

#define OOB_TX_STATUS__WQ_SIZE_LOG2_OUT_OF_RANGE_SHIFT 4
#define OOB_TX_STATUS__WQ_SIZE_LOG2_OUT_OF_RANGE_WIDTH 1
#define OOB_TX_STATUS__WQ_SIZE_LOG2_OUT_OF_RANGE_RESET_VAL 0
#define OOB_TX_STATUS__WQ_SIZE_LOG2_OUT_OF_RANGE_RMASK 0x1
#define OOB_TX_STATUS__WQ_SIZE_LOG2_OUT_OF_RANGE_MASK  0x10
#define OOB_TX_STATUS__WQ_SIZE_LOG2_OUT_OF_RANGE_FIELD 4,4


/*
 * TX fifos status Register.
 * This is the tx fifos status register.
 */
#define OOB_TX_FIFOS_STATUS 0x0190
#define OOB_TX_FIFOS_STATUS__LENGTH 0x0001

#define OOB_TX_FIFOS_STATUS__WQES_SHIFT 0
#define OOB_TX_FIFOS_STATUS__WQES_WIDTH 8
#define OOB_TX_FIFOS_STATUS__WQES_RESET_VAL 0
#define OOB_TX_FIFOS_STATUS__WQES_RMASK 0xff
#define OOB_TX_FIFOS_STATUS__WQES_MASK  0xff
#define OOB_TX_FIFOS_STATUS__WQES_FIELD 0,7

#define OOB_TX_FIFOS_STATUS__READ_REQUESTS_INFO_SHIFT 8
#define OOB_TX_FIFOS_STATUS__READ_REQUESTS_INFO_WIDTH 5
#define OOB_TX_FIFOS_STATUS__READ_REQUESTS_INFO_RESET_VAL 0
#define OOB_TX_FIFOS_STATUS__READ_REQUESTS_INFO_RMASK 0x1f
#define OOB_TX_FIFOS_STATUS__READ_REQUESTS_INFO_MASK  0x1f00
#define OOB_TX_FIFOS_STATUS__READ_REQUESTS_INFO_FIELD 8,12

#define OOB_TX_FIFOS_STATUS__DATA_SHIFT 13
#define OOB_TX_FIFOS_STATUS__DATA_WIDTH 11
#define OOB_TX_FIFOS_STATUS__DATA_RESET_VAL 0
#define OOB_TX_FIFOS_STATUS__DATA_RMASK 0x7ff
#define OOB_TX_FIFOS_STATUS__DATA_MASK  0xffe000
#define OOB_TX_FIFOS_STATUS__DATA_FIELD 13,23

#define OOB_TX_FIFOS_STATUS__CHECKSUM_INFO_SHIFT 24
#define OOB_TX_FIFOS_STATUS__CHECKSUM_INFO_WIDTH 8
#define OOB_TX_FIFOS_STATUS__CHECKSUM_INFO_RESET_VAL 0
#define OOB_TX_FIFOS_STATUS__CHECKSUM_INFO_RMASK 0xff
#define OOB_TX_FIFOS_STATUS__CHECKSUM_INFO_MASK  0xff000000
#define OOB_TX_FIFOS_STATUS__CHECKSUM_INFO_FIELD 24,31

#define OOB_TX_FIFOS_STATUS__CHECKSUM_RESULT_SHIFT 32
#define OOB_TX_FIFOS_STATUS__CHECKSUM_RESULT_WIDTH 9
#define OOB_TX_FIFOS_STATUS__CHECKSUM_RESULT_RESET_VAL 0
#define OOB_TX_FIFOS_STATUS__CHECKSUM_RESULT_RMASK 0x1ff
#define OOB_TX_FIFOS_STATUS__CHECKSUM_RESULT_MASK  _64bit(0x1ff00000000)
#define OOB_TX_FIFOS_STATUS__CHECKSUM_RESULT_FIELD 32,40


/*
 * TX debug Register.
 * This is register for debug purpose.
 */
#define OOB_TX_DEBUG 0x0198
#define OOB_TX_DEBUG__LENGTH 0x0001

#define OOB_TX_DEBUG__NO_DISABLE_SHIFT 0
#define OOB_TX_DEBUG__NO_DISABLE_WIDTH 1
#define OOB_TX_DEBUG__NO_DISABLE_RESET_VAL 0
#define OOB_TX_DEBUG__NO_DISABLE_RMASK 0x1
#define OOB_TX_DEBUG__NO_DISABLE_MASK  0x1
#define OOB_TX_DEBUG__NO_DISABLE_FIELD 0,0


/*
 * TX consumer index update address.
 * The address of the tx consumer index update
 */
#define OOB_TX_CONSUMER_INDEX_UPDATE_ADDRESS 0x01a0
#define OOB_TX_CONSUMER_INDEX_UPDATE_ADDRESS__LENGTH 0x0001

#define OOB_TX_CONSUMER_INDEX_UPDATE_ADDRESS__TX_CONSUMER_INDEX_UPDATE_ADDRESS_SHIFT 6
#define OOB_TX_CONSUMER_INDEX_UPDATE_ADDRESS__TX_CONSUMER_INDEX_UPDATE_ADDRESS_WIDTH 34
#define OOB_TX_CONSUMER_INDEX_UPDATE_ADDRESS__TX_CONSUMER_INDEX_UPDATE_ADDRESS_RESET_VAL 0
#define OOB_TX_CONSUMER_INDEX_UPDATE_ADDRESS__TX_CONSUMER_INDEX_UPDATE_ADDRESS_RMASK _64bit(0x3ffffffff)
#define OOB_TX_CONSUMER_INDEX_UPDATE_ADDRESS__TX_CONSUMER_INDEX_UPDATE_ADDRESS_MASK  _64bit(0xffffffffc0)
#define OOB_TX_CONSUMER_INDEX_UPDATE_ADDRESS__TX_CONSUMER_INDEX_UPDATE_ADDRESS_FIELD 6,39


/*
 * MAC id allowed to insert to device.
 * which mac id's to insert into the oob rx path
 */
#define OOB_RX_MAC_FILTER__FIRST_WORD 0x0300
#define OOB_RX_MAC_FILTER__LAST_WORD 0x0318
#define OOB_RX_MAC_FILTER__LENGTH 0x0020
#define OOB_RX_MAC_FILTER__STRIDE 0x0008

#define OOB_RX_MAC_FILTER__ID_SHIFT 0
#define OOB_RX_MAC_FILTER__ID_WIDTH 48
#define OOB_RX_MAC_FILTER__ID_RESET_VAL 0
#define OOB_RX_MAC_FILTER__ID_RMASK _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER__ID_MASK  _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER__ID_FIELD 0,47

#define OOB_RX_MAC_FILTER__EN_SHIFT 48
#define OOB_RX_MAC_FILTER__EN_WIDTH 1
#define OOB_RX_MAC_FILTER__EN_RESET_VAL 0
#define OOB_RX_MAC_FILTER__EN_RMASK 0x1
#define OOB_RX_MAC_FILTER__EN_MASK  _64bit(0x1000000000000)
#define OOB_RX_MAC_FILTER__EN_FIELD 48,48


/*
 * MAC id allowed to insert to device.
 * which mac id's to insert into the oob rx path
 */
#define OOB_RX_MAC_FILTER_1__FIRST_WORD 0x0308
#define OOB_RX_MAC_FILTER_1__LAST_WORD 0x0320
#define OOB_RX_MAC_FILTER_1__LENGTH 0x0020
#define OOB_RX_MAC_FILTER_1__STRIDE 0x0008

#define OOB_RX_MAC_FILTER_1__ID_SHIFT 0
#define OOB_RX_MAC_FILTER_1__ID_WIDTH 48
#define OOB_RX_MAC_FILTER_1__ID_RESET_VAL 0
#define OOB_RX_MAC_FILTER_1__ID_RMASK _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_1__ID_MASK  _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_1__ID_FIELD 0,47

#define OOB_RX_MAC_FILTER_1__EN_SHIFT 48
#define OOB_RX_MAC_FILTER_1__EN_WIDTH 1
#define OOB_RX_MAC_FILTER_1__EN_RESET_VAL 0
#define OOB_RX_MAC_FILTER_1__EN_RMASK 0x1
#define OOB_RX_MAC_FILTER_1__EN_MASK  _64bit(0x1000000000000)
#define OOB_RX_MAC_FILTER_1__EN_FIELD 48,48


/*
 * MAC id allowed to insert to device.
 * which mac id's to insert into the oob rx path
 */
#define OOB_RX_MAC_FILTER_2__FIRST_WORD 0x0310
#define OOB_RX_MAC_FILTER_2__LAST_WORD 0x0328
#define OOB_RX_MAC_FILTER_2__LENGTH 0x0020
#define OOB_RX_MAC_FILTER_2__STRIDE 0x0008

#define OOB_RX_MAC_FILTER_2__ID_SHIFT 0
#define OOB_RX_MAC_FILTER_2__ID_WIDTH 48
#define OOB_RX_MAC_FILTER_2__ID_RESET_VAL 0
#define OOB_RX_MAC_FILTER_2__ID_RMASK _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_2__ID_MASK  _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_2__ID_FIELD 0,47

#define OOB_RX_MAC_FILTER_2__EN_SHIFT 48
#define OOB_RX_MAC_FILTER_2__EN_WIDTH 1
#define OOB_RX_MAC_FILTER_2__EN_RESET_VAL 0
#define OOB_RX_MAC_FILTER_2__EN_RMASK 0x1
#define OOB_RX_MAC_FILTER_2__EN_MASK  _64bit(0x1000000000000)
#define OOB_RX_MAC_FILTER_2__EN_FIELD 48,48


/*
 * MAC id allowed to insert to device.
 * which mac id's to insert into the oob rx path
 */
#define OOB_RX_MAC_FILTER_3__FIRST_WORD 0x0318
#define OOB_RX_MAC_FILTER_3__LAST_WORD 0x0330
#define OOB_RX_MAC_FILTER_3__LENGTH 0x0020
#define OOB_RX_MAC_FILTER_3__STRIDE 0x0008

#define OOB_RX_MAC_FILTER_3__ID_SHIFT 0
#define OOB_RX_MAC_FILTER_3__ID_WIDTH 48
#define OOB_RX_MAC_FILTER_3__ID_RESET_VAL 0
#define OOB_RX_MAC_FILTER_3__ID_RMASK _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_3__ID_MASK  _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_3__ID_FIELD 0,47

#define OOB_RX_MAC_FILTER_3__EN_SHIFT 48
#define OOB_RX_MAC_FILTER_3__EN_WIDTH 1
#define OOB_RX_MAC_FILTER_3__EN_RESET_VAL 0
#define OOB_RX_MAC_FILTER_3__EN_RMASK 0x1
#define OOB_RX_MAC_FILTER_3__EN_MASK  _64bit(0x1000000000000)
#define OOB_RX_MAC_FILTER_3__EN_FIELD 48,48


/*
 * Filter by DMAC ranges configurations.
 * set of registers that define the range of dmac id's
 */
#define OOB_RX_MAC_FILTER_DMAC_RANGE_START 0x0220
#define OOB_RX_MAC_FILTER_DMAC_RANGE_START__LENGTH 0x0001

#define OOB_RX_MAC_FILTER_DMAC_RANGE_START__RX_MAC_FILTER_DMAC_RANGE_START_SHIFT 0
#define OOB_RX_MAC_FILTER_DMAC_RANGE_START__RX_MAC_FILTER_DMAC_RANGE_START_WIDTH 48
#define OOB_RX_MAC_FILTER_DMAC_RANGE_START__RX_MAC_FILTER_DMAC_RANGE_START_RESET_VAL 0
#define OOB_RX_MAC_FILTER_DMAC_RANGE_START__RX_MAC_FILTER_DMAC_RANGE_START_RMASK _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_DMAC_RANGE_START__RX_MAC_FILTER_DMAC_RANGE_START_MASK  _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_DMAC_RANGE_START__RX_MAC_FILTER_DMAC_RANGE_START_FIELD 0,47


/*
 * Filter by DMAC ranges configurations.
 * set of registers that define the range of dmac id's
 */
#define OOB_RX_MAC_FILTER_DMAC_RANGE_END 0x0228
#define OOB_RX_MAC_FILTER_DMAC_RANGE_END__LENGTH 0x0001

#define OOB_RX_MAC_FILTER_DMAC_RANGE_END__RX_MAC_FILTER_DMAC_RANGE_END_SHIFT 0
#define OOB_RX_MAC_FILTER_DMAC_RANGE_END__RX_MAC_FILTER_DMAC_RANGE_END_WIDTH 48
#define OOB_RX_MAC_FILTER_DMAC_RANGE_END__RX_MAC_FILTER_DMAC_RANGE_END_RESET_VAL 0
#define OOB_RX_MAC_FILTER_DMAC_RANGE_END__RX_MAC_FILTER_DMAC_RANGE_END_RMASK _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_DMAC_RANGE_END__RX_MAC_FILTER_DMAC_RANGE_END_MASK  _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_DMAC_RANGE_END__RX_MAC_FILTER_DMAC_RANGE_END_FIELD 0,47


/*
 * Filter by DMAC configurations.
 * set of registers that define rx filtering
 */
#define OOB_RX_MAC_FILTER_GENERAL 0x0230
#define OOB_RX_MAC_FILTER_GENERAL__LENGTH 0x0001

#define OOB_RX_MAC_FILTER_GENERAL__EN_RANGE_SHIFT 0
#define OOB_RX_MAC_FILTER_GENERAL__EN_RANGE_WIDTH 1
#define OOB_RX_MAC_FILTER_GENERAL__EN_RANGE_RESET_VAL 0
#define OOB_RX_MAC_FILTER_GENERAL__EN_RANGE_RMASK 0x1
#define OOB_RX_MAC_FILTER_GENERAL__EN_RANGE_MASK  0x1
#define OOB_RX_MAC_FILTER_GENERAL__EN_RANGE_FIELD 0,0

#define OOB_RX_MAC_FILTER_GENERAL__EN_MULTICAST_SHIFT 1
#define OOB_RX_MAC_FILTER_GENERAL__EN_MULTICAST_WIDTH 1
#define OOB_RX_MAC_FILTER_GENERAL__EN_MULTICAST_RESET_VAL 0
#define OOB_RX_MAC_FILTER_GENERAL__EN_MULTICAST_RMASK 0x1
#define OOB_RX_MAC_FILTER_GENERAL__EN_MULTICAST_MASK  0x2
#define OOB_RX_MAC_FILTER_GENERAL__EN_MULTICAST_FIELD 1,1


/*
 * counting configuration in case of discard.
 * which cases to count in case of discard event at the rx filter
 */
#define OOB_RX_MAC_FILTER_COUNT_DISC 0x0238
#define OOB_RX_MAC_FILTER_COUNT_DISC__LENGTH 0x0001

#define OOB_RX_MAC_FILTER_COUNT_DISC__EN_SHIFT 0
#define OOB_RX_MAC_FILTER_COUNT_DISC__EN_WIDTH 1
#define OOB_RX_MAC_FILTER_COUNT_DISC__EN_RESET_VAL 0
#define OOB_RX_MAC_FILTER_COUNT_DISC__EN_RMASK 0x1
#define OOB_RX_MAC_FILTER_COUNT_DISC__EN_MASK  0x1
#define OOB_RX_MAC_FILTER_COUNT_DISC__EN_FIELD 0,0

#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_EN_SHIFT 1
#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_EN_WIDTH 1
#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_EN_RESET_VAL 0
#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_EN_RMASK 0x1
#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_EN_MASK  0x2
#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_EN_FIELD 1,1

#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_ID_SHIFT 4
#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_ID_WIDTH 48
#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_ID_RESET_VAL 0
#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_ID_RMASK _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_ID_MASK  _64bit(0xffffffffffff0)
#define OOB_RX_MAC_FILTER_COUNT_DISC__DMAC_ID_FIELD 4,51


/*
 * counting configuration in case of pass.
 * which cases to count in case of pass event at the rx filter
 */
#define OOB_RX_MAC_FILTER_COUNT_PASS 0x0240
#define OOB_RX_MAC_FILTER_COUNT_PASS__LENGTH 0x0001

#define OOB_RX_MAC_FILTER_COUNT_PASS__EN_SHIFT 0
#define OOB_RX_MAC_FILTER_COUNT_PASS__EN_WIDTH 1
#define OOB_RX_MAC_FILTER_COUNT_PASS__EN_RESET_VAL 0
#define OOB_RX_MAC_FILTER_COUNT_PASS__EN_RMASK 0x1
#define OOB_RX_MAC_FILTER_COUNT_PASS__EN_MASK  0x1
#define OOB_RX_MAC_FILTER_COUNT_PASS__EN_FIELD 0,0

#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_EN_SHIFT 1
#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_EN_WIDTH 1
#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_EN_RESET_VAL 0
#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_EN_RMASK 0x1
#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_EN_MASK  0x2
#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_EN_FIELD 1,1

#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_ID_SHIFT 4
#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_ID_WIDTH 48
#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_ID_RESET_VAL 0
#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_ID_RMASK _64bit(0xffffffffffff)
#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_ID_MASK  _64bit(0xffffffffffff0)
#define OOB_RX_MAC_FILTER_COUNT_PASS__DMAC_ID_FIELD 4,51


/*
 * counting all the pass packets through the RX filter.
 * count all the pass (not a specific DMAC)
 */
#define OOB_RX_MAC_FILTER_PASS_COUNTER_ALL 0x0248
#define OOB_RX_MAC_FILTER_PASS_COUNTER_ALL__LENGTH 0x0001

#define OOB_RX_MAC_FILTER_PASS_COUNTER_ALL__RX_MAC_FILTER_PASS_COUNTER_ALL_SHIFT 0
#define OOB_RX_MAC_FILTER_PASS_COUNTER_ALL__RX_MAC_FILTER_PASS_COUNTER_ALL_WIDTH 64
#define OOB_RX_MAC_FILTER_PASS_COUNTER_ALL__RX_MAC_FILTER_PASS_COUNTER_ALL_RESET_VAL 0
#define OOB_RX_MAC_FILTER_PASS_COUNTER_ALL__RX_MAC_FILTER_PASS_COUNTER_ALL_RMASK _64bit(0xffffffffffffffff)
#define OOB_RX_MAC_FILTER_PASS_COUNTER_ALL__RX_MAC_FILTER_PASS_COUNTER_ALL_MASK  _64bit(0xffffffffffffffff)
#define OOB_RX_MAC_FILTER_PASS_COUNTER_ALL__RX_MAC_FILTER_PASS_COUNTER_ALL_FIELD 0,63


/*
 * counting all the pass packets through the RX filter.
 * according to a specific DMAC ID from the configuration
 */
#define OOB_RX_MAC_FILTER_PASS_COUNTER_DMACID 0x0250
#define OOB_RX_MAC_FILTER_PASS_COUNTER_DMACID__LENGTH 0x0001

#define OOB_RX_MAC_FILTER_PASS_COUNTER_DMACID__RX_MAC_FILTER_PASS_COUNTER_DMACID_SHIFT 0
#define OOB_RX_MAC_FILTER_PASS_COUNTER_DMACID__RX_MAC_FILTER_PASS_COUNTER_DMACID_WIDTH 64
#define OOB_RX_MAC_FILTER_PASS_COUNTER_DMACID__RX_MAC_FILTER_PASS_COUNTER_DMACID_RESET_VAL 0
#define OOB_RX_MAC_FILTER_PASS_COUNTER_DMACID__RX_MAC_FILTER_PASS_COUNTER_DMACID_RMASK _64bit(0xffffffffffffffff)
#define OOB_RX_MAC_FILTER_PASS_COUNTER_DMACID__RX_MAC_FILTER_PASS_COUNTER_DMACID_MASK  _64bit(0xffffffffffffffff)
#define OOB_RX_MAC_FILTER_PASS_COUNTER_DMACID__RX_MAC_FILTER_PASS_COUNTER_DMACID_FIELD 0,63


/*
 * counting all the disc packets through the RX filter.
 * count all the disc (not a specific DMAC)
 */
#define OOB_RX_MAC_FILTER_DISC_COUNTER_ALL 0x0258
#define OOB_RX_MAC_FILTER_DISC_COUNTER_ALL__LENGTH 0x0001

#define OOB_RX_MAC_FILTER_DISC_COUNTER_ALL__RX_MAC_FILTER_DISC_COUNTER_ALL_SHIFT 0
#define OOB_RX_MAC_FILTER_DISC_COUNTER_ALL__RX_MAC_FILTER_DISC_COUNTER_ALL_WIDTH 64
#define OOB_RX_MAC_FILTER_DISC_COUNTER_ALL__RX_MAC_FILTER_DISC_COUNTER_ALL_RESET_VAL 0
#define OOB_RX_MAC_FILTER_DISC_COUNTER_ALL__RX_MAC_FILTER_DISC_COUNTER_ALL_RMASK _64bit(0xffffffffffffffff)
#define OOB_RX_MAC_FILTER_DISC_COUNTER_ALL__RX_MAC_FILTER_DISC_COUNTER_ALL_MASK  _64bit(0xffffffffffffffff)
#define OOB_RX_MAC_FILTER_DISC_COUNTER_ALL__RX_MAC_FILTER_DISC_COUNTER_ALL_FIELD 0,63


/*
 * counting all the disc packets through the RX filter.
 * according to a specific DMAC ID from the configuration
 */
#define OOB_RX_MAC_FILTER_DISC_COUNTER_DMACID 0x0260
#define OOB_RX_MAC_FILTER_DISC_COUNTER_DMACID__LENGTH 0x0001

#define OOB_RX_MAC_FILTER_DISC_COUNTER_DMACID__RX_MAC_FILTER_DISC_COUNTER_DMACID_SHIFT 0
#define OOB_RX_MAC_FILTER_DISC_COUNTER_DMACID__RX_MAC_FILTER_DISC_COUNTER_DMACID_WIDTH 64
#define OOB_RX_MAC_FILTER_DISC_COUNTER_DMACID__RX_MAC_FILTER_DISC_COUNTER_DMACID_RESET_VAL 0
#define OOB_RX_MAC_FILTER_DISC_COUNTER_DMACID__RX_MAC_FILTER_DISC_COUNTER_DMACID_RMASK _64bit(0xffffffffffffffff)
#define OOB_RX_MAC_FILTER_DISC_COUNTER_DMACID__RX_MAC_FILTER_DISC_COUNTER_DMACID_MASK  _64bit(0xffffffffffffffff)
#define OOB_RX_MAC_FILTER_DISC_COUNTER_DMACID__RX_MAC_FILTER_DISC_COUNTER_DMACID_FIELD 0,63


/*
 * global rx configuration.
 * collection of rx configuration
 */
#define OOB_RX 0x0268
#define OOB_RX__LENGTH 0x0001

#define OOB_RX__LITEND_SWITCH_SHIFT 0
#define OOB_RX__LITEND_SWITCH_WIDTH 1
#define OOB_RX__LITEND_SWITCH_RESET_VAL 1
#define OOB_RX__LITEND_SWITCH_RMASK 0x1
#define OOB_RX__LITEND_SWITCH_MASK  0x1
#define OOB_RX__LITEND_SWITCH_FIELD 0,0

#define OOB_RX__STRIP_CRC_EN_SHIFT 1
#define OOB_RX__STRIP_CRC_EN_WIDTH 1
#define OOB_RX__STRIP_CRC_EN_RESET_VAL 0
#define OOB_RX__STRIP_CRC_EN_RMASK 0x1
#define OOB_RX__STRIP_CRC_EN_MASK  0x2
#define OOB_RX__STRIP_CRC_EN_FIELD 1,1

#define OOB_RX__CRC_SIZE_SHIFT 4
#define OOB_RX__CRC_SIZE_WIDTH 4
#define OOB_RX__CRC_SIZE_RESET_VAL 4
#define OOB_RX__CRC_SIZE_RMASK 0xf
#define OOB_RX__CRC_SIZE_MASK  0xf0
#define OOB_RX__CRC_SIZE_FIELD 4,7


/*
 * counting configuration in case of pass.
 * which cases to count in case of pass event at the rx filter
 */
#define OOB_RX_MAC_FC_TH 0x02d8
#define OOB_RX_MAC_FC_TH__LENGTH 0x0001

#define OOB_RX_MAC_FC_TH__LOW_SHIFT 0
#define OOB_RX_MAC_FC_TH__LOW_WIDTH 13
#define OOB_RX_MAC_FC_TH__LOW_RESET_VAL 1792
#define OOB_RX_MAC_FC_TH__LOW_RMASK 0x1fff
#define OOB_RX_MAC_FC_TH__LOW_MASK  0x1fff
#define OOB_RX_MAC_FC_TH__LOW_FIELD 0,12

#define OOB_RX_MAC_FC_TH__HIGH_SHIFT 16
#define OOB_RX_MAC_FC_TH__HIGH_WIDTH 13
#define OOB_RX_MAC_FC_TH__HIGH_RESET_VAL 2560
#define OOB_RX_MAC_FC_TH__HIGH_RMASK 0x1fff
#define OOB_RX_MAC_FC_TH__HIGH_MASK  0x1fff0000
#define OOB_RX_MAC_FC_TH__HIGH_FIELD 16,28


/*
 * in stage buffering configuration.
 * which cases to count in case of pass event at the rx filter
 */
#define OOB_RX_BUFFER_IN 0x0288
#define OOB_RX_BUFFER_IN__LENGTH 0x0001

#define OOB_RX_BUFFER_IN__MAX_FULLNESS_AT_SOP_SHIFT 0
#define OOB_RX_BUFFER_IN__MAX_FULLNESS_AT_SOP_WIDTH 13
#define OOB_RX_BUFFER_IN__MAX_FULLNESS_AT_SOP_RESET_VAL 3000
#define OOB_RX_BUFFER_IN__MAX_FULLNESS_AT_SOP_RMASK 0x1fff
#define OOB_RX_BUFFER_IN__MAX_FULLNESS_AT_SOP_MASK  0x1fff
#define OOB_RX_BUFFER_IN__MAX_FULLNESS_AT_SOP_FIELD 0,12

#define OOB_RX_BUFFER_IN__MAX_FRAMENUM_AT_SOP_SHIFT 16
#define OOB_RX_BUFFER_IN__MAX_FRAMENUM_AT_SOP_WIDTH 11
#define OOB_RX_BUFFER_IN__MAX_FRAMENUM_AT_SOP_RESET_VAL 784
#define OOB_RX_BUFFER_IN__MAX_FRAMENUM_AT_SOP_RMASK 0x7ff
#define OOB_RX_BUFFER_IN__MAX_FRAMENUM_AT_SOP_MASK  0x7ff0000
#define OOB_RX_BUFFER_IN__MAX_FRAMENUM_AT_SOP_FIELD 16,26

#define OOB_RX_BUFFER_IN__DISC_ERR_TRN_SHIFT 32
#define OOB_RX_BUFFER_IN__DISC_ERR_TRN_WIDTH 1
#define OOB_RX_BUFFER_IN__DISC_ERR_TRN_RESET_VAL 0
#define OOB_RX_BUFFER_IN__DISC_ERR_TRN_RMASK 0x1
#define OOB_RX_BUFFER_IN__DISC_ERR_TRN_MASK  _64bit(0x100000000)
#define OOB_RX_BUFFER_IN__DISC_ERR_TRN_FIELD 32,32

#define OOB_RX_BUFFER_IN__DISC_ERR_MAC_SHIFT 33
#define OOB_RX_BUFFER_IN__DISC_ERR_MAC_WIDTH 1
#define OOB_RX_BUFFER_IN__DISC_ERR_MAC_RESET_VAL 0
#define OOB_RX_BUFFER_IN__DISC_ERR_MAC_RMASK 0x1
#define OOB_RX_BUFFER_IN__DISC_ERR_MAC_MASK  _64bit(0x200000000)
#define OOB_RX_BUFFER_IN__DISC_ERR_MAC_FIELD 33,33

#define OOB_RX_BUFFER_IN__DISC_PACKET_TOO_LARGE_SHIFT 34
#define OOB_RX_BUFFER_IN__DISC_PACKET_TOO_LARGE_WIDTH 1
#define OOB_RX_BUFFER_IN__DISC_PACKET_TOO_LARGE_RESET_VAL 0
#define OOB_RX_BUFFER_IN__DISC_PACKET_TOO_LARGE_RMASK 0x1
#define OOB_RX_BUFFER_IN__DISC_PACKET_TOO_LARGE_MASK  _64bit(0x400000000)
#define OOB_RX_BUFFER_IN__DISC_PACKET_TOO_LARGE_FIELD 34,34

#define OOB_RX_BUFFER_IN__TRN_PACKET_TOO_LARGE_SHIFT 35
#define OOB_RX_BUFFER_IN__TRN_PACKET_TOO_LARGE_WIDTH 1
#define OOB_RX_BUFFER_IN__TRN_PACKET_TOO_LARGE_RESET_VAL 1
#define OOB_RX_BUFFER_IN__TRN_PACKET_TOO_LARGE_RMASK 0x1
#define OOB_RX_BUFFER_IN__TRN_PACKET_TOO_LARGE_MASK  _64bit(0x800000000)
#define OOB_RX_BUFFER_IN__TRN_PACKET_TOO_LARGE_FIELD 35,35

#define OOB_RX_BUFFER_IN__MAX_PACKET_SIZE_SHIFT 40
#define OOB_RX_BUFFER_IN__MAX_PACKET_SIZE_WIDTH 14
#define OOB_RX_BUFFER_IN__MAX_PACKET_SIZE_RESET_VAL 8192
#define OOB_RX_BUFFER_IN__MAX_PACKET_SIZE_RMASK 0x3fff
#define OOB_RX_BUFFER_IN__MAX_PACKET_SIZE_MASK  _64bit(0x3fff0000000000)
#define OOB_RX_BUFFER_IN__MAX_PACKET_SIZE_FIELD 40,53


/*
 * DMA configurations.
 * collection of
 */
#define OOB_RX_DMA 0x0270
#define OOB_RX_DMA__LENGTH 0x0001

#define OOB_RX_DMA__EN_SHIFT 0
#define OOB_RX_DMA__EN_WIDTH 1
#define OOB_RX_DMA__EN_RESET_VAL 0
#define OOB_RX_DMA__EN_RMASK 0x1
#define OOB_RX_DMA__EN_MASK  0x1
#define OOB_RX_DMA__EN_FIELD 0,0

#define OOB_RX_DMA__WQE_PAGE_SIZE_SHIFT 1
#define OOB_RX_DMA__WQE_PAGE_SIZE_WIDTH 1
#define OOB_RX_DMA__WQE_PAGE_SIZE_RESET_VAL 0
#define OOB_RX_DMA__WQE_PAGE_SIZE_RMASK 0x1
#define OOB_RX_DMA__WQE_PAGE_SIZE_MASK  0x2
#define OOB_RX_DMA__WQE_PAGE_SIZE_FIELD 1,1

#define OOB_RX_DMA__SOP_IN_NEW_CACHE_LINE_SHIFT 4
#define OOB_RX_DMA__SOP_IN_NEW_CACHE_LINE_WIDTH 1
#define OOB_RX_DMA__SOP_IN_NEW_CACHE_LINE_RESET_VAL 0
#define OOB_RX_DMA__SOP_IN_NEW_CACHE_LINE_RMASK 0x1
#define OOB_RX_DMA__SOP_IN_NEW_CACHE_LINE_MASK  0x10
#define OOB_RX_DMA__SOP_IN_NEW_CACHE_LINE_FIELD 4,4

#define OOB_RX_DMA__MAX_OTF_WR_SHIFT 8
#define OOB_RX_DMA__MAX_OTF_WR_WIDTH 15
#define OOB_RX_DMA__MAX_OTF_WR_RESET_VAL 240
#define OOB_RX_DMA__MAX_OTF_WR_RMASK 0x7fff
#define OOB_RX_DMA__MAX_OTF_WR_MASK  0x7fff00
#define OOB_RX_DMA__MAX_OTF_WR_FIELD 8,22

#define OOB_RX_DMA__CQE_AGGR_TIMER_SHIFT 24
#define OOB_RX_DMA__CQE_AGGR_TIMER_WIDTH 8
#define OOB_RX_DMA__CQE_AGGR_TIMER_RESET_VAL 4
#define OOB_RX_DMA__CQE_AGGR_TIMER_RMASK 0xff
#define OOB_RX_DMA__CQE_AGGR_TIMER_MASK  0xff000000
#define OOB_RX_DMA__CQE_AGGR_TIMER_FIELD 24,31


/*
 * wqe producer index supplied by SW.
 * indicates in wrapping mode the last aloocated wqe page index
 */
#define OOB_RX_WQE_PAGE_PI 0x0290
#define OOB_RX_WQE_PAGE_PI__LENGTH 0x0001

#define OOB_RX_WQE_PAGE_PI__RX_WQE_PAGE_PI_SHIFT 0
#define OOB_RX_WQE_PAGE_PI__RX_WQE_PAGE_PI_WIDTH 16
#define OOB_RX_WQE_PAGE_PI__RX_WQE_PAGE_PI_RESET_VAL 0
#define OOB_RX_WQE_PAGE_PI__RX_WQE_PAGE_PI_RMASK 0xffff
#define OOB_RX_WQE_PAGE_PI__RX_WQE_PAGE_PI_MASK  0xffff
#define OOB_RX_WQE_PAGE_PI__RX_WQE_PAGE_PI_FIELD 0,15


/*
 * wqe consumer supplied by by HW.
 * indicates in wrapping mode the last used WQE
 */
#define OOB_RX_WQE_PAGE_ALLOC_CI 0x02a0
#define OOB_RX_WQE_PAGE_ALLOC_CI__LENGTH 0x0001

#define OOB_RX_WQE_PAGE_ALLOC_CI__RX_WQE_PAGE_ALLOC_CI_SHIFT 0
#define OOB_RX_WQE_PAGE_ALLOC_CI__RX_WQE_PAGE_ALLOC_CI_WIDTH 16
#define OOB_RX_WQE_PAGE_ALLOC_CI__RX_WQE_PAGE_ALLOC_CI_RESET_VAL 0
#define OOB_RX_WQE_PAGE_ALLOC_CI__RX_WQE_PAGE_ALLOC_CI_RMASK 0xffff
#define OOB_RX_WQE_PAGE_ALLOC_CI__RX_WQE_PAGE_ALLOC_CI_MASK  0xffff
#define OOB_RX_WQE_PAGE_ALLOC_CI__RX_WQE_PAGE_ALLOC_CI_FIELD 0,15


/*
 * wqe consumer supplied by by HW.
 * indicates in wrapping mode the last used WQE
 */
#define OOB_RX_WQE_PAGE_USED_CI 0x02a8
#define OOB_RX_WQE_PAGE_USED_CI__LENGTH 0x0001

#define OOB_RX_WQE_PAGE_USED_CI__RX_WQE_PAGE_USED_CI_SHIFT 0
#define OOB_RX_WQE_PAGE_USED_CI__RX_WQE_PAGE_USED_CI_WIDTH 16
#define OOB_RX_WQE_PAGE_USED_CI__RX_WQE_PAGE_USED_CI_RESET_VAL 0
#define OOB_RX_WQE_PAGE_USED_CI__RX_WQE_PAGE_USED_CI_RMASK 0xffff
#define OOB_RX_WQE_PAGE_USED_CI__RX_WQE_PAGE_USED_CI_MASK  0xffff
#define OOB_RX_WQE_PAGE_USED_CI__RX_WQE_PAGE_USED_CI_FIELD 0,15


/*
 * cqe consumer supplied by by HW - per ready packet on memory.
 * indicates in wrapping mode the last written CQE
 */
#define OOB_RX_CQE_PACKET_CI 0x02c0
#define OOB_RX_CQE_PACKET_CI__LENGTH 0x0001

#define OOB_RX_CQE_PACKET_CI__RX_CQE_PACKET_CI_SHIFT 0
#define OOB_RX_CQE_PACKET_CI__RX_CQE_PACKET_CI_WIDTH 64
#define OOB_RX_CQE_PACKET_CI__RX_CQE_PACKET_CI_RESET_VAL 0
#define OOB_RX_CQE_PACKET_CI__RX_CQE_PACKET_CI_RMASK _64bit(0xffffffffffffffff)
#define OOB_RX_CQE_PACKET_CI__RX_CQE_PACKET_CI_MASK  _64bit(0xffffffffffffffff)
#define OOB_RX_CQE_PACKET_CI__RX_CQE_PACKET_CI_FIELD 0,63


/*
 * accumulative CQE wr sent to axi (counter inc before response is back).
 * how much cqes was sent to write (not finished the write!)
 */
#define OOB_RX_CQE_USED_CNTR 0x02b0
#define OOB_RX_CQE_USED_CNTR__LENGTH 0x0001

#define OOB_RX_CQE_USED_CNTR__RX_CQE_USED_CNTR_SHIFT 0
#define OOB_RX_CQE_USED_CNTR__RX_CQE_USED_CNTR_WIDTH 64
#define OOB_RX_CQE_USED_CNTR__RX_CQE_USED_CNTR_RESET_VAL 0
#define OOB_RX_CQE_USED_CNTR__RX_CQE_USED_CNTR_RMASK _64bit(0xffffffffffffffff)
#define OOB_RX_CQE_USED_CNTR__RX_CQE_USED_CNTR_MASK  _64bit(0xffffffffffffffff)
#define OOB_RX_CQE_USED_CNTR__RX_CQE_USED_CNTR_FIELD 0,63


/*
 * cqe wr transaction counter.
 * how much cqes wr transactions generated to axi CQE IF
 */
#define OOB_RX_CQE_TRANS_CNTR 0x02b8
#define OOB_RX_CQE_TRANS_CNTR__LENGTH 0x0001

#define OOB_RX_CQE_TRANS_CNTR__RX_CQE_TRANS_CNTR_SHIFT 0
#define OOB_RX_CQE_TRANS_CNTR__RX_CQE_TRANS_CNTR_WIDTH 64
#define OOB_RX_CQE_TRANS_CNTR__RX_CQE_TRANS_CNTR_RESET_VAL 0
#define OOB_RX_CQE_TRANS_CNTR__RX_CQE_TRANS_CNTR_RMASK _64bit(0xffffffffffffffff)
#define OOB_RX_CQE_TRANS_CNTR__RX_CQE_TRANS_CNTR_MASK  _64bit(0xffffffffffffffff)
#define OOB_RX_CQE_TRANS_CNTR__RX_CQE_TRANS_CNTR_FIELD 0,63


/*
 * wqe configurations.
 * set of configurations that define how to access to the WQE pointers
 */
#define OOB_RX_WQE 0x02c8
#define OOB_RX_WQE__LENGTH 0x0001

#define OOB_RX_WQE__SIZE_LOG2_SHIFT 0
#define OOB_RX_WQE__SIZE_LOG2_WIDTH 4
#define OOB_RX_WQE__SIZE_LOG2_RESET_VAL 8
#define OOB_RX_WQE__SIZE_LOG2_RMASK 0xf
#define OOB_RX_WQE__SIZE_LOG2_MASK  0xf
#define OOB_RX_WQE__SIZE_LOG2_FIELD 0,3

#define OOB_RX_WQE__FIRST_ADDRESS_SHIFT 6
#define OOB_RX_WQE__FIRST_ADDRESS_WIDTH 34
#define OOB_RX_WQE__FIRST_ADDRESS_RESET_VAL 0
#define OOB_RX_WQE__FIRST_ADDRESS_RMASK _64bit(0x3ffffffff)
#define OOB_RX_WQE__FIRST_ADDRESS_MASK  _64bit(0xffffffffc0)
#define OOB_RX_WQE__FIRST_ADDRESS_FIELD 6,39


/*
 * cqe configurations.
 * set of configurations that define how to access to the CQE pointers
 */
#define OOB_RX_CQE 0x02d0
#define OOB_RX_CQE__LENGTH 0x0001

#define OOB_RX_CQE__SIZE_LOG2_SHIFT 0
#define OOB_RX_CQE__SIZE_LOG2_WIDTH 4
#define OOB_RX_CQE__SIZE_LOG2_RESET_VAL 8
#define OOB_RX_CQE__SIZE_LOG2_RMASK 0xf
#define OOB_RX_CQE__SIZE_LOG2_MASK  0xf
#define OOB_RX_CQE__SIZE_LOG2_FIELD 0,3

#define OOB_RX_CQE__FIRST_ADDRESS_SHIFT 6
#define OOB_RX_CQE__FIRST_ADDRESS_WIDTH 34
#define OOB_RX_CQE__FIRST_ADDRESS_RESET_VAL 0
#define OOB_RX_CQE__FIRST_ADDRESS_RMASK _64bit(0x3ffffffff)
#define OOB_RX_CQE__FIRST_ADDRESS_MASK  _64bit(0xffffffffc0)
#define OOB_RX_CQE__FIRST_ADDRESS_FIELD 6,39

#define OOB_RX_CQE__VALID_BIT_START_SHIFT 40
#define OOB_RX_CQE__VALID_BIT_START_WIDTH 1
#define OOB_RX_CQE__VALID_BIT_START_RESET_VAL 0
#define OOB_RX_CQE__VALID_BIT_START_RMASK 0x1
#define OOB_RX_CQE__VALID_BIT_START_MASK  _64bit(0x10000000000)
#define OOB_RX_CQE__VALID_BIT_START_FIELD 40,40


/*
 * the fetch unit prepare cqes/wqes page pointers has a limit how much to
 * fill in the fifo.
 * the fifo depth is 16, limit the maximal fullness as start of new request
 */
#define OOB_RX_QE_READY_MAX_FIFO_TH 0x02e0
#define OOB_RX_QE_READY_MAX_FIFO_TH__LENGTH 0x0001

#define OOB_RX_QE_READY_MAX_FIFO_TH__WQE_SHIFT 0
#define OOB_RX_QE_READY_MAX_FIFO_TH__WQE_WIDTH 7
#define OOB_RX_QE_READY_MAX_FIFO_TH__WQE_RESET_VAL 16
#define OOB_RX_QE_READY_MAX_FIFO_TH__WQE_RMASK 0x7f
#define OOB_RX_QE_READY_MAX_FIFO_TH__WQE_MASK  0x7f
#define OOB_RX_QE_READY_MAX_FIFO_TH__WQE_FIELD 0,6


/*
 * mac related configurations.
 * the mac reset is controlloed by ARM for security (reset high)
 */
#define OOB_MAC_CFG 0x0408
#define OOB_MAC_CFG__LENGTH 0x0001

#define OOB_MAC_CFG__METER_MAID_CLOCKS_NUM_SHIFT 0
#define OOB_MAC_CFG__METER_MAID_CLOCKS_NUM_WIDTH 8
#define OOB_MAC_CFG__METER_MAID_CLOCKS_NUM_RESET_VAL 100
#define OOB_MAC_CFG__METER_MAID_CLOCKS_NUM_RMASK 0xff
#define OOB_MAC_CFG__METER_MAID_CLOCKS_NUM_MASK  0xff
#define OOB_MAC_CFG__METER_MAID_CLOCKS_NUM_FIELD 0,7

#define OOB_MAC_CFG__IR_PERF_CNT_EN_SHIFT 8
#define OOB_MAC_CFG__IR_PERF_CNT_EN_WIDTH 1
#define OOB_MAC_CFG__IR_PERF_CNT_EN_RESET_VAL 0
#define OOB_MAC_CFG__IR_PERF_CNT_EN_RMASK 0x1
#define OOB_MAC_CFG__IR_PERF_CNT_EN_MASK  0x100
#define OOB_MAC_CFG__IR_PERF_CNT_EN_FIELD 8,8


/*
 * enable interrupt raising in rx oob - configuration.
 * each interrupt can be enabled (1) or disables (0)
 */
#define OOB_RX_INT_EN 0x02e8
#define OOB_RX_INT_EN__LENGTH 0x0001

#define OOB_RX_INT_EN__DIN_MAC_ERR_PASSED_SHIFT 0
#define OOB_RX_INT_EN__DIN_MAC_ERR_PASSED_WIDTH 1
#define OOB_RX_INT_EN__DIN_MAC_ERR_PASSED_RESET_VAL 0
#define OOB_RX_INT_EN__DIN_MAC_ERR_PASSED_RMASK 0x1
#define OOB_RX_INT_EN__DIN_MAC_ERR_PASSED_MASK  0x1
#define OOB_RX_INT_EN__DIN_MAC_ERR_PASSED_FIELD 0,0

#define OOB_RX_INT_EN__DIN_TRN_ERR_PASSED_SHIFT 1
#define OOB_RX_INT_EN__DIN_TRN_ERR_PASSED_WIDTH 1
#define OOB_RX_INT_EN__DIN_TRN_ERR_PASSED_RESET_VAL 0
#define OOB_RX_INT_EN__DIN_TRN_ERR_PASSED_RMASK 0x1
#define OOB_RX_INT_EN__DIN_TRN_ERR_PASSED_MASK  0x2
#define OOB_RX_INT_EN__DIN_TRN_ERR_PASSED_FIELD 1,1

#define OOB_RX_INT_EN__DIN_MAC_ERR_DISCARD_SHIFT 2
#define OOB_RX_INT_EN__DIN_MAC_ERR_DISCARD_WIDTH 1
#define OOB_RX_INT_EN__DIN_MAC_ERR_DISCARD_RESET_VAL 0
#define OOB_RX_INT_EN__DIN_MAC_ERR_DISCARD_RMASK 0x1
#define OOB_RX_INT_EN__DIN_MAC_ERR_DISCARD_MASK  0x4
#define OOB_RX_INT_EN__DIN_MAC_ERR_DISCARD_FIELD 2,2

#define OOB_RX_INT_EN__DIN_TRN_ERR_DISCARD_SHIFT 3
#define OOB_RX_INT_EN__DIN_TRN_ERR_DISCARD_WIDTH 1
#define OOB_RX_INT_EN__DIN_TRN_ERR_DISCARD_RESET_VAL 0
#define OOB_RX_INT_EN__DIN_TRN_ERR_DISCARD_RMASK 0x1
#define OOB_RX_INT_EN__DIN_TRN_ERR_DISCARD_MASK  0x8
#define OOB_RX_INT_EN__DIN_TRN_ERR_DISCARD_FIELD 3,3

#define OOB_RX_INT_EN__DIN_TOO_LARGE_DISCARD_SHIFT 4
#define OOB_RX_INT_EN__DIN_TOO_LARGE_DISCARD_WIDTH 1
#define OOB_RX_INT_EN__DIN_TOO_LARGE_DISCARD_RESET_VAL 0
#define OOB_RX_INT_EN__DIN_TOO_LARGE_DISCARD_RMASK 0x1
#define OOB_RX_INT_EN__DIN_TOO_LARGE_DISCARD_MASK  0x10
#define OOB_RX_INT_EN__DIN_TOO_LARGE_DISCARD_FIELD 4,4

#define OOB_RX_INT_EN__DIN_TRN_ERR_FATAL_SHIFT 5
#define OOB_RX_INT_EN__DIN_TRN_ERR_FATAL_WIDTH 1
#define OOB_RX_INT_EN__DIN_TRN_ERR_FATAL_RESET_VAL 0
#define OOB_RX_INT_EN__DIN_TRN_ERR_FATAL_RMASK 0x1
#define OOB_RX_INT_EN__DIN_TRN_ERR_FATAL_MASK  0x20
#define OOB_RX_INT_EN__DIN_TRN_ERR_FATAL_FIELD 5,5

#define OOB_RX_INT_EN__DMA_IN_WRESP_SHIFT 6
#define OOB_RX_INT_EN__DMA_IN_WRESP_WIDTH 1
#define OOB_RX_INT_EN__DMA_IN_WRESP_RESET_VAL 0
#define OOB_RX_INT_EN__DMA_IN_WRESP_RMASK 0x1
#define OOB_RX_INT_EN__DMA_IN_WRESP_MASK  0x40
#define OOB_RX_INT_EN__DMA_IN_WRESP_FIELD 6,6

#define OOB_RX_INT_EN__DMA_CQE_WRESP_SHIFT 7
#define OOB_RX_INT_EN__DMA_CQE_WRESP_WIDTH 1
#define OOB_RX_INT_EN__DMA_CQE_WRESP_RESET_VAL 0
#define OOB_RX_INT_EN__DMA_CQE_WRESP_RMASK 0x1
#define OOB_RX_INT_EN__DMA_CQE_WRESP_MASK  0x80
#define OOB_RX_INT_EN__DMA_CQE_WRESP_FIELD 7,7

#define OOB_RX_INT_EN__DMA_IN_4K_BNDR_SHIFT 8
#define OOB_RX_INT_EN__DMA_IN_4K_BNDR_WIDTH 1
#define OOB_RX_INT_EN__DMA_IN_4K_BNDR_RESET_VAL 0
#define OOB_RX_INT_EN__DMA_IN_4K_BNDR_RMASK 0x1
#define OOB_RX_INT_EN__DMA_IN_4K_BNDR_MASK  0x100
#define OOB_RX_INT_EN__DMA_IN_4K_BNDR_FIELD 8,8

#define OOB_RX_INT_EN__WQE_RD_RESP_ERR_SHIFT 9
#define OOB_RX_INT_EN__WQE_RD_RESP_ERR_WIDTH 1
#define OOB_RX_INT_EN__WQE_RD_RESP_ERR_RESET_VAL 0
#define OOB_RX_INT_EN__WQE_RD_RESP_ERR_RMASK 0x1
#define OOB_RX_INT_EN__WQE_RD_RESP_ERR_MASK  0x200
#define OOB_RX_INT_EN__WQE_RD_RESP_ERR_FIELD 9,9

#define OOB_RX_INT_EN__LLU_ACCESS_ERR_SHIFT 10
#define OOB_RX_INT_EN__LLU_ACCESS_ERR_WIDTH 1
#define OOB_RX_INT_EN__LLU_ACCESS_ERR_RESET_VAL 0
#define OOB_RX_INT_EN__LLU_ACCESS_ERR_RMASK 0x1
#define OOB_RX_INT_EN__LLU_ACCESS_ERR_MASK  0x400
#define OOB_RX_INT_EN__LLU_ACCESS_ERR_FIELD 10,10

#define OOB_RX_INT_EN__PLU_ACCESS_ERR_SHIFT 11
#define OOB_RX_INT_EN__PLU_ACCESS_ERR_WIDTH 1
#define OOB_RX_INT_EN__PLU_ACCESS_ERR_RESET_VAL 0
#define OOB_RX_INT_EN__PLU_ACCESS_ERR_RMASK 0x1
#define OOB_RX_INT_EN__PLU_ACCESS_ERR_MASK  0x800
#define OOB_RX_INT_EN__PLU_ACCESS_ERR_FIELD 11,11


/*
 * counting all the pass packets through the RX filter.
 * count all the pass (not a specific DMAC)
 */
#define OOB_RX_INT_STATUS 0x02f0
#define OOB_RX_INT_STATUS__LENGTH 0x0001

#define OOB_RX_INT_STATUS__DIN_MAC_ERR_PASSED_SHIFT 0
#define OOB_RX_INT_STATUS__DIN_MAC_ERR_PASSED_WIDTH 1
#define OOB_RX_INT_STATUS__DIN_MAC_ERR_PASSED_RESET_VAL 0
#define OOB_RX_INT_STATUS__DIN_MAC_ERR_PASSED_RMASK 0x1
#define OOB_RX_INT_STATUS__DIN_MAC_ERR_PASSED_MASK  0x1
#define OOB_RX_INT_STATUS__DIN_MAC_ERR_PASSED_FIELD 0,0

#define OOB_RX_INT_STATUS__DIN_TRN_ERR_PASSED_SHIFT 1
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_PASSED_WIDTH 1
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_PASSED_RESET_VAL 0
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_PASSED_RMASK 0x1
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_PASSED_MASK  0x2
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_PASSED_FIELD 1,1

#define OOB_RX_INT_STATUS__DIN_MAC_ERR_DISCARD_SHIFT 2
#define OOB_RX_INT_STATUS__DIN_MAC_ERR_DISCARD_WIDTH 1
#define OOB_RX_INT_STATUS__DIN_MAC_ERR_DISCARD_RESET_VAL 0
#define OOB_RX_INT_STATUS__DIN_MAC_ERR_DISCARD_RMASK 0x1
#define OOB_RX_INT_STATUS__DIN_MAC_ERR_DISCARD_MASK  0x4
#define OOB_RX_INT_STATUS__DIN_MAC_ERR_DISCARD_FIELD 2,2

#define OOB_RX_INT_STATUS__DIN_TRN_ERR_DISCARD_SHIFT 3
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_DISCARD_WIDTH 1
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_DISCARD_RESET_VAL 0
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_DISCARD_RMASK 0x1
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_DISCARD_MASK  0x8
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_DISCARD_FIELD 3,3

#define OOB_RX_INT_STATUS__DIN_TOO_LARGE_DISCARD_SHIFT 4
#define OOB_RX_INT_STATUS__DIN_TOO_LARGE_DISCARD_WIDTH 1
#define OOB_RX_INT_STATUS__DIN_TOO_LARGE_DISCARD_RESET_VAL 0
#define OOB_RX_INT_STATUS__DIN_TOO_LARGE_DISCARD_RMASK 0x1
#define OOB_RX_INT_STATUS__DIN_TOO_LARGE_DISCARD_MASK  0x10
#define OOB_RX_INT_STATUS__DIN_TOO_LARGE_DISCARD_FIELD 4,4

#define OOB_RX_INT_STATUS__DIN_TRN_ERR_FATAL_SHIFT 5
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_FATAL_WIDTH 1
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_FATAL_RESET_VAL 0
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_FATAL_RMASK 0x1
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_FATAL_MASK  0x20
#define OOB_RX_INT_STATUS__DIN_TRN_ERR_FATAL_FIELD 5,5

#define OOB_RX_INT_STATUS__DMA_IN_WRESP_SHIFT 6
#define OOB_RX_INT_STATUS__DMA_IN_WRESP_WIDTH 1
#define OOB_RX_INT_STATUS__DMA_IN_WRESP_RESET_VAL 0
#define OOB_RX_INT_STATUS__DMA_IN_WRESP_RMASK 0x1
#define OOB_RX_INT_STATUS__DMA_IN_WRESP_MASK  0x40
#define OOB_RX_INT_STATUS__DMA_IN_WRESP_FIELD 6,6

#define OOB_RX_INT_STATUS__DMA_CQE_WRESP_SHIFT 7
#define OOB_RX_INT_STATUS__DMA_CQE_WRESP_WIDTH 1
#define OOB_RX_INT_STATUS__DMA_CQE_WRESP_RESET_VAL 0
#define OOB_RX_INT_STATUS__DMA_CQE_WRESP_RMASK 0x1
#define OOB_RX_INT_STATUS__DMA_CQE_WRESP_MASK  0x80
#define OOB_RX_INT_STATUS__DMA_CQE_WRESP_FIELD 7,7

#define OOB_RX_INT_STATUS__DMA_IN_4K_BNDR_SHIFT 8
#define OOB_RX_INT_STATUS__DMA_IN_4K_BNDR_WIDTH 1
#define OOB_RX_INT_STATUS__DMA_IN_4K_BNDR_RESET_VAL 0
#define OOB_RX_INT_STATUS__DMA_IN_4K_BNDR_RMASK 0x1
#define OOB_RX_INT_STATUS__DMA_IN_4K_BNDR_MASK  0x100
#define OOB_RX_INT_STATUS__DMA_IN_4K_BNDR_FIELD 8,8

#define OOB_RX_INT_STATUS__WQE_RD_RESP_ERR_SHIFT 9
#define OOB_RX_INT_STATUS__WQE_RD_RESP_ERR_WIDTH 1
#define OOB_RX_INT_STATUS__WQE_RD_RESP_ERR_RESET_VAL 0
#define OOB_RX_INT_STATUS__WQE_RD_RESP_ERR_RMASK 0x1
#define OOB_RX_INT_STATUS__WQE_RD_RESP_ERR_MASK  0x200
#define OOB_RX_INT_STATUS__WQE_RD_RESP_ERR_FIELD 9,9

#define OOB_RX_INT_STATUS__LLU_ACCESS_ERR_SHIFT 10
#define OOB_RX_INT_STATUS__LLU_ACCESS_ERR_WIDTH 1
#define OOB_RX_INT_STATUS__LLU_ACCESS_ERR_RESET_VAL 0
#define OOB_RX_INT_STATUS__LLU_ACCESS_ERR_RMASK 0x1
#define OOB_RX_INT_STATUS__LLU_ACCESS_ERR_MASK  0x400
#define OOB_RX_INT_STATUS__LLU_ACCESS_ERR_FIELD 10,10

#define OOB_RX_INT_STATUS__PLU_ACCESS_ERR_SHIFT 11
#define OOB_RX_INT_STATUS__PLU_ACCESS_ERR_WIDTH 1
#define OOB_RX_INT_STATUS__PLU_ACCESS_ERR_RESET_VAL 0
#define OOB_RX_INT_STATUS__PLU_ACCESS_ERR_RMASK 0x1
#define OOB_RX_INT_STATUS__PLU_ACCESS_ERR_MASK  0x800
#define OOB_RX_INT_STATUS__PLU_ACCESS_ERR_FIELD 11,11


/*
 * to be removed.
 * none
 */
#define OOB_OOB_RX_CQE_PAGE_USED_CI 0x0418
#define OOB_OOB_RX_CQE_PAGE_USED_CI__LENGTH 0x0001

#define OOB_OOB_RX_CQE_PAGE_USED_CI__OOB_RX_CQE_PAGE_USED_CI_SHIFT 0
#define OOB_OOB_RX_CQE_PAGE_USED_CI__OOB_RX_CQE_PAGE_USED_CI_WIDTH 64
#define OOB_OOB_RX_CQE_PAGE_USED_CI__OOB_RX_CQE_PAGE_USED_CI_RESET_VAL 0
#define OOB_OOB_RX_CQE_PAGE_USED_CI__OOB_RX_CQE_PAGE_USED_CI_RMASK _64bit(0xffffffffffffffff)
#define OOB_OOB_RX_CQE_PAGE_USED_CI__OOB_RX_CQE_PAGE_USED_CI_MASK  _64bit(0xffffffffffffffff)
#define OOB_OOB_RX_CQE_PAGE_USED_CI__OOB_RX_CQE_PAGE_USED_CI_FIELD 0,63


/*
 * to be removed.
 * none
 */
#define OOB_OOB_RX_CQE_PAGE_PI 0x0410
#define OOB_OOB_RX_CQE_PAGE_PI__LENGTH 0x0001

#define OOB_OOB_RX_CQE_PAGE_PI__OOB_RX_CQE_PAGE_PI_SHIFT 0
#define OOB_OOB_RX_CQE_PAGE_PI__OOB_RX_CQE_PAGE_PI_WIDTH 64
#define OOB_OOB_RX_CQE_PAGE_PI__OOB_RX_CQE_PAGE_PI_RESET_VAL 0
#define OOB_OOB_RX_CQE_PAGE_PI__OOB_RX_CQE_PAGE_PI_RMASK _64bit(0xffffffffffffffff)
#define OOB_OOB_RX_CQE_PAGE_PI__OOB_RX_CQE_PAGE_PI_MASK  _64bit(0xffffffffffffffff)
#define OOB_OOB_RX_CQE_PAGE_PI__OOB_RX_CQE_PAGE_PI_FIELD 0,63

#endif /* !defined(__DOXYGEN__) */

#endif /* !defined(__REGS_OOB_DEF_H__) */
