#ifndef __REGS_MMC_DEF_H__
#define __REGS_MMC_DEF_H__

#ifdef __ASSEMBLER__
#define _64bit(x) x
#else /* __ASSEMBLER__ */
#ifdef __tile__
#define _64bit(x) x ## UL
#else /* __tile__ */
#define _64bit(x) x ## ULL
#endif /* __tile__ */
#endif /* __ASSEMBLER */



#ifndef __DOXYGEN__

/*
 * Device Info.
 * This register provides general information about the device attached to
 * this port and channel.
 */
#define MMC_DEV_INFO 0x0000
#define MMC_DEV_INFO__LENGTH 0x0001

#define MMC_DEV_INFO__TYPE_SHIFT 0
#define MMC_DEV_INFO__TYPE_WIDTH 12
#define MMC_DEV_INFO__TYPE_RESET_VAL 0
#define MMC_DEV_INFO__TYPE_RMASK 0xfff
#define MMC_DEV_INFO__TYPE_MASK  0xfff
#define MMC_DEV_INFO__TYPE_FIELD 0,11
#define MMC_DEV_INFO__TYPE_VAL_PCIE 0x1
#define MMC_DEV_INFO__TYPE_VAL_GBE 0x10
#define MMC_DEV_INFO__TYPE_VAL_XGBE 0x11
#define MMC_DEV_INFO__TYPE_VAL_MPIPE 0x13
#define MMC_DEV_INFO__TYPE_VAL_TRIO 0x14
#define MMC_DEV_INFO__TYPE_VAL_CRYPTO 0x16
#define MMC_DEV_INFO__TYPE_VAL_COMPRESSION 0x18
#define MMC_DEV_INFO__TYPE_VAL_GPIO 0x20
#define MMC_DEV_INFO__TYPE_VAL_RSHIM 0x21
#define MMC_DEV_INFO__TYPE_VAL_SROM 0x22
#define MMC_DEV_INFO__TYPE_VAL_I2CM 0x25
#define MMC_DEV_INFO__TYPE_VAL_I2CS 0x26
#define MMC_DEV_INFO__TYPE_VAL_UART 0x28
#define MMC_DEV_INFO__TYPE_VAL_USBH 0x29
#define MMC_DEV_INFO__TYPE_VAL_USBS 0x2a
#define MMC_DEV_INFO__TYPE_VAL_USBHS 0x2b
#define MMC_DEV_INFO__TYPE_VAL_MMC 0x2c
#define MMC_DEV_INFO__TYPE_VAL_DDR2 0x40
#define MMC_DEV_INFO__TYPE_VAL_DDR3 0x42
#define MMC_DEV_INFO__TYPE_VAL_DDR4 0x44
#define MMC_DEV_INFO__TYPE_VAL_HMC 0x45
#define MMC_DEV_INFO__TYPE_VAL_MSS 0x46
#define MMC_DEV_INFO__TYPE_VAL_DIAG_SNP 0x80
#define MMC_DEV_INFO__TYPE_VAL_IPIC 0x81
#define MMC_DEV_INFO__TYPE_VAL_TILE 0x82
#define MMC_DEV_INFO__TYPE_VAL_TM 0x83
#define MMC_DEV_INFO__TYPE_VAL_TCAM 0x84
#define MMC_DEV_INFO__TYPE_VAL_SMMU 0x85
#define MMC_DEV_INFO__TYPE_VAL_GIC 0x86
#define MMC_DEV_INFO__TYPE_VAL_MPIPE_TX 0x87

#define MMC_DEV_INFO__DEVICE_REV_SHIFT 16
#define MMC_DEV_INFO__DEVICE_REV_WIDTH 8
#define MMC_DEV_INFO__DEVICE_REV_RMASK 0xff
#define MMC_DEV_INFO__DEVICE_REV_MASK  0xff0000
#define MMC_DEV_INFO__DEVICE_REV_FIELD 16,23

#define MMC_DEV_INFO__REGISTER_REV_SHIFT 24
#define MMC_DEV_INFO__REGISTER_REV_WIDTH 4
#define MMC_DEV_INFO__REGISTER_REV_RESET_VAL 0
#define MMC_DEV_INFO__REGISTER_REV_RMASK 0xf
#define MMC_DEV_INFO__REGISTER_REV_MASK  0xf000000
#define MMC_DEV_INFO__REGISTER_REV_FIELD 24,27

#define MMC_DEV_INFO__INSTANCE_SHIFT 32
#define MMC_DEV_INFO__INSTANCE_WIDTH 4
#define MMC_DEV_INFO__INSTANCE_RMASK 0xf
#define MMC_DEV_INFO__INSTANCE_MASK  _64bit(0xf00000000)
#define MMC_DEV_INFO__INSTANCE_FIELD 32,35


/*
 * Device Control.
 * This register provides general device control.
 */
#define MMC_DEV_CTL 0x0008
#define MMC_DEV_CTL__LENGTH 0x0001

#define MMC_DEV_CTL__NDN_ROUTE_ORDER_SHIFT 0
#define MMC_DEV_CTL__NDN_ROUTE_ORDER_WIDTH 1
#define MMC_DEV_CTL__NDN_ROUTE_ORDER_RESET_VAL 0
#define MMC_DEV_CTL__NDN_ROUTE_ORDER_RMASK 0x1
#define MMC_DEV_CTL__NDN_ROUTE_ORDER_MASK  0x1
#define MMC_DEV_CTL__NDN_ROUTE_ORDER_FIELD 0,0

#define MMC_DEV_CTL__CDN_ROUTE_ORDER_SHIFT 1
#define MMC_DEV_CTL__CDN_ROUTE_ORDER_WIDTH 1
#define MMC_DEV_CTL__CDN_ROUTE_ORDER_RESET_VAL 1
#define MMC_DEV_CTL__CDN_ROUTE_ORDER_RMASK 0x1
#define MMC_DEV_CTL__CDN_ROUTE_ORDER_MASK  0x2
#define MMC_DEV_CTL__CDN_ROUTE_ORDER_FIELD 1,1

#define MMC_DEV_CTL__DDN_ROUTE_ORDER_SHIFT 2
#define MMC_DEV_CTL__DDN_ROUTE_ORDER_WIDTH 1
#define MMC_DEV_CTL__DDN_ROUTE_ORDER_RESET_VAL 1
#define MMC_DEV_CTL__DDN_ROUTE_ORDER_RMASK 0x1
#define MMC_DEV_CTL__DDN_ROUTE_ORDER_MASK  0x4
#define MMC_DEV_CTL__DDN_ROUTE_ORDER_FIELD 2,2

#define MMC_DEV_CTL__DMA_RD_CA_ENA_SHIFT 3
#define MMC_DEV_CTL__DMA_RD_CA_ENA_WIDTH 1
#define MMC_DEV_CTL__DMA_RD_CA_ENA_RESET_VAL 1
#define MMC_DEV_CTL__DMA_RD_CA_ENA_RMASK 0x1
#define MMC_DEV_CTL__DMA_RD_CA_ENA_MASK  0x8
#define MMC_DEV_CTL__DMA_RD_CA_ENA_FIELD 3,3

#define MMC_DEV_CTL__L3_PROFILE_OVD_SHIFT 4
#define MMC_DEV_CTL__L3_PROFILE_OVD_WIDTH 1
#define MMC_DEV_CTL__L3_PROFILE_OVD_RESET_VAL 0
#define MMC_DEV_CTL__L3_PROFILE_OVD_RMASK 0x1
#define MMC_DEV_CTL__L3_PROFILE_OVD_MASK  0x10
#define MMC_DEV_CTL__L3_PROFILE_OVD_FIELD 4,4

#define MMC_DEV_CTL__L3_PROFILE_VAL_SHIFT 5
#define MMC_DEV_CTL__L3_PROFILE_VAL_WIDTH 4
#define MMC_DEV_CTL__L3_PROFILE_VAL_RESET_VAL 0
#define MMC_DEV_CTL__L3_PROFILE_VAL_RMASK 0xf
#define MMC_DEV_CTL__L3_PROFILE_VAL_MASK  0x1e0
#define MMC_DEV_CTL__L3_PROFILE_VAL_FIELD 5,8

#define MMC_DEV_CTL__WR_SLVERR_MAP_SHIFT 9
#define MMC_DEV_CTL__WR_SLVERR_MAP_WIDTH 2
#define MMC_DEV_CTL__WR_SLVERR_MAP_RESET_VAL 2
#define MMC_DEV_CTL__WR_SLVERR_MAP_RMASK 0x3
#define MMC_DEV_CTL__WR_SLVERR_MAP_MASK  0x600
#define MMC_DEV_CTL__WR_SLVERR_MAP_FIELD 9,10
#define MMC_DEV_CTL__WR_SLVERR_MAP_VAL_OKAY 0x0
#define MMC_DEV_CTL__WR_SLVERR_MAP_VAL_DATAERROR 0x2
#define MMC_DEV_CTL__WR_SLVERR_MAP_VAL_NONDATAERROR 0x3

#define MMC_DEV_CTL__WR_DECERR_MAP_SHIFT 11
#define MMC_DEV_CTL__WR_DECERR_MAP_WIDTH 2
#define MMC_DEV_CTL__WR_DECERR_MAP_RESET_VAL 3
#define MMC_DEV_CTL__WR_DECERR_MAP_RMASK 0x3
#define MMC_DEV_CTL__WR_DECERR_MAP_MASK  0x1800
#define MMC_DEV_CTL__WR_DECERR_MAP_FIELD 11,12
#define MMC_DEV_CTL__WR_DECERR_MAP_VAL_OKAY 0x0
#define MMC_DEV_CTL__WR_DECERR_MAP_VAL_DATAERROR 0x2
#define MMC_DEV_CTL__WR_DECERR_MAP_VAL_NONDATAERROR 0x3

#define MMC_DEV_CTL__RD_SLVERR_MAP_SHIFT 13
#define MMC_DEV_CTL__RD_SLVERR_MAP_WIDTH 2
#define MMC_DEV_CTL__RD_SLVERR_MAP_RESET_VAL 2
#define MMC_DEV_CTL__RD_SLVERR_MAP_RMASK 0x3
#define MMC_DEV_CTL__RD_SLVERR_MAP_MASK  0x6000
#define MMC_DEV_CTL__RD_SLVERR_MAP_FIELD 13,14
#define MMC_DEV_CTL__RD_SLVERR_MAP_VAL_OKAY 0x0
#define MMC_DEV_CTL__RD_SLVERR_MAP_VAL_DATAERROR 0x2
#define MMC_DEV_CTL__RD_SLVERR_MAP_VAL_NONDATAERROR 0x3

#define MMC_DEV_CTL__RD_DECERR_MAP_SHIFT 15
#define MMC_DEV_CTL__RD_DECERR_MAP_WIDTH 2
#define MMC_DEV_CTL__RD_DECERR_MAP_RESET_VAL 3
#define MMC_DEV_CTL__RD_DECERR_MAP_RMASK 0x3
#define MMC_DEV_CTL__RD_DECERR_MAP_MASK  0x18000
#define MMC_DEV_CTL__RD_DECERR_MAP_FIELD 15,16
#define MMC_DEV_CTL__RD_DECERR_MAP_VAL_OKAY 0x0
#define MMC_DEV_CTL__RD_DECERR_MAP_VAL_DATAERROR 0x2
#define MMC_DEV_CTL__RD_DECERR_MAP_VAL_NONDATAERROR 0x3

#define MMC_DEV_CTL__CDN_REQ_BUF_ENA_SHIFT 17
#define MMC_DEV_CTL__CDN_REQ_BUF_ENA_WIDTH 1
#define MMC_DEV_CTL__CDN_REQ_BUF_ENA_RESET_VAL 1
#define MMC_DEV_CTL__CDN_REQ_BUF_ENA_RMASK 0x1
#define MMC_DEV_CTL__CDN_REQ_BUF_ENA_MASK  0x20000
#define MMC_DEV_CTL__CDN_REQ_BUF_ENA_FIELD 17,17

#define MMC_DEV_CTL__DMA_WRQ_HWM_SHIFT 20
#define MMC_DEV_CTL__DMA_WRQ_HWM_WIDTH 8
#define MMC_DEV_CTL__DMA_WRQ_HWM_RESET_VAL 255
#define MMC_DEV_CTL__DMA_WRQ_HWM_RMASK 0xff
#define MMC_DEV_CTL__DMA_WRQ_HWM_MASK  0xff00000
#define MMC_DEV_CTL__DMA_WRQ_HWM_FIELD 20,27

#define MMC_DEV_CTL__GTHR_DELAY_ADJ_SHIFT 28
#define MMC_DEV_CTL__GTHR_DELAY_ADJ_WIDTH 4
#define MMC_DEV_CTL__GTHR_DELAY_ADJ_RESET_VAL 0
#define MMC_DEV_CTL__GTHR_DELAY_ADJ_RMASK 0xf
#define MMC_DEV_CTL__GTHR_DELAY_ADJ_MASK  0xf0000000
#define MMC_DEV_CTL__GTHR_DELAY_ADJ_FIELD 28,31


/* Scratchpad. */
#define MMC_SCRATCHPAD 0x0020
#define MMC_SCRATCHPAD__LENGTH 0x0001

#define MMC_SCRATCHPAD__SCRATCHPAD_SHIFT 0
#define MMC_SCRATCHPAD__SCRATCHPAD_WIDTH 64
#define MMC_SCRATCHPAD__SCRATCHPAD_RESET_VAL 0
#define MMC_SCRATCHPAD__SCRATCHPAD_RMASK _64bit(0xffffffffffffffff)
#define MMC_SCRATCHPAD__SCRATCHPAD_MASK  _64bit(0xffffffffffffffff)
#define MMC_SCRATCHPAD__SCRATCHPAD_FIELD 0,63


/*
 * Semaphore0.
 * Semaphore
 */
#define MMC_SEMAPHORE0 0x0028
#define MMC_SEMAPHORE0__LENGTH 0x0001

#define MMC_SEMAPHORE0__VAL_SHIFT 0
#define MMC_SEMAPHORE0__VAL_WIDTH 1
#define MMC_SEMAPHORE0__VAL_RESET_VAL 0
#define MMC_SEMAPHORE0__VAL_RMASK 0x1
#define MMC_SEMAPHORE0__VAL_MASK  0x1
#define MMC_SEMAPHORE0__VAL_FIELD 0,0


/*
 * DMA Status.
 * DMA status information for debug. Unused for devices that do not have DMA.
 */
#define MMC_DMA_STATUS 0x0030
#define MMC_DMA_STATUS__LENGTH 0x0001

#define MMC_DMA_STATUS__RDQ_INFL_COUNT_SHIFT 0
#define MMC_DMA_STATUS__RDQ_INFL_COUNT_WIDTH 9
#define MMC_DMA_STATUS__RDQ_INFL_COUNT_RESET_VAL 0
#define MMC_DMA_STATUS__RDQ_INFL_COUNT_RMASK 0x1ff
#define MMC_DMA_STATUS__RDQ_INFL_COUNT_MASK  0x1ff
#define MMC_DMA_STATUS__RDQ_INFL_COUNT_FIELD 0,8

#define MMC_DMA_STATUS__WRQ_INFL_COUNT_SHIFT 9
#define MMC_DMA_STATUS__WRQ_INFL_COUNT_WIDTH 9
#define MMC_DMA_STATUS__WRQ_INFL_COUNT_RESET_VAL 0
#define MMC_DMA_STATUS__WRQ_INFL_COUNT_RMASK 0x1ff
#define MMC_DMA_STATUS__WRQ_INFL_COUNT_MASK  0x3fe00
#define MMC_DMA_STATUS__WRQ_INFL_COUNT_FIELD 9,17

#define MMC_DMA_STATUS__WRQ_DIAG_VEC_SHIFT 25
#define MMC_DMA_STATUS__WRQ_DIAG_VEC_WIDTH 39
#define MMC_DMA_STATUS__WRQ_DIAG_VEC_RESET_VAL 0
#define MMC_DMA_STATUS__WRQ_DIAG_VEC_RMASK _64bit(0x7fffffffff)
#define MMC_DMA_STATUS__WRQ_DIAG_VEC_MASK  _64bit(0xfffffffffe000000)
#define MMC_DMA_STATUS__WRQ_DIAG_VEC_FIELD 25,63


/* Clock Count. */
#define MMC_CLOCK_COUNT 0x0038
#define MMC_CLOCK_COUNT__LENGTH 0x0001

#define MMC_CLOCK_COUNT__RUN_SHIFT 0
#define MMC_CLOCK_COUNT__RUN_WIDTH 1
#define MMC_CLOCK_COUNT__RUN_RESET_VAL 0
#define MMC_CLOCK_COUNT__RUN_RMASK 0x1
#define MMC_CLOCK_COUNT__RUN_MASK  0x1
#define MMC_CLOCK_COUNT__RUN_FIELD 0,0

#define MMC_CLOCK_COUNT__COUNT_SHIFT 1
#define MMC_CLOCK_COUNT__COUNT_WIDTH 15
#define MMC_CLOCK_COUNT__COUNT_RMASK 0x7fff
#define MMC_CLOCK_COUNT__COUNT_MASK  0xfffe
#define MMC_CLOCK_COUNT__COUNT_FIELD 1,15


/*
 * Interrupt Setup.
 * Configuration for device interrupts.
 */
#define MMC_INT_SETUP 0x0040
#define MMC_INT_SETUP__LENGTH 0x0001

#define MMC_INT_SETUP__GBL_ENA_SHIFT 0
#define MMC_INT_SETUP__GBL_ENA_WIDTH 1
#define MMC_INT_SETUP__GBL_ENA_RESET_VAL 0
#define MMC_INT_SETUP__GBL_ENA_RMASK 0x1
#define MMC_INT_SETUP__GBL_ENA_MASK  0x1
#define MMC_INT_SETUP__GBL_ENA_FIELD 0,0

#define MMC_INT_SETUP__BASE_INT_NUM_SHIFT 48
#define MMC_INT_SETUP__BASE_INT_NUM_WIDTH 16
#define MMC_INT_SETUP__BASE_INT_NUM_RMASK 0xffff
#define MMC_INT_SETUP__BASE_INT_NUM_MASK  _64bit(0xffff000000000000)
#define MMC_INT_SETUP__BASE_INT_NUM_FIELD 48,63


/*
 * Feature Control.
 * Device-specific feature controls.
 */
#define MMC_FEATURE_CTL 0x0048
#define MMC_FEATURE_CTL__LENGTH 0x0001

#define MMC_FEATURE_CTL__FEATURE_CTL_SHIFT 0
#define MMC_FEATURE_CTL__FEATURE_CTL_WIDTH 64
#define MMC_FEATURE_CTL__FEATURE_CTL_RESET_VAL 12297829382473034410
#define MMC_FEATURE_CTL__FEATURE_CTL_RMASK _64bit(0xffffffffffffffff)
#define MMC_FEATURE_CTL__FEATURE_CTL_MASK  _64bit(0xffffffffffffffff)
#define MMC_FEATURE_CTL__FEATURE_CTL_FIELD 0,63


/*
 * Credit Control.
 * Provides access to the request-credit counters that control end-to-end
 * flow control between the device and other nodes in the system.
 */
#define MMC_CRED_CTL 0x0050
#define MMC_CRED_CTL__LENGTH 0x0001

#define MMC_CRED_CTL__UPDATE_SHIFT 0
#define MMC_CRED_CTL__UPDATE_WIDTH 1
#define MMC_CRED_CTL__UPDATE_RESET_VAL 0
#define MMC_CRED_CTL__UPDATE_RMASK 0x1
#define MMC_CRED_CTL__UPDATE_MASK  0x1
#define MMC_CRED_CTL__UPDATE_FIELD 0,0

#define MMC_CRED_CTL__NODEID_SEL_SHIFT 1
#define MMC_CRED_CTL__NODEID_SEL_WIDTH 11
#define MMC_CRED_CTL__NODEID_SEL_RESET_VAL 0
#define MMC_CRED_CTL__NODEID_SEL_RMASK 0x7ff
#define MMC_CRED_CTL__NODEID_SEL_MASK  0xffe
#define MMC_CRED_CTL__NODEID_SEL_FIELD 1,11

#define MMC_CRED_CTL__TGT_SEL_SHIFT 12
#define MMC_CRED_CTL__TGT_SEL_WIDTH 2
#define MMC_CRED_CTL__TGT_SEL_RESET_VAL 0
#define MMC_CRED_CTL__TGT_SEL_RMASK 0x3
#define MMC_CRED_CTL__TGT_SEL_MASK  0x3000
#define MMC_CRED_CTL__TGT_SEL_FIELD 12,13
#define MMC_CRED_CTL__TGT_SEL_VAL_TX_REQ 0x0
#define MMC_CRED_CTL__TGT_SEL_VAL_RETRYQ 0x1
#define MMC_CRED_CTL__TGT_SEL_VAL_RING 0x2

#define MMC_CRED_CTL__CLIENT_SEL_SHIFT 14
#define MMC_CRED_CTL__CLIENT_SEL_WIDTH 2
#define MMC_CRED_CTL__CLIENT_SEL_RESET_VAL 0
#define MMC_CRED_CTL__CLIENT_SEL_RMASK 0x3
#define MMC_CRED_CTL__CLIENT_SEL_MASK  0xc000
#define MMC_CRED_CTL__CLIENT_SEL_FIELD 14,15

#define MMC_CRED_CTL__VAL_SHIFT 16
#define MMC_CRED_CTL__VAL_WIDTH 16
#define MMC_CRED_CTL__VAL_RESET_VAL 0
#define MMC_CRED_CTL__VAL_RMASK 0xffff
#define MMC_CRED_CTL__VAL_MASK  0xffff0000
#define MMC_CRED_CTL__VAL_FIELD 16,31


/*
 * SAM Control.
 * Provides access to SAM initialization.
 */
#define MMC_SAM_CTL 0x0058
#define MMC_SAM_CTL__LENGTH 0x0001

#define MMC_SAM_CTL__UPDATE_SHIFT 0
#define MMC_SAM_CTL__UPDATE_WIDTH 1
#define MMC_SAM_CTL__UPDATE_RESET_VAL 0
#define MMC_SAM_CTL__UPDATE_RMASK 0x1
#define MMC_SAM_CTL__UPDATE_MASK  0x1
#define MMC_SAM_CTL__UPDATE_FIELD 0,0

#define MMC_SAM_CTL__IDX_SHIFT 1
#define MMC_SAM_CTL__IDX_WIDTH 12
#define MMC_SAM_CTL__IDX_RESET_VAL 0
#define MMC_SAM_CTL__IDX_RMASK 0xfff
#define MMC_SAM_CTL__IDX_MASK  0x1ffe
#define MMC_SAM_CTL__IDX_FIELD 1,12
#define MMC_SAM_CTL__IDX_VAL_HNF_SIZE 0x7f7
#define MMC_SAM_CTL__IDX_VAL_LDR_SIZE 0x20

#define MMC_SAM_CTL__TBL_SEL_SHIFT 13
#define MMC_SAM_CTL__TBL_SEL_WIDTH 3
#define MMC_SAM_CTL__TBL_SEL_RESET_VAL 0
#define MMC_SAM_CTL__TBL_SEL_RMASK 0x7
#define MMC_SAM_CTL__TBL_SEL_MASK  0xe000
#define MMC_SAM_CTL__TBL_SEL_FIELD 13,15
#define MMC_SAM_CTL__TBL_SEL_VAL_LDR 0x0
#define MMC_SAM_CTL__TBL_SEL_VAL_HNF 0x1
#define MMC_SAM_CTL__TBL_SEL_VAL_PCI_NPF 0x2
#define MMC_SAM_CTL__TBL_SEL_VAL_PCI_PF 0x3
#define MMC_SAM_CTL__TBL_SEL_VAL_PCI_CFG 0x4

#define MMC_SAM_CTL__CLIENT_SEL_SHIFT 16
#define MMC_SAM_CTL__CLIENT_SEL_WIDTH 1
#define MMC_SAM_CTL__CLIENT_SEL_RESET_VAL 0
#define MMC_SAM_CTL__CLIENT_SEL_RMASK 0x1
#define MMC_SAM_CTL__CLIENT_SEL_MASK  0x10000
#define MMC_SAM_CTL__CLIENT_SEL_FIELD 16,16

#define MMC_SAM_CTL__READ_SHIFT 17
#define MMC_SAM_CTL__READ_WIDTH 1
#define MMC_SAM_CTL__READ_RESET_VAL 0
#define MMC_SAM_CTL__READ_RMASK 0x1
#define MMC_SAM_CTL__READ_MASK  0x20000
#define MMC_SAM_CTL__READ_FIELD 17,17

#define MMC_SAM_CTL__VAL_SHIFT 18
#define MMC_SAM_CTL__VAL_WIDTH 34
#define MMC_SAM_CTL__VAL_RESET_VAL 0
#define MMC_SAM_CTL__VAL_RMASK _64bit(0x3ffffffff)
#define MMC_SAM_CTL__VAL_MASK  _64bit(0xffffffffc0000)
#define MMC_SAM_CTL__VAL_FIELD 18,51


/*
 * CTRL.
 */
#define MMC_CTRL 0x8000
#define MMC_CTRL__LENGTH 0x0001

#define MMC_CTRL__CONTROLLER_RESET_SHIFT 0
#define MMC_CTRL__CONTROLLER_RESET_WIDTH 1
#define MMC_CTRL__CONTROLLER_RESET_RESET_VAL 0
#define MMC_CTRL__CONTROLLER_RESET_RMASK 0x1
#define MMC_CTRL__CONTROLLER_RESET_MASK  0x1
#define MMC_CTRL__CONTROLLER_RESET_FIELD 0,0

#define MMC_CTRL__FIFO_RESET_SHIFT 1
#define MMC_CTRL__FIFO_RESET_WIDTH 1
#define MMC_CTRL__FIFO_RESET_RESET_VAL 0
#define MMC_CTRL__FIFO_RESET_RMASK 0x1
#define MMC_CTRL__FIFO_RESET_MASK  0x2
#define MMC_CTRL__FIFO_RESET_FIELD 1,1

#define MMC_CTRL__DMA_RESET_SHIFT 2
#define MMC_CTRL__DMA_RESET_WIDTH 1
#define MMC_CTRL__DMA_RESET_RESET_VAL 0
#define MMC_CTRL__DMA_RESET_RMASK 0x1
#define MMC_CTRL__DMA_RESET_MASK  0x4
#define MMC_CTRL__DMA_RESET_FIELD 2,2

#define MMC_CTRL__INT_ENABLE_SHIFT 4
#define MMC_CTRL__INT_ENABLE_WIDTH 1
#define MMC_CTRL__INT_ENABLE_RESET_VAL 0
#define MMC_CTRL__INT_ENABLE_RMASK 0x1
#define MMC_CTRL__INT_ENABLE_MASK  0x10
#define MMC_CTRL__INT_ENABLE_FIELD 4,4

#define MMC_CTRL__DMA_ENABLE_SHIFT 5
#define MMC_CTRL__DMA_ENABLE_WIDTH 1
#define MMC_CTRL__DMA_ENABLE_RESET_VAL 0
#define MMC_CTRL__DMA_ENABLE_RMASK 0x1
#define MMC_CTRL__DMA_ENABLE_MASK  0x20
#define MMC_CTRL__DMA_ENABLE_FIELD 5,5

#define MMC_CTRL__READ_WAIT_SHIFT 6
#define MMC_CTRL__READ_WAIT_WIDTH 1
#define MMC_CTRL__READ_WAIT_RESET_VAL 0
#define MMC_CTRL__READ_WAIT_RMASK 0x1
#define MMC_CTRL__READ_WAIT_MASK  0x40
#define MMC_CTRL__READ_WAIT_FIELD 6,6

#define MMC_CTRL__SEND_IRQ_RESPONSE_SHIFT 7
#define MMC_CTRL__SEND_IRQ_RESPONSE_WIDTH 1
#define MMC_CTRL__SEND_IRQ_RESPONSE_RESET_VAL 0
#define MMC_CTRL__SEND_IRQ_RESPONSE_RMASK 0x1
#define MMC_CTRL__SEND_IRQ_RESPONSE_MASK  0x80
#define MMC_CTRL__SEND_IRQ_RESPONSE_FIELD 7,7

#define MMC_CTRL__ABORT_READ_DATA_SHIFT 8
#define MMC_CTRL__ABORT_READ_DATA_WIDTH 1
#define MMC_CTRL__ABORT_READ_DATA_RESET_VAL 0
#define MMC_CTRL__ABORT_READ_DATA_RMASK 0x1
#define MMC_CTRL__ABORT_READ_DATA_MASK  0x100
#define MMC_CTRL__ABORT_READ_DATA_FIELD 8,8

#define MMC_CTRL__SEND_CCSD_SHIFT 9
#define MMC_CTRL__SEND_CCSD_WIDTH 1
#define MMC_CTRL__SEND_CCSD_RESET_VAL 0
#define MMC_CTRL__SEND_CCSD_RMASK 0x1
#define MMC_CTRL__SEND_CCSD_MASK  0x200
#define MMC_CTRL__SEND_CCSD_FIELD 9,9

#define MMC_CTRL__SEND_AUTO_STOP_CCSD_SHIFT 10
#define MMC_CTRL__SEND_AUTO_STOP_CCSD_WIDTH 1
#define MMC_CTRL__SEND_AUTO_STOP_CCSD_RESET_VAL 0
#define MMC_CTRL__SEND_AUTO_STOP_CCSD_RMASK 0x1
#define MMC_CTRL__SEND_AUTO_STOP_CCSD_MASK  0x400
#define MMC_CTRL__SEND_AUTO_STOP_CCSD_FIELD 10,10

#define MMC_CTRL__CEATA_DEVICE_INTERRUPT_STATUS_SHIFT 11
#define MMC_CTRL__CEATA_DEVICE_INTERRUPT_STATUS_WIDTH 1
#define MMC_CTRL__CEATA_DEVICE_INTERRUPT_STATUS_RESET_VAL 0
#define MMC_CTRL__CEATA_DEVICE_INTERRUPT_STATUS_RMASK 0x1
#define MMC_CTRL__CEATA_DEVICE_INTERRUPT_STATUS_MASK  0x800
#define MMC_CTRL__CEATA_DEVICE_INTERRUPT_STATUS_FIELD 11,11

#define MMC_CTRL__CARD_VOLTAGE_A_SHIFT 16
#define MMC_CTRL__CARD_VOLTAGE_A_WIDTH 4
#define MMC_CTRL__CARD_VOLTAGE_A_RESET_VAL 0
#define MMC_CTRL__CARD_VOLTAGE_A_RMASK 0xf
#define MMC_CTRL__CARD_VOLTAGE_A_MASK  0xf0000
#define MMC_CTRL__CARD_VOLTAGE_A_FIELD 16,19

#define MMC_CTRL__CARD_VOLTAGE_B_SHIFT 20
#define MMC_CTRL__CARD_VOLTAGE_B_WIDTH 4
#define MMC_CTRL__CARD_VOLTAGE_B_RESET_VAL 0
#define MMC_CTRL__CARD_VOLTAGE_B_RMASK 0xf
#define MMC_CTRL__CARD_VOLTAGE_B_MASK  0xf00000
#define MMC_CTRL__CARD_VOLTAGE_B_FIELD 20,23

#define MMC_CTRL__ENABLE_OD_PULLUP_SHIFT 24
#define MMC_CTRL__ENABLE_OD_PULLUP_WIDTH 1
#define MMC_CTRL__ENABLE_OD_PULLUP_RESET_VAL 0
#define MMC_CTRL__ENABLE_OD_PULLUP_RMASK 0x1
#define MMC_CTRL__ENABLE_OD_PULLUP_MASK  0x1000000
#define MMC_CTRL__ENABLE_OD_PULLUP_FIELD 24,24

#define MMC_CTRL__USE_INTERNAL_DMAC_SHIFT 25
#define MMC_CTRL__USE_INTERNAL_DMAC_WIDTH 1
#define MMC_CTRL__USE_INTERNAL_DMAC_RESET_VAL 0
#define MMC_CTRL__USE_INTERNAL_DMAC_RMASK 0x1
#define MMC_CTRL__USE_INTERNAL_DMAC_MASK  0x2000000
#define MMC_CTRL__USE_INTERNAL_DMAC_FIELD 25,25


/*
 * PWREN.
 */
#define MMC_PWREN 0x8004
#define MMC_PWREN__LENGTH 0x0001

#define MMC_PWREN__POWER_ENABLE_SHIFT 0
#define MMC_PWREN__POWER_ENABLE_WIDTH 2
#define MMC_PWREN__POWER_ENABLE_RESET_VAL 0
#define MMC_PWREN__POWER_ENABLE_RMASK 0x3
#define MMC_PWREN__POWER_ENABLE_MASK  0x3
#define MMC_PWREN__POWER_ENABLE_FIELD 0,1


/*
 * CLKDIV.
 */
#define MMC_CLKDIV 0x8008
#define MMC_CLKDIV__LENGTH 0x0001

#define MMC_CLKDIV__CLK_DIVIDER0_SHIFT 0
#define MMC_CLKDIV__CLK_DIVIDER0_WIDTH 8
#define MMC_CLKDIV__CLK_DIVIDER0_RESET_VAL 0
#define MMC_CLKDIV__CLK_DIVIDER0_RMASK 0xff
#define MMC_CLKDIV__CLK_DIVIDER0_MASK  0xff
#define MMC_CLKDIV__CLK_DIVIDER0_FIELD 0,7

#define MMC_CLKDIV__CLK_DIVIDER1_SHIFT 8
#define MMC_CLKDIV__CLK_DIVIDER1_WIDTH 8
#define MMC_CLKDIV__CLK_DIVIDER1_RESET_VAL 0
#define MMC_CLKDIV__CLK_DIVIDER1_RMASK 0xff
#define MMC_CLKDIV__CLK_DIVIDER1_MASK  0xff00
#define MMC_CLKDIV__CLK_DIVIDER1_FIELD 8,15

#define MMC_CLKDIV__CLK_DIVIDER2_SHIFT 16
#define MMC_CLKDIV__CLK_DIVIDER2_WIDTH 8
#define MMC_CLKDIV__CLK_DIVIDER2_RESET_VAL 0
#define MMC_CLKDIV__CLK_DIVIDER2_RMASK 0xff
#define MMC_CLKDIV__CLK_DIVIDER2_MASK  0xff0000
#define MMC_CLKDIV__CLK_DIVIDER2_FIELD 16,23

#define MMC_CLKDIV__CLK_DIVIDER3_SHIFT 24
#define MMC_CLKDIV__CLK_DIVIDER3_WIDTH 8
#define MMC_CLKDIV__CLK_DIVIDER3_RESET_VAL 0
#define MMC_CLKDIV__CLK_DIVIDER3_RMASK 0xff
#define MMC_CLKDIV__CLK_DIVIDER3_MASK  0xff000000
#define MMC_CLKDIV__CLK_DIVIDER3_FIELD 24,31


/*
 * CLKSRC.
 */
#define MMC_CLKSRC 0x800c
#define MMC_CLKSRC__LENGTH 0x0001

#define MMC_CLKSRC__CLK_SOURCE_SHIFT 0
#define MMC_CLKSRC__CLK_SOURCE_WIDTH 32
#define MMC_CLKSRC__CLK_SOURCE_RESET_VAL 0
#define MMC_CLKSRC__CLK_SOURCE_RMASK 0xffffffff
#define MMC_CLKSRC__CLK_SOURCE_MASK  0xffffffff
#define MMC_CLKSRC__CLK_SOURCE_FIELD 0,31


/*
 * CLKENA.
 */
#define MMC_CLKENA 0x8010
#define MMC_CLKENA__LENGTH 0x0001

#define MMC_CLKENA__CCLK_ENABLE_SHIFT 0
#define MMC_CLKENA__CCLK_ENABLE_WIDTH 16
#define MMC_CLKENA__CCLK_ENABLE_RESET_VAL 0
#define MMC_CLKENA__CCLK_ENABLE_RMASK 0xffff
#define MMC_CLKENA__CCLK_ENABLE_MASK  0xffff
#define MMC_CLKENA__CCLK_ENABLE_FIELD 0,15

#define MMC_CLKENA__CCLK_LOW_POWER_SHIFT 16
#define MMC_CLKENA__CCLK_LOW_POWER_WIDTH 16
#define MMC_CLKENA__CCLK_LOW_POWER_RESET_VAL 0
#define MMC_CLKENA__CCLK_LOW_POWER_RMASK 0xffff
#define MMC_CLKENA__CCLK_LOW_POWER_MASK  0xffff0000
#define MMC_CLKENA__CCLK_LOW_POWER_FIELD 16,31


/*
 * TMOUT.
 */
#define MMC_TMOUT 0x8014
#define MMC_TMOUT__LENGTH 0x0001

#define MMC_TMOUT__RESPONSE_TIMEOUT_SHIFT 0
#define MMC_TMOUT__RESPONSE_TIMEOUT_WIDTH 8
#define MMC_TMOUT__RESPONSE_TIMEOUT_RESET_VAL 0
#define MMC_TMOUT__RESPONSE_TIMEOUT_RMASK 0xff
#define MMC_TMOUT__RESPONSE_TIMEOUT_MASK  0xff
#define MMC_TMOUT__RESPONSE_TIMEOUT_FIELD 0,7

#define MMC_TMOUT__DATA_TIMEOUT_SHIFT 8
#define MMC_TMOUT__DATA_TIMEOUT_WIDTH 24
#define MMC_TMOUT__DATA_TIMEOUT_RESET_VAL 0
#define MMC_TMOUT__DATA_TIMEOUT_RMASK 0xffffff
#define MMC_TMOUT__DATA_TIMEOUT_MASK  0xffffff00
#define MMC_TMOUT__DATA_TIMEOUT_FIELD 8,31


/*
 * CTYPE.
 */
#define MMC_CTYPE 0x8018
#define MMC_CTYPE__LENGTH 0x0001

#define MMC_CTYPE__CARD_WIDTH2_SHIFT 0
#define MMC_CTYPE__CARD_WIDTH2_WIDTH 2
#define MMC_CTYPE__CARD_WIDTH2_RESET_VAL 0
#define MMC_CTYPE__CARD_WIDTH2_RMASK 0x3
#define MMC_CTYPE__CARD_WIDTH2_MASK  0x3
#define MMC_CTYPE__CARD_WIDTH2_FIELD 0,1

#define MMC_CTYPE__CARD_WIDTH1_SHIFT 16
#define MMC_CTYPE__CARD_WIDTH1_WIDTH 2
#define MMC_CTYPE__CARD_WIDTH1_RESET_VAL 0
#define MMC_CTYPE__CARD_WIDTH1_RMASK 0x3
#define MMC_CTYPE__CARD_WIDTH1_MASK  0x30000
#define MMC_CTYPE__CARD_WIDTH1_FIELD 16,17


/*
 * BLKSIZ.
 */
#define MMC_BLKSIZ 0x801c
#define MMC_BLKSIZ__LENGTH 0x0001

#define MMC_BLKSIZ__BLOCK_SIZE_SHIFT 0
#define MMC_BLKSIZ__BLOCK_SIZE_WIDTH 16
#define MMC_BLKSIZ__BLOCK_SIZE_RESET_VAL 0
#define MMC_BLKSIZ__BLOCK_SIZE_RMASK 0xffff
#define MMC_BLKSIZ__BLOCK_SIZE_MASK  0xffff
#define MMC_BLKSIZ__BLOCK_SIZE_FIELD 0,15


/*
 * BYTCNT.
 */
#define MMC_BYTCNT 0x8020
#define MMC_BYTCNT__LENGTH 0x0001

#define MMC_BYTCNT__BYTE_COUNT_SHIFT 0
#define MMC_BYTCNT__BYTE_COUNT_WIDTH 32
#define MMC_BYTCNT__BYTE_COUNT_RESET_VAL 0
#define MMC_BYTCNT__BYTE_COUNT_RMASK 0xffffffff
#define MMC_BYTCNT__BYTE_COUNT_MASK  0xffffffff
#define MMC_BYTCNT__BYTE_COUNT_FIELD 0,31


/*
 * INTMASK.
 */
#define MMC_INTMASK 0x8024
#define MMC_INTMASK__LENGTH 0x0001

#define MMC_INTMASK__INT_MASK_SHIFT 0
#define MMC_INTMASK__INT_MASK_WIDTH 16
#define MMC_INTMASK__INT_MASK_RESET_VAL 0
#define MMC_INTMASK__INT_MASK_RMASK 0xffff
#define MMC_INTMASK__INT_MASK_MASK  0xffff
#define MMC_INTMASK__INT_MASK_FIELD 0,15

#define MMC_INTMASK__SDIO_INT_MASK_SHIFT 16
#define MMC_INTMASK__SDIO_INT_MASK_WIDTH 16
#define MMC_INTMASK__SDIO_INT_MASK_RESET_VAL 0
#define MMC_INTMASK__SDIO_INT_MASK_RMASK 0xffff
#define MMC_INTMASK__SDIO_INT_MASK_MASK  0xffff0000
#define MMC_INTMASK__SDIO_INT_MASK_FIELD 16,31


/*
 * CMDARG.
 */
#define MMC_CMDARG 0x8028
#define MMC_CMDARG__LENGTH 0x0001

#define MMC_CMDARG__CMD_ARG_SHIFT 0
#define MMC_CMDARG__CMD_ARG_WIDTH 32
#define MMC_CMDARG__CMD_ARG_RESET_VAL 0
#define MMC_CMDARG__CMD_ARG_RMASK 0xffffffff
#define MMC_CMDARG__CMD_ARG_MASK  0xffffffff
#define MMC_CMDARG__CMD_ARG_FIELD 0,31


/*
 * CMD.
 */
#define MMC_CMD 0x802c
#define MMC_CMD__LENGTH 0x0001

#define MMC_CMD__CMD_INDEX_SHIFT 0
#define MMC_CMD__CMD_INDEX_WIDTH 6
#define MMC_CMD__CMD_INDEX_RESET_VAL 0
#define MMC_CMD__CMD_INDEX_RMASK 0x3f
#define MMC_CMD__CMD_INDEX_MASK  0x3f
#define MMC_CMD__CMD_INDEX_FIELD 0,5

#define MMC_CMD__RESPONSE_EXPECT_SHIFT 6
#define MMC_CMD__RESPONSE_EXPECT_WIDTH 1
#define MMC_CMD__RESPONSE_EXPECT_RESET_VAL 0
#define MMC_CMD__RESPONSE_EXPECT_RMASK 0x1
#define MMC_CMD__RESPONSE_EXPECT_MASK  0x40
#define MMC_CMD__RESPONSE_EXPECT_FIELD 6,6

#define MMC_CMD__RESPONSE_LENGTH_SHIFT 7
#define MMC_CMD__RESPONSE_LENGTH_WIDTH 1
#define MMC_CMD__RESPONSE_LENGTH_RESET_VAL 0
#define MMC_CMD__RESPONSE_LENGTH_RMASK 0x1
#define MMC_CMD__RESPONSE_LENGTH_MASK  0x80
#define MMC_CMD__RESPONSE_LENGTH_FIELD 7,7

#define MMC_CMD__CHECK_RESPONSE_CRC_SHIFT 8
#define MMC_CMD__CHECK_RESPONSE_CRC_WIDTH 1
#define MMC_CMD__CHECK_RESPONSE_CRC_RESET_VAL 0
#define MMC_CMD__CHECK_RESPONSE_CRC_RMASK 0x1
#define MMC_CMD__CHECK_RESPONSE_CRC_MASK  0x100
#define MMC_CMD__CHECK_RESPONSE_CRC_FIELD 8,8

#define MMC_CMD__DATA_EXPECTED_SHIFT 9
#define MMC_CMD__DATA_EXPECTED_WIDTH 1
#define MMC_CMD__DATA_EXPECTED_RESET_VAL 0
#define MMC_CMD__DATA_EXPECTED_RMASK 0x1
#define MMC_CMD__DATA_EXPECTED_MASK  0x200
#define MMC_CMD__DATA_EXPECTED_FIELD 9,9

#define MMC_CMD__READ_WRITE_SHIFT 10
#define MMC_CMD__READ_WRITE_WIDTH 1
#define MMC_CMD__READ_WRITE_RESET_VAL 0
#define MMC_CMD__READ_WRITE_RMASK 0x1
#define MMC_CMD__READ_WRITE_MASK  0x400
#define MMC_CMD__READ_WRITE_FIELD 10,10

#define MMC_CMD__TRANSFER_MODE_SHIFT 11
#define MMC_CMD__TRANSFER_MODE_WIDTH 1
#define MMC_CMD__TRANSFER_MODE_RESET_VAL 0
#define MMC_CMD__TRANSFER_MODE_RMASK 0x1
#define MMC_CMD__TRANSFER_MODE_MASK  0x800
#define MMC_CMD__TRANSFER_MODE_FIELD 11,11

#define MMC_CMD__SEND_AUTO_STOP_SHIFT 12
#define MMC_CMD__SEND_AUTO_STOP_WIDTH 1
#define MMC_CMD__SEND_AUTO_STOP_RESET_VAL 0
#define MMC_CMD__SEND_AUTO_STOP_RMASK 0x1
#define MMC_CMD__SEND_AUTO_STOP_MASK  0x1000
#define MMC_CMD__SEND_AUTO_STOP_FIELD 12,12

#define MMC_CMD__WAIT_PRVDATA_COMPLETE_SHIFT 13
#define MMC_CMD__WAIT_PRVDATA_COMPLETE_WIDTH 1
#define MMC_CMD__WAIT_PRVDATA_COMPLETE_RESET_VAL 0
#define MMC_CMD__WAIT_PRVDATA_COMPLETE_RMASK 0x1
#define MMC_CMD__WAIT_PRVDATA_COMPLETE_MASK  0x2000
#define MMC_CMD__WAIT_PRVDATA_COMPLETE_FIELD 13,13

#define MMC_CMD__STOP_ABORT_CMD_SHIFT 14
#define MMC_CMD__STOP_ABORT_CMD_WIDTH 1
#define MMC_CMD__STOP_ABORT_CMD_RESET_VAL 0
#define MMC_CMD__STOP_ABORT_CMD_RMASK 0x1
#define MMC_CMD__STOP_ABORT_CMD_MASK  0x4000
#define MMC_CMD__STOP_ABORT_CMD_FIELD 14,14

#define MMC_CMD__SEND_INITIALIZATION_SHIFT 15
#define MMC_CMD__SEND_INITIALIZATION_WIDTH 1
#define MMC_CMD__SEND_INITIALIZATION_RESET_VAL 0
#define MMC_CMD__SEND_INITIALIZATION_RMASK 0x1
#define MMC_CMD__SEND_INITIALIZATION_MASK  0x8000
#define MMC_CMD__SEND_INITIALIZATION_FIELD 15,15

#define MMC_CMD__CARD_NUMBER_SHIFT 16
#define MMC_CMD__CARD_NUMBER_WIDTH 5
#define MMC_CMD__CARD_NUMBER_RESET_VAL 0
#define MMC_CMD__CARD_NUMBER_RMASK 0x1f
#define MMC_CMD__CARD_NUMBER_MASK  0x1f0000
#define MMC_CMD__CARD_NUMBER_FIELD 16,20

#define MMC_CMD__UPDATE_CLOCK_REGISTERS_ONLY_SHIFT 21
#define MMC_CMD__UPDATE_CLOCK_REGISTERS_ONLY_WIDTH 1
#define MMC_CMD__UPDATE_CLOCK_REGISTERS_ONLY_RESET_VAL 0
#define MMC_CMD__UPDATE_CLOCK_REGISTERS_ONLY_RMASK 0x1
#define MMC_CMD__UPDATE_CLOCK_REGISTERS_ONLY_MASK  0x200000
#define MMC_CMD__UPDATE_CLOCK_REGISTERS_ONLY_FIELD 21,21

#define MMC_CMD__READ_CEATA_DEVICE_SHIFT 22
#define MMC_CMD__READ_CEATA_DEVICE_WIDTH 1
#define MMC_CMD__READ_CEATA_DEVICE_RESET_VAL 0
#define MMC_CMD__READ_CEATA_DEVICE_RMASK 0x1
#define MMC_CMD__READ_CEATA_DEVICE_MASK  0x400000
#define MMC_CMD__READ_CEATA_DEVICE_FIELD 22,22

#define MMC_CMD__CCS_EXPECTED_SHIFT 23
#define MMC_CMD__CCS_EXPECTED_WIDTH 1
#define MMC_CMD__CCS_EXPECTED_RESET_VAL 0
#define MMC_CMD__CCS_EXPECTED_RMASK 0x1
#define MMC_CMD__CCS_EXPECTED_MASK  0x800000
#define MMC_CMD__CCS_EXPECTED_FIELD 23,23

#define MMC_CMD__ENABLE_BOOT_SHIFT 24
#define MMC_CMD__ENABLE_BOOT_WIDTH 1
#define MMC_CMD__ENABLE_BOOT_RESET_VAL 0
#define MMC_CMD__ENABLE_BOOT_RMASK 0x1
#define MMC_CMD__ENABLE_BOOT_MASK  0x1000000
#define MMC_CMD__ENABLE_BOOT_FIELD 24,24

#define MMC_CMD__EXPECT_BOOT_ACK_SHIFT 25
#define MMC_CMD__EXPECT_BOOT_ACK_WIDTH 1
#define MMC_CMD__EXPECT_BOOT_ACK_RESET_VAL 0
#define MMC_CMD__EXPECT_BOOT_ACK_RMASK 0x1
#define MMC_CMD__EXPECT_BOOT_ACK_MASK  0x2000000
#define MMC_CMD__EXPECT_BOOT_ACK_FIELD 25,25

#define MMC_CMD__DISABLE_BOOT_SHIFT 26
#define MMC_CMD__DISABLE_BOOT_WIDTH 1
#define MMC_CMD__DISABLE_BOOT_RESET_VAL 0
#define MMC_CMD__DISABLE_BOOT_RMASK 0x1
#define MMC_CMD__DISABLE_BOOT_MASK  0x4000000
#define MMC_CMD__DISABLE_BOOT_FIELD 26,26

#define MMC_CMD__BOOT_MODE_SHIFT 27
#define MMC_CMD__BOOT_MODE_WIDTH 1
#define MMC_CMD__BOOT_MODE_RESET_VAL 0
#define MMC_CMD__BOOT_MODE_RMASK 0x1
#define MMC_CMD__BOOT_MODE_MASK  0x8000000
#define MMC_CMD__BOOT_MODE_FIELD 27,27

#define MMC_CMD__VOLT_SWITCH_SHIFT 28
#define MMC_CMD__VOLT_SWITCH_WIDTH 1
#define MMC_CMD__VOLT_SWITCH_RESET_VAL 0
#define MMC_CMD__VOLT_SWITCH_RMASK 0x1
#define MMC_CMD__VOLT_SWITCH_MASK  0x10000000
#define MMC_CMD__VOLT_SWITCH_FIELD 28,28

#define MMC_CMD__USE_HOLD_REG_SHIFT 29
#define MMC_CMD__USE_HOLD_REG_WIDTH 1
#define MMC_CMD__USE_HOLD_REG_RESET_VAL 0
#define MMC_CMD__USE_HOLD_REG_RMASK 0x1
#define MMC_CMD__USE_HOLD_REG_MASK  0x20000000
#define MMC_CMD__USE_HOLD_REG_FIELD 29,29

#define MMC_CMD__START_CMD_SHIFT 31
#define MMC_CMD__START_CMD_WIDTH 1
#define MMC_CMD__START_CMD_RESET_VAL 0
#define MMC_CMD__START_CMD_RMASK 0x1
#define MMC_CMD__START_CMD_MASK  0x80000000
#define MMC_CMD__START_CMD_FIELD 31,31


/*
 * RESP0.
 */
#define MMC_RESP0 0x8030
#define MMC_RESP0__LENGTH 0x0001

#define MMC_RESP0__RESPONSE0_SHIFT 0
#define MMC_RESP0__RESPONSE0_WIDTH 32
#define MMC_RESP0__RESPONSE0_RESET_VAL 0
#define MMC_RESP0__RESPONSE0_RMASK 0xffffffff
#define MMC_RESP0__RESPONSE0_MASK  0xffffffff
#define MMC_RESP0__RESPONSE0_FIELD 0,31


/*
 * RESP1.
 */
#define MMC_RESP1 0x8034
#define MMC_RESP1__LENGTH 0x0001

#define MMC_RESP1__RESPONSE1_SHIFT 0
#define MMC_RESP1__RESPONSE1_WIDTH 32
#define MMC_RESP1__RESPONSE1_RESET_VAL 0
#define MMC_RESP1__RESPONSE1_RMASK 0xffffffff
#define MMC_RESP1__RESPONSE1_MASK  0xffffffff
#define MMC_RESP1__RESPONSE1_FIELD 0,31


/*
 * RESP2.
 */
#define MMC_RESP2 0x8038
#define MMC_RESP2__LENGTH 0x0001

#define MMC_RESP2__RESPONSE2_SHIFT 0
#define MMC_RESP2__RESPONSE2_WIDTH 32
#define MMC_RESP2__RESPONSE2_RESET_VAL 0
#define MMC_RESP2__RESPONSE2_RMASK 0xffffffff
#define MMC_RESP2__RESPONSE2_MASK  0xffffffff
#define MMC_RESP2__RESPONSE2_FIELD 0,31


/*
 * RESP3.
 */
#define MMC_RESP3 0x803c
#define MMC_RESP3__LENGTH 0x0001

#define MMC_RESP3__RESPONSE3_SHIFT 0
#define MMC_RESP3__RESPONSE3_WIDTH 32
#define MMC_RESP3__RESPONSE3_RESET_VAL 0
#define MMC_RESP3__RESPONSE3_RMASK 0xffffffff
#define MMC_RESP3__RESPONSE3_MASK  0xffffffff
#define MMC_RESP3__RESPONSE3_FIELD 0,31


/*
 * MINTSTS.
 */
#define MMC_MINTSTS 0x8040
#define MMC_MINTSTS__LENGTH 0x0001

#define MMC_MINTSTS__INT_STATUS_SHIFT 0
#define MMC_MINTSTS__INT_STATUS_WIDTH 16
#define MMC_MINTSTS__INT_STATUS_RESET_VAL 0
#define MMC_MINTSTS__INT_STATUS_RMASK 0xffff
#define MMC_MINTSTS__INT_STATUS_MASK  0xffff
#define MMC_MINTSTS__INT_STATUS_FIELD 0,15

#define MMC_MINTSTS__SDIO_INTERRUPT_SHIFT 16
#define MMC_MINTSTS__SDIO_INTERRUPT_WIDTH 16
#define MMC_MINTSTS__SDIO_INTERRUPT_RESET_VAL 0
#define MMC_MINTSTS__SDIO_INTERRUPT_RMASK 0xffff
#define MMC_MINTSTS__SDIO_INTERRUPT_MASK  0xffff0000
#define MMC_MINTSTS__SDIO_INTERRUPT_FIELD 16,31


/*
 * RINTSTS.
 */
#define MMC_RINTSTS 0x8044
#define MMC_RINTSTS__LENGTH 0x0001

#define MMC_RINTSTS__INT_STATUS_SHIFT 0
#define MMC_RINTSTS__INT_STATUS_WIDTH 16
#define MMC_RINTSTS__INT_STATUS_RESET_VAL 0
#define MMC_RINTSTS__INT_STATUS_RMASK 0xffff
#define MMC_RINTSTS__INT_STATUS_MASK  0xffff
#define MMC_RINTSTS__INT_STATUS_FIELD 0,15

#define MMC_RINTSTS__SDIO_INTERRUPT_SHIFT 16
#define MMC_RINTSTS__SDIO_INTERRUPT_WIDTH 16
#define MMC_RINTSTS__SDIO_INTERRUPT_RESET_VAL 0
#define MMC_RINTSTS__SDIO_INTERRUPT_RMASK 0xffff
#define MMC_RINTSTS__SDIO_INTERRUPT_MASK  0xffff0000
#define MMC_RINTSTS__SDIO_INTERRUPT_FIELD 16,31


/*
 * STATUS.
 */
#define MMC_STATUS 0x8048
#define MMC_STATUS__LENGTH 0x0001

#define MMC_STATUS__FIFO_RX_WATERMARK_SHIFT 0
#define MMC_STATUS__FIFO_RX_WATERMARK_WIDTH 1
#define MMC_STATUS__FIFO_RX_WATERMARK_RESET_VAL 0
#define MMC_STATUS__FIFO_RX_WATERMARK_RMASK 0x1
#define MMC_STATUS__FIFO_RX_WATERMARK_MASK  0x1
#define MMC_STATUS__FIFO_RX_WATERMARK_FIELD 0,0

#define MMC_STATUS__FIFO_TX_WATERMARK_SHIFT 1
#define MMC_STATUS__FIFO_TX_WATERMARK_WIDTH 1
#define MMC_STATUS__FIFO_TX_WATERMARK_RESET_VAL 0
#define MMC_STATUS__FIFO_TX_WATERMARK_RMASK 0x1
#define MMC_STATUS__FIFO_TX_WATERMARK_MASK  0x2
#define MMC_STATUS__FIFO_TX_WATERMARK_FIELD 1,1

#define MMC_STATUS__FIFO_EMPTY_SHIFT 2
#define MMC_STATUS__FIFO_EMPTY_WIDTH 1
#define MMC_STATUS__FIFO_EMPTY_RESET_VAL 0
#define MMC_STATUS__FIFO_EMPTY_RMASK 0x1
#define MMC_STATUS__FIFO_EMPTY_MASK  0x4
#define MMC_STATUS__FIFO_EMPTY_FIELD 2,2

#define MMC_STATUS__FIFO_FULL_SHIFT 3
#define MMC_STATUS__FIFO_FULL_WIDTH 1
#define MMC_STATUS__FIFO_FULL_RESET_VAL 0
#define MMC_STATUS__FIFO_FULL_RMASK 0x1
#define MMC_STATUS__FIFO_FULL_MASK  0x8
#define MMC_STATUS__FIFO_FULL_FIELD 3,3

#define MMC_STATUS__COMMAND_FSM_STATES_SHIFT 4
#define MMC_STATUS__COMMAND_FSM_STATES_WIDTH 4
#define MMC_STATUS__COMMAND_FSM_STATES_RESET_VAL 0
#define MMC_STATUS__COMMAND_FSM_STATES_RMASK 0xf
#define MMC_STATUS__COMMAND_FSM_STATES_MASK  0xf0
#define MMC_STATUS__COMMAND_FSM_STATES_FIELD 4,7

#define MMC_STATUS__DATA_3_STATUS_SHIFT 8
#define MMC_STATUS__DATA_3_STATUS_WIDTH 1
#define MMC_STATUS__DATA_3_STATUS_RESET_VAL 0
#define MMC_STATUS__DATA_3_STATUS_RMASK 0x1
#define MMC_STATUS__DATA_3_STATUS_MASK  0x100
#define MMC_STATUS__DATA_3_STATUS_FIELD 8,8

#define MMC_STATUS__DATA_BUSY_SHIFT 9
#define MMC_STATUS__DATA_BUSY_WIDTH 1
#define MMC_STATUS__DATA_BUSY_RESET_VAL 0
#define MMC_STATUS__DATA_BUSY_RMASK 0x1
#define MMC_STATUS__DATA_BUSY_MASK  0x200
#define MMC_STATUS__DATA_BUSY_FIELD 9,9

#define MMC_STATUS__DATA_STATE_MC_BUSY_SHIFT 10
#define MMC_STATUS__DATA_STATE_MC_BUSY_WIDTH 1
#define MMC_STATUS__DATA_STATE_MC_BUSY_RESET_VAL 0
#define MMC_STATUS__DATA_STATE_MC_BUSY_RMASK 0x1
#define MMC_STATUS__DATA_STATE_MC_BUSY_MASK  0x400
#define MMC_STATUS__DATA_STATE_MC_BUSY_FIELD 10,10

#define MMC_STATUS__RESPONSE_INDEX_SHIFT 11
#define MMC_STATUS__RESPONSE_INDEX_WIDTH 6
#define MMC_STATUS__RESPONSE_INDEX_RESET_VAL 0
#define MMC_STATUS__RESPONSE_INDEX_RMASK 0x3f
#define MMC_STATUS__RESPONSE_INDEX_MASK  0x1f800
#define MMC_STATUS__RESPONSE_INDEX_FIELD 11,16

#define MMC_STATUS__FIFO_COUNT_SHIFT 17
#define MMC_STATUS__FIFO_COUNT_WIDTH 13
#define MMC_STATUS__FIFO_COUNT_RESET_VAL 0
#define MMC_STATUS__FIFO_COUNT_RMASK 0x1fff
#define MMC_STATUS__FIFO_COUNT_MASK  0x3ffe0000
#define MMC_STATUS__FIFO_COUNT_FIELD 17,29

#define MMC_STATUS__DMA_ACK_SHIFT 30
#define MMC_STATUS__DMA_ACK_WIDTH 1
#define MMC_STATUS__DMA_ACK_RESET_VAL 0
#define MMC_STATUS__DMA_ACK_RMASK 0x1
#define MMC_STATUS__DMA_ACK_MASK  0x40000000
#define MMC_STATUS__DMA_ACK_FIELD 30,30

#define MMC_STATUS__DMA_REQ_SHIFT 31
#define MMC_STATUS__DMA_REQ_WIDTH 1
#define MMC_STATUS__DMA_REQ_RESET_VAL 0
#define MMC_STATUS__DMA_REQ_RMASK 0x1
#define MMC_STATUS__DMA_REQ_MASK  0x80000000
#define MMC_STATUS__DMA_REQ_FIELD 31,31


/*
 * FIFOTH.
 */
#define MMC_FIFOTH 0x804c
#define MMC_FIFOTH__LENGTH 0x0001

#define MMC_FIFOTH__TX_WMARK_SHIFT 0
#define MMC_FIFOTH__TX_WMARK_WIDTH 12
#define MMC_FIFOTH__TX_WMARK_RESET_VAL 0
#define MMC_FIFOTH__TX_WMARK_RMASK 0xfff
#define MMC_FIFOTH__TX_WMARK_MASK  0xfff
#define MMC_FIFOTH__TX_WMARK_FIELD 0,11

#define MMC_FIFOTH__RX_WMARK_SHIFT 16
#define MMC_FIFOTH__RX_WMARK_WIDTH 12
#define MMC_FIFOTH__RX_WMARK_RESET_VAL 0
#define MMC_FIFOTH__RX_WMARK_RMASK 0xfff
#define MMC_FIFOTH__RX_WMARK_MASK  0xfff0000
#define MMC_FIFOTH__RX_WMARK_FIELD 16,27

#define MMC_FIFOTH__DW_DMA_MULTIPLE_TRANSACTION_SIZE_SHIFT 28
#define MMC_FIFOTH__DW_DMA_MULTIPLE_TRANSACTION_SIZE_WIDTH 3
#define MMC_FIFOTH__DW_DMA_MULTIPLE_TRANSACTION_SIZE_RESET_VAL 0
#define MMC_FIFOTH__DW_DMA_MULTIPLE_TRANSACTION_SIZE_RMASK 0x7
#define MMC_FIFOTH__DW_DMA_MULTIPLE_TRANSACTION_SIZE_MASK  0x70000000
#define MMC_FIFOTH__DW_DMA_MULTIPLE_TRANSACTION_SIZE_FIELD 28,30


/*
 * CDETECT.
 */
#define MMC_CDETECT 0x8050
#define MMC_CDETECT__LENGTH 0x0001

#define MMC_CDETECT__CARD_DETECT_N_SHIFT 0
#define MMC_CDETECT__CARD_DETECT_N_WIDTH 2
#define MMC_CDETECT__CARD_DETECT_N_RESET_VAL 0
#define MMC_CDETECT__CARD_DETECT_N_RMASK 0x3
#define MMC_CDETECT__CARD_DETECT_N_MASK  0x3
#define MMC_CDETECT__CARD_DETECT_N_FIELD 0,1


/*
 * WRTPRT.
 */
#define MMC_WRTPRT 0x8054
#define MMC_WRTPRT__LENGTH 0x0001

#define MMC_WRTPRT__WRITE_PROTECT_SHIFT 0
#define MMC_WRTPRT__WRITE_PROTECT_WIDTH 1
#define MMC_WRTPRT__WRITE_PROTECT_RESET_VAL 0
#define MMC_WRTPRT__WRITE_PROTECT_RMASK 0x1
#define MMC_WRTPRT__WRITE_PROTECT_MASK  0x1
#define MMC_WRTPRT__WRITE_PROTECT_FIELD 0,0


/*
 * GPIO.
 */
#define MMC_GPIO 0x8058
#define MMC_GPIO__LENGTH 0x0001

#define MMC_GPIO__GPI_SHIFT 0
#define MMC_GPIO__GPI_WIDTH 8
#define MMC_GPIO__GPI_RESET_VAL 0
#define MMC_GPIO__GPI_RMASK 0xff
#define MMC_GPIO__GPI_MASK  0xff
#define MMC_GPIO__GPI_FIELD 0,7

#define MMC_GPIO__GPO_SHIFT 8
#define MMC_GPIO__GPO_WIDTH 16
#define MMC_GPIO__GPO_RESET_VAL 0
#define MMC_GPIO__GPO_RMASK 0xffff
#define MMC_GPIO__GPO_MASK  0xffff00
#define MMC_GPIO__GPO_FIELD 8,23


/*
 * TCBCNT.
 */
#define MMC_TCBCNT 0x805c
#define MMC_TCBCNT__LENGTH 0x0001

#define MMC_TCBCNT__TRANS_CARD_BYTE_COUNT_SHIFT 0
#define MMC_TCBCNT__TRANS_CARD_BYTE_COUNT_WIDTH 32
#define MMC_TCBCNT__TRANS_CARD_BYTE_COUNT_RESET_VAL 0
#define MMC_TCBCNT__TRANS_CARD_BYTE_COUNT_RMASK 0xffffffff
#define MMC_TCBCNT__TRANS_CARD_BYTE_COUNT_MASK  0xffffffff
#define MMC_TCBCNT__TRANS_CARD_BYTE_COUNT_FIELD 0,31


/*
 * TBBCNT.
 */
#define MMC_TBBCNT 0x8060
#define MMC_TBBCNT__LENGTH 0x0001

#define MMC_TBBCNT__TRANS_FIFO_BYTE_COUNT_SHIFT 0
#define MMC_TBBCNT__TRANS_FIFO_BYTE_COUNT_WIDTH 32
#define MMC_TBBCNT__TRANS_FIFO_BYTE_COUNT_RESET_VAL 0
#define MMC_TBBCNT__TRANS_FIFO_BYTE_COUNT_RMASK 0xffffffff
#define MMC_TBBCNT__TRANS_FIFO_BYTE_COUNT_MASK  0xffffffff
#define MMC_TBBCNT__TRANS_FIFO_BYTE_COUNT_FIELD 0,31


/*
 * DEBNCE.
 */
#define MMC_DEBNCE 0x8064
#define MMC_DEBNCE__LENGTH 0x0001

#define MMC_DEBNCE__DEBOUNCE_COUNT_SHIFT 0
#define MMC_DEBNCE__DEBOUNCE_COUNT_WIDTH 24
#define MMC_DEBNCE__DEBOUNCE_COUNT_RESET_VAL 0
#define MMC_DEBNCE__DEBOUNCE_COUNT_RMASK 0xffffff
#define MMC_DEBNCE__DEBOUNCE_COUNT_MASK  0xffffff
#define MMC_DEBNCE__DEBOUNCE_COUNT_FIELD 0,23


/*
 * USRID.
 */
#define MMC_USRID 0x8068
#define MMC_USRID__LENGTH 0x0001

#define MMC_USRID__USR_ID_SHIFT 0
#define MMC_USRID__USR_ID_WIDTH 32
#define MMC_USRID__USR_ID_RESET_VAL 0
#define MMC_USRID__USR_ID_RMASK 0xffffffff
#define MMC_USRID__USR_ID_MASK  0xffffffff
#define MMC_USRID__USR_ID_FIELD 0,31


/*
 * VERID.
 */
#define MMC_VERID 0x806c
#define MMC_VERID__LENGTH 0x0001

#define MMC_VERID__VER_ID_SHIFT 0
#define MMC_VERID__VER_ID_WIDTH 32
#define MMC_VERID__VER_ID_RESET_VAL 0
#define MMC_VERID__VER_ID_RMASK 0xffffffff
#define MMC_VERID__VER_ID_MASK  0xffffffff
#define MMC_VERID__VER_ID_FIELD 0,31


/*
 * HCON.
 */
#define MMC_HCON 0x8070
#define MMC_HCON__LENGTH 0x0001

#define MMC_HCON__H_CON_SHIFT 0
#define MMC_HCON__H_CON_WIDTH 32
#define MMC_HCON__H_CON_RESET_VAL 0
#define MMC_HCON__H_CON_RMASK 0xffffffff
#define MMC_HCON__H_CON_MASK  0xffffffff
#define MMC_HCON__H_CON_FIELD 0,31


/*
 * UHS.
 */
#define MMC_UHS 0x8074
#define MMC_UHS__LENGTH 0x0001

#define MMC_UHS__VOLT_REG_SHIFT 0
#define MMC_UHS__VOLT_REG_WIDTH 16
#define MMC_UHS__VOLT_REG_RESET_VAL 0
#define MMC_UHS__VOLT_REG_RMASK 0xffff
#define MMC_UHS__VOLT_REG_MASK  0xffff
#define MMC_UHS__VOLT_REG_FIELD 0,15

#define MMC_UHS__DDR_REG_SHIFT 16
#define MMC_UHS__DDR_REG_WIDTH 16
#define MMC_UHS__DDR_REG_RESET_VAL 0
#define MMC_UHS__DDR_REG_RMASK 0xffff
#define MMC_UHS__DDR_REG_MASK  0xffff0000
#define MMC_UHS__DDR_REG_FIELD 16,31


/*
 * RST_N.
 */
#define MMC_RST_N 0x8078
#define MMC_RST_N__LENGTH 0x0001

#define MMC_RST_N__CARD_RESET_SHIFT 0
#define MMC_RST_N__CARD_RESET_WIDTH 1
#define MMC_RST_N__CARD_RESET_RESET_VAL 0
#define MMC_RST_N__CARD_RESET_RMASK 0x1
#define MMC_RST_N__CARD_RESET_MASK  0x1
#define MMC_RST_N__CARD_RESET_FIELD 0,0


/*
 * BMOD.
 */
#define MMC_BMOD 0x8080
#define MMC_BMOD__LENGTH 0x0001

#define MMC_BMOD__SWR_SHIFT 0
#define MMC_BMOD__SWR_WIDTH 1
#define MMC_BMOD__SWR_RESET_VAL 0
#define MMC_BMOD__SWR_RMASK 0x1
#define MMC_BMOD__SWR_MASK  0x1
#define MMC_BMOD__SWR_FIELD 0,0

#define MMC_BMOD__FB_SHIFT 1
#define MMC_BMOD__FB_WIDTH 1
#define MMC_BMOD__FB_RESET_VAL 0
#define MMC_BMOD__FB_RMASK 0x1
#define MMC_BMOD__FB_MASK  0x2
#define MMC_BMOD__FB_FIELD 1,1

#define MMC_BMOD__DSL_SHIFT 2
#define MMC_BMOD__DSL_WIDTH 5
#define MMC_BMOD__DSL_RESET_VAL 0
#define MMC_BMOD__DSL_RMASK 0x1f
#define MMC_BMOD__DSL_MASK  0x7c
#define MMC_BMOD__DSL_FIELD 2,6

#define MMC_BMOD__DE_SHIFT 7
#define MMC_BMOD__DE_WIDTH 1
#define MMC_BMOD__DE_RESET_VAL 0
#define MMC_BMOD__DE_RMASK 0x1
#define MMC_BMOD__DE_MASK  0x80
#define MMC_BMOD__DE_FIELD 7,7

#define MMC_BMOD__PBL_SHIFT 8
#define MMC_BMOD__PBL_WIDTH 3
#define MMC_BMOD__PBL_RESET_VAL 0
#define MMC_BMOD__PBL_RMASK 0x7
#define MMC_BMOD__PBL_MASK  0x700
#define MMC_BMOD__PBL_FIELD 8,10


/*
 * PLDMND.
 */
#define MMC_PLDMND 0x8084
#define MMC_PLDMND__LENGTH 0x0001

#define MMC_PLDMND__PD_SHIFT 0
#define MMC_PLDMND__PD_WIDTH 32
#define MMC_PLDMND__PD_RESET_VAL 0
#define MMC_PLDMND__PD_RMASK 0xffffffff
#define MMC_PLDMND__PD_MASK  0xffffffff
#define MMC_PLDMND__PD_FIELD 0,31


/*
 * DBADDRL.
 */
#define MMC_DBADDRL 0x8088
#define MMC_DBADDRL__LENGTH 0x0001

#define MMC_DBADDRL__SDL_SHIFT 0
#define MMC_DBADDRL__SDL_WIDTH 32
#define MMC_DBADDRL__SDL_RESET_VAL 0
#define MMC_DBADDRL__SDL_RMASK 0xffffffff
#define MMC_DBADDRL__SDL_MASK  0xffffffff
#define MMC_DBADDRL__SDL_FIELD 0,31


/*
 * DBADDRU.
 */
#define MMC_DBADDRU 0x808c
#define MMC_DBADDRU__LENGTH 0x0001

#define MMC_DBADDRU__SDLU_SHIFT 0
#define MMC_DBADDRU__SDLU_WIDTH 32
#define MMC_DBADDRU__SDLU_RESET_VAL 0
#define MMC_DBADDRU__SDLU_RMASK 0xffffffff
#define MMC_DBADDRU__SDLU_MASK  0xffffffff
#define MMC_DBADDRU__SDLU_FIELD 0,31


/*
 * IDSTS64.
 */
#define MMC_IDSTS64 0x8090
#define MMC_IDSTS64__LENGTH 0x0001

#define MMC_IDSTS64__TI_SHIFT 0
#define MMC_IDSTS64__TI_WIDTH 1
#define MMC_IDSTS64__TI_RESET_VAL 0
#define MMC_IDSTS64__TI_RMASK 0x1
#define MMC_IDSTS64__TI_MASK  0x1
#define MMC_IDSTS64__TI_FIELD 0,0

#define MMC_IDSTS64__RI_SHIFT 1
#define MMC_IDSTS64__RI_WIDTH 1
#define MMC_IDSTS64__RI_RESET_VAL 0
#define MMC_IDSTS64__RI_RMASK 0x1
#define MMC_IDSTS64__RI_MASK  0x2
#define MMC_IDSTS64__RI_FIELD 1,1

#define MMC_IDSTS64__FBE_SHIFT 2
#define MMC_IDSTS64__FBE_WIDTH 1
#define MMC_IDSTS64__FBE_RESET_VAL 0
#define MMC_IDSTS64__FBE_RMASK 0x1
#define MMC_IDSTS64__FBE_MASK  0x4
#define MMC_IDSTS64__FBE_FIELD 2,2

#define MMC_IDSTS64__DU_SHIFT 4
#define MMC_IDSTS64__DU_WIDTH 1
#define MMC_IDSTS64__DU_RESET_VAL 0
#define MMC_IDSTS64__DU_RMASK 0x1
#define MMC_IDSTS64__DU_MASK  0x10
#define MMC_IDSTS64__DU_FIELD 4,4

#define MMC_IDSTS64__CES_SHIFT 5
#define MMC_IDSTS64__CES_WIDTH 1
#define MMC_IDSTS64__CES_RESET_VAL 0
#define MMC_IDSTS64__CES_RMASK 0x1
#define MMC_IDSTS64__CES_MASK  0x20
#define MMC_IDSTS64__CES_FIELD 5,5

#define MMC_IDSTS64__NIS_SHIFT 8
#define MMC_IDSTS64__NIS_WIDTH 1
#define MMC_IDSTS64__NIS_RESET_VAL 0
#define MMC_IDSTS64__NIS_RMASK 0x1
#define MMC_IDSTS64__NIS_MASK  0x100
#define MMC_IDSTS64__NIS_FIELD 8,8

#define MMC_IDSTS64__AIS_SHIFT 9
#define MMC_IDSTS64__AIS_WIDTH 1
#define MMC_IDSTS64__AIS_RESET_VAL 0
#define MMC_IDSTS64__AIS_RMASK 0x1
#define MMC_IDSTS64__AIS_MASK  0x200
#define MMC_IDSTS64__AIS_FIELD 9,9

#define MMC_IDSTS64__EB_SHIFT 10
#define MMC_IDSTS64__EB_WIDTH 3
#define MMC_IDSTS64__EB_RESET_VAL 0
#define MMC_IDSTS64__EB_RMASK 0x7
#define MMC_IDSTS64__EB_MASK  0x1c00
#define MMC_IDSTS64__EB_FIELD 10,12

#define MMC_IDSTS64__FSM_SHIFT 13
#define MMC_IDSTS64__FSM_WIDTH 4
#define MMC_IDSTS64__FSM_RESET_VAL 0
#define MMC_IDSTS64__FSM_RMASK 0xf
#define MMC_IDSTS64__FSM_MASK  0x1e000
#define MMC_IDSTS64__FSM_FIELD 13,16


/*
 * IDINTEN64.
 */
#define MMC_IDINTEN64 0x8094
#define MMC_IDINTEN64__LENGTH 0x0001

#define MMC_IDINTEN64__TI_SHIFT 0
#define MMC_IDINTEN64__TI_WIDTH 1
#define MMC_IDINTEN64__TI_RESET_VAL 0
#define MMC_IDINTEN64__TI_RMASK 0x1
#define MMC_IDINTEN64__TI_MASK  0x1
#define MMC_IDINTEN64__TI_FIELD 0,0

#define MMC_IDINTEN64__RI_SHIFT 1
#define MMC_IDINTEN64__RI_WIDTH 1
#define MMC_IDINTEN64__RI_RESET_VAL 0
#define MMC_IDINTEN64__RI_RMASK 0x1
#define MMC_IDINTEN64__RI_MASK  0x2
#define MMC_IDINTEN64__RI_FIELD 1,1

#define MMC_IDINTEN64__FBE_SHIFT 2
#define MMC_IDINTEN64__FBE_WIDTH 1
#define MMC_IDINTEN64__FBE_RESET_VAL 0
#define MMC_IDINTEN64__FBE_RMASK 0x1
#define MMC_IDINTEN64__FBE_MASK  0x4
#define MMC_IDINTEN64__FBE_FIELD 2,2

#define MMC_IDINTEN64__DU_SHIFT 4
#define MMC_IDINTEN64__DU_WIDTH 1
#define MMC_IDINTEN64__DU_RESET_VAL 0
#define MMC_IDINTEN64__DU_RMASK 0x1
#define MMC_IDINTEN64__DU_MASK  0x10
#define MMC_IDINTEN64__DU_FIELD 4,4

#define MMC_IDINTEN64__CES_SHIFT 5
#define MMC_IDINTEN64__CES_WIDTH 1
#define MMC_IDINTEN64__CES_RESET_VAL 0
#define MMC_IDINTEN64__CES_RMASK 0x1
#define MMC_IDINTEN64__CES_MASK  0x20
#define MMC_IDINTEN64__CES_FIELD 5,5

#define MMC_IDINTEN64__NI_SHIFT 8
#define MMC_IDINTEN64__NI_WIDTH 1
#define MMC_IDINTEN64__NI_RESET_VAL 0
#define MMC_IDINTEN64__NI_RMASK 0x1
#define MMC_IDINTEN64__NI_MASK  0x100
#define MMC_IDINTEN64__NI_FIELD 8,8

#define MMC_IDINTEN64__AI_SHIFT 9
#define MMC_IDINTEN64__AI_WIDTH 1
#define MMC_IDINTEN64__AI_RESET_VAL 0
#define MMC_IDINTEN64__AI_RMASK 0x1
#define MMC_IDINTEN64__AI_MASK  0x200
#define MMC_IDINTEN64__AI_FIELD 9,9


/*
 * DSCADDRL.
 */
#define MMC_DSCADDRL 0x8098
#define MMC_DSCADDRL__LENGTH 0x0001

#define MMC_DSCADDRL__HDAL_SHIFT 0
#define MMC_DSCADDRL__HDAL_WIDTH 32
#define MMC_DSCADDRL__HDAL_RESET_VAL 0
#define MMC_DSCADDRL__HDAL_RMASK 0xffffffff
#define MMC_DSCADDRL__HDAL_MASK  0xffffffff
#define MMC_DSCADDRL__HDAL_FIELD 0,31


/*
 * DSCADDRU.
 */
#define MMC_DSCADDRU 0x809c
#define MMC_DSCADDRU__LENGTH 0x0001

#define MMC_DSCADDRU__HDAU_SHIFT 0
#define MMC_DSCADDRU__HDAU_WIDTH 32
#define MMC_DSCADDRU__HDAU_RESET_VAL 0
#define MMC_DSCADDRU__HDAU_RMASK 0xffffffff
#define MMC_DSCADDRU__HDAU_MASK  0xffffffff
#define MMC_DSCADDRU__HDAU_FIELD 0,31


/*
 * BUFADDRL.
 */
#define MMC_BUFADDRL 0x80a0
#define MMC_BUFADDRL__LENGTH 0x0001

#define MMC_BUFADDRL__HBAL_SHIFT 0
#define MMC_BUFADDRL__HBAL_WIDTH 32
#define MMC_BUFADDRL__HBAL_RESET_VAL 0
#define MMC_BUFADDRL__HBAL_RMASK 0xffffffff
#define MMC_BUFADDRL__HBAL_MASK  0xffffffff
#define MMC_BUFADDRL__HBAL_FIELD 0,31


/*
 * BUFADDRU.
 */
#define MMC_BUFADDRU 0x80a4
#define MMC_BUFADDRU__LENGTH 0x0001

#define MMC_BUFADDRU__HBAU_SHIFT 0
#define MMC_BUFADDRU__HBAU_WIDTH 32
#define MMC_BUFADDRU__HBAU_RESET_VAL 0
#define MMC_BUFADDRU__HBAU_RMASK 0xffffffff
#define MMC_BUFADDRU__HBAU_MASK  0xffffffff
#define MMC_BUFADDRU__HBAU_FIELD 0,31


/*
 * CARDTHRCTL.
 */
#define MMC_CARDTHRCTL 0x8100
#define MMC_CARDTHRCTL__LENGTH 0x0001

#define MMC_CARDTHRCTL__CARDRDTHREN_SHIFT 0
#define MMC_CARDTHRCTL__CARDRDTHREN_WIDTH 1
#define MMC_CARDTHRCTL__CARDRDTHREN_RESET_VAL 0
#define MMC_CARDTHRCTL__CARDRDTHREN_RMASK 0x1
#define MMC_CARDTHRCTL__CARDRDTHREN_MASK  0x1
#define MMC_CARDTHRCTL__CARDRDTHREN_FIELD 0,0

#define MMC_CARDTHRCTL__BUSY_CLR_INT_EN_SHIFT 1
#define MMC_CARDTHRCTL__BUSY_CLR_INT_EN_WIDTH 1
#define MMC_CARDTHRCTL__BUSY_CLR_INT_EN_RESET_VAL 0
#define MMC_CARDTHRCTL__BUSY_CLR_INT_EN_RMASK 0x1
#define MMC_CARDTHRCTL__BUSY_CLR_INT_EN_MASK  0x2
#define MMC_CARDTHRCTL__BUSY_CLR_INT_EN_FIELD 1,1

#define MMC_CARDTHRCTL__CARDRDTHRESHOLD_SHIFT 16
#define MMC_CARDTHRCTL__CARDRDTHRESHOLD_WIDTH 11
#define MMC_CARDTHRCTL__CARDRDTHRESHOLD_RESET_VAL 0
#define MMC_CARDTHRCTL__CARDRDTHRESHOLD_RMASK 0x7ff
#define MMC_CARDTHRCTL__CARDRDTHRESHOLD_MASK  0x7ff0000
#define MMC_CARDTHRCTL__CARDRDTHRESHOLD_FIELD 16,26


/*
 * BACK_END_POWER_R.
 */
#define MMC_BACK_END_POWER_R 0x8104
#define MMC_BACK_END_POWER_R__LENGTH 0x0001

#define MMC_BACK_END_POWER_R__BACK_END_POWER_SHIFT 0
#define MMC_BACK_END_POWER_R__BACK_END_POWER_WIDTH 16
#define MMC_BACK_END_POWER_R__BACK_END_POWER_RESET_VAL 0
#define MMC_BACK_END_POWER_R__BACK_END_POWER_RMASK 0xffff
#define MMC_BACK_END_POWER_R__BACK_END_POWER_MASK  0xffff
#define MMC_BACK_END_POWER_R__BACK_END_POWER_FIELD 0,15


/*
 * UHS_REG_EXT.
 */
#define MMC_UHS_REG_EXT 0x8108
#define MMC_UHS_REG_EXT__LENGTH 0x0001

#define MMC_UHS_REG_EXT__MMC_VOLT_REG_SHIFT 0
#define MMC_UHS_REG_EXT__MMC_VOLT_REG_WIDTH 16
#define MMC_UHS_REG_EXT__MMC_VOLT_REG_RESET_VAL 0
#define MMC_UHS_REG_EXT__MMC_VOLT_REG_RMASK 0xffff
#define MMC_UHS_REG_EXT__MMC_VOLT_REG_MASK  0xffff
#define MMC_UHS_REG_EXT__MMC_VOLT_REG_FIELD 0,15

#define MMC_UHS_REG_EXT__CLK_SMPL_PHASE_CTRL_SHIFT 16
#define MMC_UHS_REG_EXT__CLK_SMPL_PHASE_CTRL_WIDTH 7
#define MMC_UHS_REG_EXT__CLK_SMPL_PHASE_CTRL_RESET_VAL 0
#define MMC_UHS_REG_EXT__CLK_SMPL_PHASE_CTRL_RMASK 0x7f
#define MMC_UHS_REG_EXT__CLK_SMPL_PHASE_CTRL_MASK  0x7f0000
#define MMC_UHS_REG_EXT__CLK_SMPL_PHASE_CTRL_FIELD 16,22

#define MMC_UHS_REG_EXT__CLK_DRV_PHASE_CTRL_SHIFT 23
#define MMC_UHS_REG_EXT__CLK_DRV_PHASE_CTRL_WIDTH 7
#define MMC_UHS_REG_EXT__CLK_DRV_PHASE_CTRL_RESET_VAL 0
#define MMC_UHS_REG_EXT__CLK_DRV_PHASE_CTRL_RMASK 0x7f
#define MMC_UHS_REG_EXT__CLK_DRV_PHASE_CTRL_MASK  0x3f800000
#define MMC_UHS_REG_EXT__CLK_DRV_PHASE_CTRL_FIELD 23,29

#define MMC_UHS_REG_EXT__EXT_CLK_MUX_CTRL_SHIFT 30
#define MMC_UHS_REG_EXT__EXT_CLK_MUX_CTRL_WIDTH 2
#define MMC_UHS_REG_EXT__EXT_CLK_MUX_CTRL_RESET_VAL 0
#define MMC_UHS_REG_EXT__EXT_CLK_MUX_CTRL_RMASK 0x3
#define MMC_UHS_REG_EXT__EXT_CLK_MUX_CTRL_MASK  0xc0000000
#define MMC_UHS_REG_EXT__EXT_CLK_MUX_CTRL_FIELD 30,31


/*
 * EMMC_DDR.
 */
#define MMC_EMMC_DDR 0x810c
#define MMC_EMMC_DDR__LENGTH 0x0001

#define MMC_EMMC_DDR__HALF_START_BIT_SHIFT 0
#define MMC_EMMC_DDR__HALF_START_BIT_WIDTH 1
#define MMC_EMMC_DDR__HALF_START_BIT_RESET_VAL 0
#define MMC_EMMC_DDR__HALF_START_BIT_RMASK 0x1
#define MMC_EMMC_DDR__HALF_START_BIT_MASK  0x1
#define MMC_EMMC_DDR__HALF_START_BIT_FIELD 0,0


/*
 * ENABLE_SHIFT.
 */
#define MMC_ENABLE_SHIFT 0x8110
#define MMC_ENABLE_SHIFT__LENGTH 0x0001

#define MMC_ENABLE_SHIFT__ENABLE_SHIFT_CARD_SHIFT 0
#define MMC_ENABLE_SHIFT__ENABLE_SHIFT_CARD_WIDTH 2
#define MMC_ENABLE_SHIFT__ENABLE_SHIFT_CARD_RESET_VAL 0
#define MMC_ENABLE_SHIFT__ENABLE_SHIFT_CARD_RMASK 0x3
#define MMC_ENABLE_SHIFT__ENABLE_SHIFT_CARD_MASK  0x3
#define MMC_ENABLE_SHIFT__ENABLE_SHIFT_CARD_FIELD 0,1


/*
 * FIFO.
 * MMC Data FIFO
 */
#define MMC_FIFO 0x8200
#define MMC_FIFO__LENGTH 0x0001

#define MMC_FIFO__DATA_SHIFT 0
#define MMC_FIFO__DATA_WIDTH 32
#define MMC_FIFO__DATA_RESET_VAL 0
#define MMC_FIFO__DATA_RMASK 0xffffffff
#define MMC_FIFO__DATA_MASK  0xffffffff
#define MMC_FIFO__DATA_FIELD 0,31


/* Scratchpad. */
#define MMC_SCRATCHPAD2 0xc000
#define MMC_SCRATCHPAD2__LENGTH 0x0001

#define MMC_SCRATCHPAD2__VAL_SHIFT 0
#define MMC_SCRATCHPAD2__VAL_WIDTH 32
#define MMC_SCRATCHPAD2__VAL_RESET_VAL 0
#define MMC_SCRATCHPAD2__VAL_RMASK 0xffffffff
#define MMC_SCRATCHPAD2__VAL_MASK  0xffffffff
#define MMC_SCRATCHPAD2__VAL_FIELD 0,31


/*
 * Interface Control.
 * Provides control over card-controller operations.
 */
#define MMC_INTFC_CTL 0xc008
#define MMC_INTFC_CTL__LENGTH 0x0001

#define MMC_INTFC_CTL__CARD_DET_OVD_SHIFT 0
#define MMC_INTFC_CTL__CARD_DET_OVD_WIDTH 2
#define MMC_INTFC_CTL__CARD_DET_OVD_RESET_VAL 3
#define MMC_INTFC_CTL__CARD_DET_OVD_RMASK 0x3
#define MMC_INTFC_CTL__CARD_DET_OVD_MASK  0x3
#define MMC_INTFC_CTL__CARD_DET_OVD_FIELD 0,1

#define MMC_INTFC_CTL__CARD_DET_OVD_VAL_SHIFT 2
#define MMC_INTFC_CTL__CARD_DET_OVD_VAL_WIDTH 2
#define MMC_INTFC_CTL__CARD_DET_OVD_VAL_RESET_VAL 0
#define MMC_INTFC_CTL__CARD_DET_OVD_VAL_RMASK 0x3
#define MMC_INTFC_CTL__CARD_DET_OVD_VAL_MASK  0xc
#define MMC_INTFC_CTL__CARD_DET_OVD_VAL_FIELD 2,3

#define MMC_INTFC_CTL__WRITE_PROT_OVD_SHIFT 4
#define MMC_INTFC_CTL__WRITE_PROT_OVD_WIDTH 2
#define MMC_INTFC_CTL__WRITE_PROT_OVD_RESET_VAL 3
#define MMC_INTFC_CTL__WRITE_PROT_OVD_RMASK 0x3
#define MMC_INTFC_CTL__WRITE_PROT_OVD_MASK  0x30
#define MMC_INTFC_CTL__WRITE_PROT_OVD_FIELD 4,5

#define MMC_INTFC_CTL__WRITE_PROT_OVD_VAL_SHIFT 6
#define MMC_INTFC_CTL__WRITE_PROT_OVD_VAL_WIDTH 2
#define MMC_INTFC_CTL__WRITE_PROT_OVD_VAL_RESET_VAL 0
#define MMC_INTFC_CTL__WRITE_PROT_OVD_VAL_RMASK 0x3
#define MMC_INTFC_CTL__WRITE_PROT_OVD_VAL_MASK  0xc0
#define MMC_INTFC_CTL__WRITE_PROT_OVD_VAL_FIELD 6,7

#define MMC_INTFC_CTL__CARD_INT_OVD_SHIFT 8
#define MMC_INTFC_CTL__CARD_INT_OVD_WIDTH 2
#define MMC_INTFC_CTL__CARD_INT_OVD_RESET_VAL 3
#define MMC_INTFC_CTL__CARD_INT_OVD_RMASK 0x3
#define MMC_INTFC_CTL__CARD_INT_OVD_MASK  0x300
#define MMC_INTFC_CTL__CARD_INT_OVD_FIELD 8,9

#define MMC_INTFC_CTL__CARD_INT_OVD_VAL_SHIFT 10
#define MMC_INTFC_CTL__CARD_INT_OVD_VAL_WIDTH 2
#define MMC_INTFC_CTL__CARD_INT_OVD_VAL_RESET_VAL 0
#define MMC_INTFC_CTL__CARD_INT_OVD_VAL_RMASK 0x3
#define MMC_INTFC_CTL__CARD_INT_OVD_VAL_MASK  0xc00
#define MMC_INTFC_CTL__CARD_INT_OVD_VAL_FIELD 10,11

#define MMC_INTFC_CTL__DEV_RESET_SHIFT 30
#define MMC_INTFC_CTL__DEV_RESET_WIDTH 1
#define MMC_INTFC_CTL__DEV_RESET_RESET_VAL 0
#define MMC_INTFC_CTL__DEV_RESET_RMASK 0x1
#define MMC_INTFC_CTL__DEV_RESET_MASK  0x40000000
#define MMC_INTFC_CTL__DEV_RESET_FIELD 30,30

#define MMC_INTFC_CTL__DEV_REBOOT_SHIFT 31
#define MMC_INTFC_CTL__DEV_REBOOT_WIDTH 1
#define MMC_INTFC_CTL__DEV_REBOOT_RESET_VAL 0
#define MMC_INTFC_CTL__DEV_REBOOT_RMASK 0x1
#define MMC_INTFC_CTL__DEV_REBOOT_MASK  0x80000000
#define MMC_INTFC_CTL__DEV_REBOOT_FIELD 31,31


/*
 * Clock Control.
 * Provides control over eclk PLL.
 */
#define MMC_HX_CLOCK_CONTROL 0xc010
#define MMC_HX_CLOCK_CONTROL__LENGTH 0x0001

#define MMC_HX_CLOCK_CONTROL__ENA_SHIFT 0
#define MMC_HX_CLOCK_CONTROL__ENA_WIDTH 1
#define MMC_HX_CLOCK_CONTROL__ENA_RMASK 0x1
#define MMC_HX_CLOCK_CONTROL__ENA_MASK  0x1
#define MMC_HX_CLOCK_CONTROL__ENA_FIELD 0,0

#define MMC_HX_CLOCK_CONTROL__PLL_OD_SHIFT 1
#define MMC_HX_CLOCK_CONTROL__PLL_OD_WIDTH 4
#define MMC_HX_CLOCK_CONTROL__PLL_OD_RESET_VAL 3
#define MMC_HX_CLOCK_CONTROL__PLL_OD_RMASK 0xf
#define MMC_HX_CLOCK_CONTROL__PLL_OD_MASK  0x1e
#define MMC_HX_CLOCK_CONTROL__PLL_OD_FIELD 1,4

#define MMC_HX_CLOCK_CONTROL__PLL_R_SHIFT 5
#define MMC_HX_CLOCK_CONTROL__PLL_R_WIDTH 6
#define MMC_HX_CLOCK_CONTROL__PLL_R_RESET_VAL 4
#define MMC_HX_CLOCK_CONTROL__PLL_R_RMASK 0x3f
#define MMC_HX_CLOCK_CONTROL__PLL_R_MASK  0x7e0
#define MMC_HX_CLOCK_CONTROL__PLL_R_FIELD 5,10

#define MMC_HX_CLOCK_CONTROL__PLL_F_SHIFT 11
#define MMC_HX_CLOCK_CONTROL__PLL_F_WIDTH 13
#define MMC_HX_CLOCK_CONTROL__PLL_F_RESET_VAL 127
#define MMC_HX_CLOCK_CONTROL__PLL_F_RMASK 0x1fff
#define MMC_HX_CLOCK_CONTROL__PLL_F_MASK  0xfff800
#define MMC_HX_CLOCK_CONTROL__PLL_F_FIELD 11,23

#define MMC_HX_CLOCK_CONTROL__PLL_RSVD_SHIFT 24
#define MMC_HX_CLOCK_CONTROL__PLL_RSVD_WIDTH 7
#define MMC_HX_CLOCK_CONTROL__PLL_RSVD_RESET_VAL 0
#define MMC_HX_CLOCK_CONTROL__PLL_RSVD_RMASK 0x7f
#define MMC_HX_CLOCK_CONTROL__PLL_RSVD_MASK  0x7f000000
#define MMC_HX_CLOCK_CONTROL__PLL_RSVD_FIELD 24,30

#define MMC_HX_CLOCK_CONTROL__CLOCK_READY_SHIFT 31
#define MMC_HX_CLOCK_CONTROL__CLOCK_READY_WIDTH 1
#define MMC_HX_CLOCK_CONTROL__CLOCK_READY_RESET_VAL 0
#define MMC_HX_CLOCK_CONTROL__CLOCK_READY_RMASK 0x1
#define MMC_HX_CLOCK_CONTROL__CLOCK_READY_MASK  0x80000000
#define MMC_HX_CLOCK_CONTROL__CLOCK_READY_FIELD 31,31


/*
 * Interface Status.
 * Scratchpad
 */
#define MMC_INTFC_STS 0xc018
#define MMC_INTFC_STS__LENGTH 0x0001

#define MMC_INTFC_STS__BOOT_ENA_SHIFT 0
#define MMC_INTFC_STS__BOOT_ENA_WIDTH 1
#define MMC_INTFC_STS__BOOT_ENA_RESET_VAL 0
#define MMC_INTFC_STS__BOOT_ENA_RMASK 0x1
#define MMC_INTFC_STS__BOOT_ENA_MASK  0x1
#define MMC_INTFC_STS__BOOT_ENA_FIELD 0,0

#define MMC_INTFC_STS__BOOT_STATE_SHIFT 1
#define MMC_INTFC_STS__BOOT_STATE_WIDTH 4
#define MMC_INTFC_STS__BOOT_STATE_RESET_VAL 0
#define MMC_INTFC_STS__BOOT_STATE_RMASK 0xf
#define MMC_INTFC_STS__BOOT_STATE_MASK  0x1e
#define MMC_INTFC_STS__BOOT_STATE_FIELD 1,4

#define MMC_INTFC_STS__BOOT_RECORD_STATE_SHIFT 8
#define MMC_INTFC_STS__BOOT_RECORD_STATE_WIDTH 3
#define MMC_INTFC_STS__BOOT_RECORD_STATE_RESET_VAL 0
#define MMC_INTFC_STS__BOOT_RECORD_STATE_RMASK 0x7
#define MMC_INTFC_STS__BOOT_RECORD_STATE_MASK  0x700
#define MMC_INTFC_STS__BOOT_RECORD_STATE_FIELD 8,10

#define MMC_INTFC_STS__BOOT_REVID_SHIFT 16
#define MMC_INTFC_STS__BOOT_REVID_WIDTH 8
#define MMC_INTFC_STS__BOOT_REVID_RESET_VAL 0
#define MMC_INTFC_STS__BOOT_REVID_RMASK 0xff
#define MMC_INTFC_STS__BOOT_REVID_MASK  0xff0000
#define MMC_INTFC_STS__BOOT_REVID_FIELD 16,23


/*
 * Boot Configuration.
 * Boot configuration parameters. This register initialized on HARD_RESET_N
 * deassertion but is left intact on soft reset.
 */
#define MMC_BOOT_CFG 0xc020
#define MMC_BOOT_CFG__LENGTH 0x0001

#define MMC_BOOT_CFG__BOOT_SIZE_MULT_SHIFT 0
#define MMC_BOOT_CFG__BOOT_SIZE_MULT_WIDTH 8
#define MMC_BOOT_CFG__BOOT_SIZE_MULT_RESET_VAL 255
#define MMC_BOOT_CFG__BOOT_SIZE_MULT_RMASK 0xff
#define MMC_BOOT_CFG__BOOT_SIZE_MULT_MASK  0xff
#define MMC_BOOT_CFG__BOOT_SIZE_MULT_FIELD 0,7

#define MMC_BOOT_CFG__ALT_BOOT_WIDTH_SHIFT 8
#define MMC_BOOT_CFG__ALT_BOOT_WIDTH_WIDTH 2
#define MMC_BOOT_CFG__ALT_BOOT_WIDTH_RESET_VAL 2
#define MMC_BOOT_CFG__ALT_BOOT_WIDTH_RMASK 0x3
#define MMC_BOOT_CFG__ALT_BOOT_WIDTH_MASK  0x300
#define MMC_BOOT_CFG__ALT_BOOT_WIDTH_FIELD 8,9
#define MMC_BOOT_CFG__ALT_BOOT_WIDTH_VAL_X1 0x0
#define MMC_BOOT_CFG__ALT_BOOT_WIDTH_VAL_X4 0x1
#define MMC_BOOT_CFG__ALT_BOOT_WIDTH_VAL_X8 0x2

#define MMC_BOOT_CFG__LEGACY_BOOT_MODE_SHIFT 10
#define MMC_BOOT_CFG__LEGACY_BOOT_MODE_WIDTH 1
#define MMC_BOOT_CFG__LEGACY_BOOT_MODE_RMASK 0x1
#define MMC_BOOT_CFG__LEGACY_BOOT_MODE_MASK  0x400
#define MMC_BOOT_CFG__LEGACY_BOOT_MODE_FIELD 10,10

#endif /* !defined(__DOXYGEN__) */

#endif /* !defined(__REGS_MMC_DEF_H__) */
